### ISSUE TITLE
Comunidad Vietur 6/11

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#1]
@FAAREIA : creo este repositorio y este ticket para arrancar a construir la comunidad Vietur, que sería la verdad de la Comunidad de Vendedores para la empresa Vietur.

La web para que veas un poco la onda es esta:
http://www.vietur.com.ar/

LOGO
Link para descargar el logo en distintos formatos https://www.dropbox.com/sh/sjc33cvoh4qrmvy/AAAaDSj0e87cvWkREK6k0EWIa?dl=0

COLORES
Los colores son bastante similares a la Comunidad actual. Vienen del logo. 
Azul: Pantone C 655 / Rojo: Pantone C 1797

Acá tenés variantes de color que utilizan por región del mundo de cada viaje. POdés ver a qué región pertenecen en la web.
https://www.dropbox.com/sh/828jqdqhyygrjz6/AACL9seLp1zDfx144Tg581Kba?dl=0

PRIMERA ENTREGA
Avancemos con un diseño de la home para el 6/11
En principio cambiarían:
. el background
. el logo (te lo mando la semana que viene)
. el footer
. los rojos de Klaukol por el rojo de Vietur
. los azules de Klaukol por el azul de Vietur.

abrazo

**Comment by FAAREIA** [comment]
Avanzo con esto o busco soluciones para lo de la impresión del presupuesto y tarjeta?

**Comment by FAAREIA** [comment]
- ¿Va a ser igual que el Club de Colocadores actual?
- ¿Mismas secciones?
- ¿Misma funcionalidad para usuario anónimo y registrado?

**Comment by LeandroBraier** [comment]
Primero presupuesto y tarjeta. Esto tiene fecha del 06/11 para la primer
entrega, hay más tiempo.

La base es la Comunidad de Vendedores, no el Club de Colocadores. Mismo
funcionalidad y secciones que Vendedores.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-10-28 11:01 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
@braulio-evangelisti

**Comment by braulio-evangelisti** [comment]
Lo paso al otro issue, se ve que tenia los dos abiertos y lo pegue acá al link.

**Comment by LeandroBraier** [comment]
Brau, esto va en otro ticket. Más allá de eso, te pasé dos imágenes en las cuales hay una espacios blanco abajo como para que el texto vaya ahi y se lea bien. Esa es la idea. Fijate cómo acomodar la foto en función de eso.

**Comment by braulio-evangelisti** [comment]
Buen día Lea, aca fue subiendo Login + Home el viernes

http://www.benteveo.tv/_comunidad-vietur/

Abrazo

**Comment by LeandroBraier** [comment]
Buenisimo Brau! Gracias! Quedó muy bueno. 

Te paso feedback para retocar y así poder luego mandar al cliente a preaprobar.
1. La imagen de fondo, no nos gusta la textura degradé de azul a rojo. Eso lo hace muy oscuro, cuando debería ser lo contrario…bien luminoso. Retocar eso para que quede bien luminoso ese fondo.
2. La imagen de la valija no va, pero estamos diseñando el slideshow y te lo pasamos aparte
3. El botón de "Empezá a jugar acá" que tenga una forma más tradicional, no la que pidieron en Parex. Puede ser redonda como la del Ingresar del login. Fijate que el rojo sigue siendo el de Klaukol, no el de Vietur que es más opaco.
4. Parece que lo que se ganan SON FICHAS, así que acá habría que volver a la estética de las fichas de Casino que teníamos en las primeras versiones de la Comunidad. Me refiero solo al embed de los tickets a la derecha que dice: "Mis logros".

abrazo

**Comment by braulio-evangelisti** [comment]
Lea estuve acomodando las modificaciones pedidas, salvo lo de la valija que quedo a la espera del slide.

Abrazo

**Comment by LeandroBraier** [comment]
Chicos, ya tengo el logo de la Comunidad Vie Tur que va y los tres slides principales.

LOGO
![logo-comunidad-vie-tur2-01](https://cloud.githubusercontent.com/assets/6719872/11160094/7d8448b4-8a44-11e5-95eb-e9e469d56f21.png)

SLIDES
<img width="1280" alt="slide01 transparente" src="https://cloud.githubusercontent.com/assets/6719872/11160086/6fae4b68-8a44-11e5-94b0-ac8fe0e8b5bc.png">
<img width="1280" alt="slide02 transparente" src="https://cloud.githubusercontent.com/assets/6719872/11160085/6fad477c-8a44-11e5-8b22-a1731147a31a.png">
<img width="1280" alt="slide03 transparente" src="https://cloud.githubusercontent.com/assets/6719872/11160087/6fb1f01a-8a44-11e5-9bc3-7f4a088d3d2b.png">

Porfa subanlos el lunes y avisenme cuando esté online así ahí le pasamos al cliente la primera entrega y tenemos feedback para seguir trabajando.

En lo que pueden ir avanzando es en lo que hablamos con @FAAREIA hoy por Skype: en la página de "Mis logros" debería decir cómo se sumaron los puntos. Por ejemplo: XX por ver un video, XX por responder una trivia, etc.

Ahí incluiríamos, cuando lo tengamos, cuánto sumaron por vender productos de Vie Tur, lo cual se va a cargar por un Excel desde backend como hacemos para el Torneo de Potenciados.

**Comment by LeandroBraier** [comment]
abrazo y buen fin de semana!!

**Comment by mkreyness** [comment]
Hosting ? Por ahora siempre en benteveo.tv ?

**Comment by LeandroBraier** [comment]
Si, por ahora si. En cuanto nos den la primer aprobación quizá ya podemos
ver de comprar uno nuevo o meterlo en el mismo de la web de ellos a lo sumo.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Ojo con "el de la web de ellos", no todo hosting se banca cualquier programacion o base de datos.
Hay que averiguar primero que tipo de hosting tienen antes de decidir meterlo en la actual.

**Comment by LeandroBraier** [comment]
Dale, tomo noto MK. Probablemente sea un hosting medio antiguo. De última
vemos cómo utilizar el dominio desde 2 hostings distintos. Se puede eso?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2015-11-13 21:10 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Si, no hay problema, siempre se puede hacer un SUBdominio que este en un hosting diferente, como (tarde) se me ocurrio para maraton.parexklaukol.com.ar

**Comment by braulio-evangelisti** [comment]
Lea no tendran un psd, ai, o el logo en png pero sin fondo? Va a hacer mas rápido que si me pongo a recortarlo

**Comment by LeandroBraier** [comment]
Brau, pero son todos PNG transparentes. Simplemente reemplazá los slides que tenés ahora ne la plataforma por esos 3. Y con respecto al logo también, es un PNG transparentes. 

Ahora si querés te paso el PSD pero para qué te serviría? Lo que te pasé ya está listo para subir. Bajalo con el botón derecho como imagen.

**Comment by braulio-evangelisti** [comment]
Es lo que hice, y me los baja como png pero tienen una sola capa con fondo blanco y bastante borde, te paso una captura:

![captura](https://cloud.githubusercontent.com/assets/11272253/11183298/b9962cb6-8c4f-11e5-97e4-d98cc3e159be.jpg)

**Comment by LeandroBraier** [comment]
Tenés razón, no me di cuenta. Ahi te mando el illustrator por gmail.

Los slides si están bien, no?

**Comment by braulio-evangelisti** [comment]
si, es el logo nomas

**Comment by braulio-evangelisti** [comment]
Ahi le puse el logo nuevo y los slides lea.

Abrazo

**Comment by LeandroBraier** [comment]
Chicos, podemos avanzar un poco con esto. Hay cambios en la estética del login y en los slides de la home. Los slides los voy a estar pasando a la tarde, pero les paso aquí los cambios en la estética del login así los podemos aplicar hoy mismo.

https://www.wetransfer.com/downloads/ac68d2e6d0a28e5d63ad59e7dfd10d0420151125121951/fba43f85e7af9e28b8edb4dfa5b10bb420151125121951/754680

abrazo

**Comment by braulio-evangelisti** [comment]
Ya estan aplicados los cambios en el login.

Abrazo

**Comment by LeandroBraier** [comment]
Gracias Brau!

Apenas tenga los slides te lo paso.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
@braulio-evangelisti , te paso los slides que quedan para subir. Creo que cambia un poco el tamaño, tendrías que adaptar la maquetación para que queden bien.

<img width="608" alt="slide-01 transp" src="https://cloud.githubusercontent.com/assets/6719872/11429394/f2916e28-9455-11e5-8fb6-168ebf5e562f.png">
<img width="608" alt="slide-02 transp" src="https://cloud.githubusercontent.com/assets/6719872/11429395/f2939be4-9455-11e5-84d3-bbbf76be702b.png">
<img width="608" alt="slide-03 transp" src="https://cloud.githubusercontent.com/assets/6719872/11429396/f299dec8-9455-11e5-89bd-4de7c7238da9.png">

abrazo

**Comment by braulio-evangelisti** [comment]
Buen día Lea

Ya subí los 3, tenias razón, tuve que acomodar un toque porque tienen elementos que se salen del ancho del contenedor, pero creo que ahí quedó. Actualiza y avisame cualquier cosa.

http://www.benteveo.tv/_comunidad-vietur/home.html

Abrazo

**Comment by LeandroBraier** [comment]
Gracias Brau! Quedó excelente.

**Comment by LeandroBraier** [comment]
Chicos, gran éxito la Comunidad, les encantó.

Solo me pidieron al pie, en el footer de la web, 

1) agregar un loguito más a los que pusieron ahí. Sería este:

![10072_1](https://cloud.githubusercontent.com/assets/6719872/11592055/1475a61e-9a7b-11e5-94f6-f60c088a1c70.jpg)

2) Quitarles los links a todos esos logitos. Que queden sin vínculo, como en la página web de ellos.

Si hay más cambios los veremos la semana que viene. abrazo grande

**Comment by braulio-evangelisti** [comment]
Buenísimo Lea.

Hecho!

Abrazo.

**Comment by LeandroBraier** [comment]
Gracias Brau! Abrazo y buen finde largo!

Igual @FAAREIA sigamos avanzando con el resto de la plataforma sobre esta misma estética. Avisame cuando esté lista para cargarle contenidos y demás, porque está aprobado para seguir.

NUEVA DINÁMICA DE VENTAS
Más allá de las funcionalidades actuales de la Comunidad de Vendedores, @mkreyness vamos a necesitar algo más: se trata de sumarle la posibilidad de cargar via Excel un puntaje de ventas de cada vendedor que se sume automáticamente a los puntos que ese vendedor acumula en la Comunidad. Podemos ir avanzando con eso MK? Es un sistema igual que el Torneo de Potenciados. @FAAREIA abría que agregar una tabla como la de Objetivos del Torneo de Potenciados en el Perfil del Vendedor bajo el titulo de Tus Ventas.

Me confirman si está todo OK?

abrazo

**Comment by mkreyness** [comment]
Podemos establecer un formato simple y fijo ? Lo que viene en Torneos no se puede levantar automatico, tiene mucha porqueria debajo y detectar que es lo bueno y que no, es algo totalmente manual.
Lo ideal seria que fuera un formato TAB separated (no CSV, porque CSV depende de la configuracion de la maquina de c/u) que contenga simplemente:
numero de vendedor <tab> puntaje
Sin titulos, sin totales, sin cuentas, sin comentarios, sin aclaraciones, sin notas, sin hojas de calculos previos, solo algo asi

1<tab>100
2<tab>300
7<tab>80
etc.

Ahora bien: es importante definir si ese puntaje SUMA o REEMPLAZA al preexistente.
Porque vos decis "suma", pero en torneos siempre fue "reemplaza".
Sabiendo esto se puede hacer una interface que les permita elegir de un popup el periodo al que aplica (año y semestre o trimestre o como lo vayan a manejar), la fecha de actualizacion (que el sistema sugiere la del dia) y el boton de upload para este archivo.

Otra cosa, que yo no estuve siguiendo esto de Vietur: ya arreglaron como va a ser el hosting ? Acordate los comentarios que hice en su momento sobre hostear "donde tienen la pagina ahora"

**Comment by LeandroBraier** [comment]
MK, te respondo.

1) Si, puede ser un sistema simple. En qué formato? Si te paso un excel de dos columnas te sirve? Te puedo pasar un excel de dos columnas: CÓDIGO VENDEDOR/ PUNTOS

El código sería el nombre de usuario, por ejemplo, JuanLopez.

2) La respuesta es SUMA, no reemplaza. Es levemente diferente, tal como decís. Cargar la fecha de la actualización alcanzaría. No sé si hace falta el período. Total todo se suma.

3) El hosting no arreglamos aún. Para la semana del 14 que estoy de vuelta tramito el hosting. Pasame las características que debe tener. Es un Inicio? Multisitio? https://www.duplika.com/#planes

O necesitamos un Onyx?

**Comment by LeandroBraier** [comment]
Fede como venimos con esto?  Para la semana que viene me estan pidiendo ver
la comunidad entera (no hace falta que esté lo de "mis ventas" aun)

**Comment by LeandroBraier** [comment]
Buen día!! Repaso para los dos:

@mkreyness : el excel sería así: CÓDIGO VENDEDOR/ MONTOS VENDIDOS EN DOLARES/ PUNTOS (="Columna anterior"*30/100) 

Espero tu confirmación de que estamos OK con esa estructura de excel (o si preferís que quede solo en dos columnas: codigo vendedor/puntos) y tu confirmación de qué tipo de hosting necesitamos contratar así lo pido.

@FAAREIA necesito ver todo el resto de la plataforma online. A qué hora podemos verlo? Aunque sea a un nivel de avance considerable, aunque falten detalles de ajuste de programación.

Espero tu respuesta lo antes posible porfa, porque mañana tenemos reunión con el cliente en torno a esto.

abraz

**Comment by braulio-evangelisti** [comment]
Buen día Lea te paso links: 

http://www.benteveo.tv/_comunidad-vietur/usuario-perfil.html
http://www.benteveo.tv/_comunidad-vietur/bases-condiciones.html
http://www.benteveo.tv/_comunidad-vietur/juegos.html
http://www.benteveo.tv/_comunidad-vietur/juego-id.html
http://www.benteveo.tv/_comunidad-vietur/trivia-id.html
http://www.benteveo.tv/_comunidad-vietur/trivia-completa.html
http://www.benteveo.tv/_comunidad-vietur/ganadores.html

Los juegos van a ser videos tambien?

**Comment by LeandroBraier** [comment]
Excelente Brau!!! Ya está todo de maquetación o también funcional? Los juegos no son siempre videos con trivias. Hay también juegos HTML5 y posteos de Facebook a compartir

@mkreyness porfa apenas puedas pasame el acceso al CMS desde donde pueda cargar los juegos y dinámicas.

abrazo grande

**Comment by mkreyness** [comment]
el excel no debe contener nada CALCULADO.
Solo datos en bruto.
Por lo que decis seria codigo de vendedor y dolares.
Yo en la interface le voy a poner que seleccionen periodo y si suma o reemplaza.
Yo no tengo absolutamente nada hecho de esto, lo primero es tener hosting, sin hosting no tengo donde trabajar. Un server cualquier como los de Duplika, como el de Parex. Si eso es Onyx, que sea Onyx.
Meterlo en el server de Benteveo es totalmente contraproducente, se mezclarian problemas con los de DelViento que ya esta hosteado ahi y no debiera. No quiero seguir propagando ese problema.
Despues tengo que rehacer montones de cosas al cambiarlo a otra plataforma.

**Comment by LeandroBraier** [comment]
Entiendo MK. Entonces necesitamos pedir un Onyx, ya lo tramito.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2015-12-14 9:18 GMT-03:00 mkreyness notifications@github.com:

**Comment by braulio-evangelisti** [comment]
Es maquetación todavia. Voy a cambiar un poco el listado de **juegos.html** entonces ya que van a ser diferentes tipos de juegos.

**Comment by braulio-evangelisti** [comment]
Buen día Lea. Cambié un poco el listado de juegos.

http://www.benteveo.tv/_comunidad-vietur/juegos.html

Qué seria lo próximo que necesitas para esto?

Abrazo

**Comment by LeandroBraier** [comment]
Gracias Brau! Acá lo estoy mostrando al cliente desde el nuevo hosting que me pasó Fede.

En cuanto a la programación, pudieron trasladarla toda o esto es solo maquetación?

http://209.133.209.166/~vieturco/

**Comment by braulio-evangelisti** [comment]
Maquetación todavía.

**Comment by LeandroBraier** [comment]
Entiendo. Cuando podríamos tener la programación también? Me refiero a
trasladar lo que está en Vendedores de Parex. Para eso no necesitamos
pedirselo a MK no?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
apenas me confirmen que hay ssh habilitado empiezo a trabajar en eso.

**Comment by braulio-evangelisti** [comment]
Ya tengo los templates de vendedores para pasarle la programacion. Calculo que para esta semana puede estar listo sino hay que hacer mas modificaciones a la maqueta. Lo único es que ya no se va a poder usar mas para mostrar porque no va a tener contenido cargado.

**Comment by mkreyness** [comment]
pero hacelo sobre una copia Braulio, a los templates poneles "T" al final. No pierdas los originales.

**Comment by braulio-evangelisti** [comment]
:+1:

**Comment by FAAREIA** [comment]
Marce, te describo aca rápidamente para abrir el ticket. No lo hago yo porque haría un copy paste de tu explicación.
1. https://clientes.duplika.com/clientarea.php
2. Te logueas con los accesos que pasó mariana hoy a las 13:59.
3. https://soporte.duplika.com/support/tickets
4. Escribis la consulta y a esperar.

**Comment by mkreyness** [comment]
listo, puse la consulta con mi email en vez de info@benteveo.tv, porque si no le llega que se yo a quien y no va a saber que hacer con eso.

**Comment by braulio-evangelisti** [comment]
Acá esta pasada a template lo que ya esta de la maqueta

http://209.133.209.166/~vieturco/templates/

Probablemente tenga errores o malas referencias. Si podes pegarle una revisada @mkreyness y me avisas así voy acomodando lo que me digas.

**Comment by mkreyness** [comment]
Gracias, en cuanto logre que la gente de soporte de Duplika entienda que me tiene que habiltar el SSH que ellos dicen que ya esta habilitado pero no es cierto, lo miro.

**Comment by LeandroBraier** [comment]
Hubo novedades de esto @mkreyness ?

**Comment by mkreyness** [comment]
Si, ya logre que me den el acceso, pero igual como perdio prioridad este tema no le di mas bolilla.
Llegue antes de eso a instalar algunas cosas mias y bajar una base de datos para ir modificando sobre eso, pero nada mas.

**Comment by LeandroBraier** [comment]
Ok, para cuando podríamos tenerlo listo con programación y todo y sumando lo del excel de ventas etc?

Para el 30 ponele? O ya para enero?

**Comment by mkreyness** [comment]
Por lo que dijo Ezequiel esto no tiene ninguna prioridad por ahora, ya que hay que llegar al 14 de Enero con lo del Toro Paty. Definamoslo en la reunion de hoy, pero dedicacion fuerte no le voy a dar hasta pasado el 14 de enero.

**Comment by LeandroBraier** [comment]
Ok, entiendo. Ahora en la reunión lo hablamos.

Yo quería saber cuánto podías avanzar antes de arrancar con paty, porque
por lo menos todo lo que está en Vendedores Klaukol ya está hecho, solo
habría que replicarlo. De hecho le pedí a Braulio que lo replicara así vos
solo tendrías que rechequear y resolver el tema del CMS.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2015-12-21 15:54 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Y si, en eso estaba yo y cuando salio esto de Paty y dije "bueno, ahora estoy con lo de Vietur..."  y me lo patearon para despues.
Supongo que va a ser un trabajo muy mecanico (no lo del toro, lo de Vietur) pero esos son los mas propensos a error, porque en vez de pensar lo que uno esta haciendo reemplaza, y puede quedar un link que se vaya a cualquier lado.

**Comment by mkreyness** [comment]
@LeandroBraier y 
@braulio-evangelisti un par de cositas para ir tocando:
en el login dice "Subscribite", en castellano es "Suscribite" nomas. 
Al hacer click en "Registrate" me pide en UN SOLO CAMPO nombre y apellido. Como siempre pido, habria que separarlo.
Por ultimo, esto es para @LeandroBraier : vamos a usar como codigo de usuario el DNI, no ?
Aclaracion para @braulio-evangelisti : estoy usando una copia de tu index.html con nombre login.html.
El index definitivo supongo que va a redireccionar a la home (sin estar loggeado).
Los templates los puse en /templates/vendedores porque si despues hay otras cosas no quiero que se pisen los nombres.
Pueden ir mirando como queda la home (faltan arreglar algunas cosas, pero que dependen de este tema de loggeo) en

http://comunidad.vietur.com.ar/cgi-bin/mainvendedores.pl

**Comment by LeandroBraier** [comment]
Respondo MK:

1- Cambiemos a "Suscribite"
2- @FAAREIA hagamos 2 campos como siempre porfa.
3- @mkreyness si usemos el DNI.

abrazo y muy feliz año para todos!!

**Comment by braulio-evangelisti** [comment]
Listo 1 y 2.

Feliz año!

**Comment by LeandroBraier** [comment]
Buen día @braulio-evangelisti cómo andan? 

1) Les paso el link al video instructivo que va en la home de la Comunidad. Lo podrían subir hoy reemplazando el video de YouTube que embebieron provisoriamente?

https://player.vimeo.com/video/151764090

2) Necesitaría que en el listado de juegos hagan un formato igual al de la Comunidad de Vendedores ParexKlaukol. Es decir, en lugar de aparecer como está ahora la Comunidad VIE TUR, que se vea como una lista horizontal como la de ParexKlaukol. Esto si pudiera ser para hoy o mañana a la mañana estamos bien.

Me confirman por favor?

Desde ya muchas gracias!

abrazo

**Comment by LeandroBraier** [comment]
@FAAREIA si estás online por ahi se pueden ayudar y de paso coordinar para el skype de esta tarde.

**Comment by braulio-evangelisti** [comment]
si llego bien con esto para hoy a ultima hora o mañana

**Comment by LeandroBraier** [comment]
Perfecto @braulio-evangelisti Ojo coordiná con @mkreyness para no pisar el template que hizo él. Trabajá directamente sobre lo que él ya hizo.

**Comment by mkreyness** [comment]
@LeandroBraier  la lista de juegos de vendedores siempre fue vertical.
No querras decir la lista de juegos de COLOCADORES, que es horizontal ?

@braulio-evangelisti 
El template que toma el sistema para esto es el que esta en http://comunidad.vietur.com.ar/templates/vendedores/juegosT.html

Ojo que ahi nunca vas a ver mas de UN article, porque la iteracion la hago yo por programa (reemplazo todo por una lista de tantos articles como haga falta).
Supongo que lo que tenes que cambiar esta mas bien en la clase del div que contiene a los articles.

**Comment by LeandroBraier** [comment]
@mkreyness yo me refiero a esto.

Así está en VIE TUR, con el titulo imagen y puntos en VERTICAL

![captura de pantalla 2016-01-14 a las 2 21 39 p m](https://cloud.githubusercontent.com/assets/6719872/12331286/afbb0d5a-bac7-11e5-859e-97ffcec989b1.png)

Así está en PAREX, con el titulo, imagen y puntos en HORIZONTAL

![captura de pantalla 2016-01-14 a las 2 21 43 p m](https://cloud.githubusercontent.com/assets/6719872/12331290/b32f8ee8-bac7-11e5-9d0e-b5c0fa156234.png)

**Comment by mkreyness** [comment]
Ah ok, entonces es solo un tema DENTRO del article, @braulio-evangelisti 
No deberias tener problema en modificarlo sobre el template que dije.

**Comment by braulio-evangelisti** [comment]
Lea ahi subi los cambios, en la home el video y la distribucion de los juegos en lista.

@mkreyness para avisarte que archivos modifique, los html los baje hace un rato y modifique siguiendo desde ahi.

**/public_html/templates/vendedores/mainT.html** (creo que esta es la home no?)
**/public_html/templates/vendedores/juegosT.html**
**/public_html/css/estilos.css**

La lista de juegos no la pude chequear como quedo porque no tengo acceso pero tendria que andar bien.

**Comment by LeandroBraier** [comment]
Está mejor @braulio-evangelisti pero parece haber un error por ahi. Mirá la captura:

<img width="700" alt="captura de pantalla 2016-01-14 a las 5 45 00 p m" src="https://cloud.githubusercontent.com/assets/6719872/12336596/168600c8-bae4-11e5-9bed-044ec1d289f3.png">

**Comment by braulio-evangelisti** [comment]
Me podras pasar algun user/pass de fantasia asi reviso especificamente el error?

**Comment by LeandroBraier** [comment]
http://comunidad.vietur.com.ar/cgi-bin/juegos.pl?usuario=XX&clave=XX

user: mk

clave: pepe

**Comment by braulio-evangelisti** [comment]
Ahi lo vi

@mkreyness 

puede ser que 

```
<!--puntosjuego-->
```

 este imprimiendo un 

```
< div class="puntos" ></ div >
```

 ademas de los datos en juegosT.html?

**Comment by mkreyness** [comment]
no veo lo que decis, github se lo debe estar tragando. Usa el markdown.

**Comment by braulio-evangelisti** [comment]
actualice el comentario se ve ahora?

**Comment by mkreyness** [comment]
Si, ahora se ve. 
Si, hace eso porque lo de marcar como hecho o no es dinamico, a cada participante primero le aparece como no hecho, y despues como hecho.
En caso de estar "hecho" el programa pone TODO esto, fijo (asi me habra dicho Fede en su momento)

`<div class="puntos hecho"><svg class="inline"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="img/constante.svg#tick"></use></svg> Hecho</div>`

y si no, pone esto:

`<div class="puntos">+XXXX</div>`

donde XXXX son los puntos que vale el juego.

**Comment by mkreyness** [comment]
Lo que haga falta cambiar de ahi decime y lo ajusto inmediatamente.

**Comment by braulio-evangelisti** [comment]
ah perfecto, ahi lo acomode, deje la variable sola ya que imprime el div contendor que necesite

@LeandroBraier fijate ahora

**Comment by LeandroBraier** [comment]
Ahora si, perfecto!! Gracias a los dos!!

Solo te pido @braulio-evangelisti si podés hacer que quede bien el link de volver a la Home que hay en el logo de arriba a la derecha. Ahora está tirando error 404.

**Comment by braulio-evangelisti** [comment]
listo

**Comment by LeandroBraier** [comment]
Faltan los parámetros de usuarios @braulio-evangelisti 

Cuando hago clic me lleva a la home pero me desloggea.

**Comment by braulio-evangelisti** [comment]
Ahi acomode el link, habia dos comillas de mas, deben haber quedado al ponerle las variables, de todos modos me lleva a una pagina en blanco, a vos te hace lo mismo ahora?

**Comment by LeandroBraier** [comment]
Yo lo sigo viendo igual. Me deslogea. Hablalo con @mkreyness porfa. Creo
que tenés que agregarle a la URL esta parte:

&usuario=&clave=

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-01-14 21:10 GMT-03:00 Braulio Evangelisti notifications@github.com:

**Comment by braulio-evangelisti** [comment]
Ah en el logo, pense que habiamos pasado de hablar del logo, a hablar del link "mi perfil" cuando desplegas en el nombre del usuario.

Ahi tendria que andar lo del logo

**Comment by mkreyness** [comment]
En el template aside-usuarioT.html no se por que estaba lleno de unos "#" donde deberia decir 
perfilvendedores.
Ya lo corregi, pero igual como no hay un perfilT.html en la carpeta, muestra una pagina en blanco.
Ahi lo estoy armando en base al usuario-perfil.html.
Les aviso cuando ande.

**Comment by braulio-evangelisti** [comment]
yo hice un **usuario-perfilT.html** con las variables creo que lo subi en /public_html/templates/vendedores con el resto, avisame cualquier cosa y te lo mando por mail sino

**Comment by mkreyness** [comment]
ahh, ok, es que se tenia que llamar perfilT.html.
Ahi lo renombre y anda, mas o menos, le tengo que hacer unos retoques al programa entonces.
