### ISSUE TITLE
Subir Template de Mailing de Bienvenida VIE TUR a Mailchimp. HOY

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#10]
@FAAREIA necesito que me subas el mailing de bienvenida de VIE TUR a Mailchimp para reenviarlos a toda la base de usuarios.

Los mailings que enviamos con @mkreyness desde Duplika tuvieron mucho rebote o no llegaron. 

Si esto funciona necesitaría que me subas también el de Vendedores y Colocadores. Pero veamos primero la de VIE TUR.

**Comment by FAAREIA** [comment]
@braulio-evangelisti 
Copio a braulio asi esta en tema.
Cuál es el último mailing de bienvenida de vietur? Link?

**Comment by LeandroBraier** [comment]
Es este tengo entendido:

http://comunidad.vietur.com.ar/_mailing/bienvenida-comunidad/bienvenida-comunidad.html

http://comunidad.vietur.com.ar/_mailing/bienvenida-comunidad/bienvenida-comunidad.html

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Ahi ya pude meterme a mailchimp y crear el template, se llama "VIETUR - Bienvenida"

**Comment by LeandroBraier** [comment]
Gracias Fede! Ya está habilitado para enviar?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Mmmmmm, desconozco como es el proceso. Faltaría poner las variables y asociarlas a un mailing-list.
Copio a marce @mkreyness

**Comment by mkreyness** [comment]
yo estoy sin acceso al mailchimp.
Hay que agregar en la mailing list un campo de tipo URL (esto es fundamental, no sirve poner un texto que se reemplace porque no funciona), y dos campos que si son de texto para usuario y clave por eso que se los repetimos mas abajo.
En el template hay que hacer referencia como en el caso que ya vieron con esos MMERGE3 MMERGE4, los nombre que le pone mailchimp a los campos de la base.
Yo voy a agregar estos 3 campos a la consulta de datos de vendedores  de la base para que los puedan exportar con URL incluido, que tiene un dato adicional aparte de esos.

**Comment by LeandroBraier** [comment]
Ok, avisame MK así yo creo la lista en Mailchimp y les digo con qué merge
quedó nombrada cada columna.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-03-07 14:01 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Ya hay una "Exportacion de Vendedores" donde te viene email, nombre, apellido, usuario, clave y URL.
Podes elegir por estado (los que tienen estado "INGRESO" ya no hace falta remandarles nada porque estan verificados que les llego).
Los que dicen "PENDIENTE" esta por salir el automatico en los proximos minutos, no deberia nunca haber muchos.
El estado "MAIL RECHAZADO" en realidad es que no se pudo ni mandar, habria que agarrar del monitoreo de CPanel los que realmente dicen que fueron rechazados y cambiarles el estado para que por lo menos sepamos que el mail esta mal y es al cuete mandarle.

**Comment by LeandroBraier** [comment]
Gracias MK! En qué parte del CPanel está eso?

**Comment by mkreyness** [comment]
En la seccion que esta todo lo relativo a mails, hay un punto que dice "Monitorizacion de envios", no se por no que "monitoreo", pero bueno.

**Comment by LeandroBraier** [comment]
Gracias @mkreyness ! Me pasarías el acceso a este Cpanel? No lo encuentro.

**Comment by mkreyness** [comment]
http://comunidad.vietur.com.ar:2082
user vieturco 
pass lo tenes en el mail del alta de la cuenta

**Comment by LeandroBraier** [comment]
Gracias MK!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
@mkreyness y @FAAREIA ya cargué la lista y creé la campaña con el template que hicieron.

Faltaría:

1) Corregir lo siguiente en el template:

Cambiar el siguiente texto: 

_Para eso deberán sumar puntos en la plataforma completando sus perfiles, capacitándose a través de contenidos y participando de trivias y juegos online que hablan sobre lo que más conoce: los viajes_

Por el siguiente:

_Para eso deberán sumar puntos en la plataforma completando sus perfiles, vendiendo productos VIE TUR, capacitándose a través de contenidos y participando de trivias y juegos online que hablan sobre lo que más conoce: los viajes._

2) Chequear los MERGE (no encontré cómo customizar el título del mail ni qué MERGE es cada columna.

3) Podemos crear un mail info@comunidad.vietur.com.ar ? Si pudiéramos sería ideal para cambiar el mail que puse en la lista de VIE TUR.

4) Avisarme que está todo así envío esta campaña tipo 10.30 hs.

Gracias!!!

**Comment by mkreyness** [comment]
2) Los MMERGE son en el orden de los campos de la base, conta de 1 en adelante y esos son los que corresponden. Igual siempre podes hacer una base de prueba separada y correr la campaña contra esa para no correr riesgos.
3) Lamentablemente no. Duplika me ofrece crear direcciones xxx @ vietur.com.ar y sabemos que eso no va a funcionar porque no llegaria nunca a nuestro server: nosotros NO manejamos el registro MX de viatur.com.ar y por lo tanto de ninguno de sus subdominios tampoco.

**Comment by LeandroBraier** [comment]
3) Ok no problem entonces. Uds corrigen 1 y 2 entonces?

**Comment by mkreyness** [comment]
yo estoy sin acceso

**Comment by LeandroBraier** [comment]
Ok. Le pedis hoy a Eze o lo pyede solucionar Fede?

**Comment by mkreyness** [comment]
Entiendo que lo que decis que hay que corregir es todo texto del template, no solo lo puede sino que lo debe hacer Fede, yo si lo toco capaz lo rompo, y en el template puede verificar que figuren las variables MMERGE en el orden/nombre que figuren en la maillist.
El asunto es que PRUEBES, duplica la maillist pero sin datos, pegale los datos de tu usuario leandro@benteveo.tv y mandate la campaña solito. La idea de todo esto es que puedan hacerlo sin mi intervencion.

**Comment by FAAREIA** [comment]
LEa el texto ya lo cambié, ahora estoy viendo todo esto de los MMERGE

**Comment by LeandroBraier** [comment]
Dale, genial. Gracias Fede! Espero tu confirmación entonces.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Ahi ya pude aprender como es lo de mailchimp. Me cree una lista, después una campaña que usa la lista y el template indicado.
Ahora, la lista es de prueba nomas y lee cree los MERGE. Ya estan aplicados al template y las variables las podes ver [aca](https://us11.admin.mailchimp.com/lists/settings/merge-tags?id=347993)
Tendrias que replicar eso a tu lista original, o usar esa misma lista y cambiar su nombre y su config porque cambié quien la manda.

Cualquier cosa avisa!
Abrazo

**Comment by LeandroBraier** [comment]
Fede, porfa hacemela más fácil. Si la probaste y funciona, pasá estas
variables a la lista que yo ya creé ayer. Se llama Comunidad VIE TUR.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-03-08 9:54 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Job done!
Ahi me fije que tu lista tenga las variables llenas para cada usuario y las tiene. Lo único que me surge es un tema con la URL. @mkreyness 
La URL del template original era:
`http://comunidad.vietur.com.ar/cgi-bin/mainvendedores.pl?especial=A&usuario=B&clave=C`
Ahora la que vi que tienen 2 usuarios es:
`http://www.comunidad.vietur.com.ar/cgi-bin/mainvendedores.pl?dni=ECarrillo&clave=Eleonora`
Mi pregunta es: ¿dónde quedaron las variables "especial" y "usuario"? ¿porque ahora hay una variable "dni"?

**Comment by LeandroBraier** [comment]
Gracias Fede!

Estoy viendo que el formato correcto es el tuyo, porque es el que aparece
en los mailings de bienvenida. Tendría que cambiarlas todas no?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-03-08 10:11 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Esperemos a ver que dice marce pero imagino que si. @mkreyness 
La variables "especial" no se que contenido tiene que tener.

**Comment by FAAREIA** [comment]
Resumiendo en el template original estan las variables
especial (no se que contenido va)
usuario
clave

En el nuevo estan:
dni (es un falso nombre-apellido)
clave

**Comment by LeandroBraier** [comment]
El dni es lo mismo que usuario, solo consulto cuál es la estructura de link
que queda asi ya salimos.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-03-08 10:33 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
La estructura es:
`http://www.comunidad.vietur.com.ar/cgi-bin/mainvendedores.pl?especial=A&usuario=B&clave=C`

`especial=A`
Hay que reemplazar "A" por un valor que desconozco

`usuario=B`
Hay que reemplazar "B" por el nombre de usuario

`clave=C`
Hay que reemplazar "C" por la clave del usuario

**Comment by LeandroBraier** [comment]
Gracias Fede!! MK, nos aclaras el tema? Sobre todo el valor A.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-03-08 11:25 GMT-03:00 Federico Arena notifications@github.com:

**Comment by mkreyness** [comment]
no hay que reemplazar nada, en el campo "URL" que esta en la base de datos que se exporta del sistema va el URL COMPLETO, con todos los detalles particulares de cada usuario.
NO tenes que tratarlo como partes, no hay nada variable, es un unico campo de TIPO URL, eso es muy importante, tenes que dejar que Mailchimp lo maneje, vos solo tenes que poner que es el MMERGEx que corresponda. Exactamente igual que en el template de LaleyendaPaty

**Comment by mkreyness** [comment]
Los campos de usuario y clave que pongo SEPARADOS del URL en la exportacion de datos es para los campos FUERA DEL URL donde se le muestran al receptor del mail cuales son su usuario y clave, para que los SEPA, pero no para que los USE ahi.

**Comment by LeandroBraier** [comment]
Ok, Fede ya modifiqué las URL en mi lista. Para eso tuve que borrar todos
los subscriptos y volverlos a subir. Eso anula lo que hiciste vos o los
merge quedan puestos?

Digo así ya puedo hacer el envío.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-03-08 12:53 GMT-03:00 mkreyness notifications@github.com:

**Comment by FAAREIA** [comment]
Lea la lista se exportó bien, si vas por ejemplo a [este link](https://us11.admin.mailchimp.com/lists/members/view?id=202381265&use_segment=Y), ves que el usuario tienen en cada campo el valor que corresponde.

**Lo que todavía no quedó claro es el valor que corresponde a "especial".**

##### Esta URL es la del template original:

`http://comunidad.vietur.com.ar/cgi-bin/mainvendedores.pl?especial=<!--especial-->&usuario=<!--usuario-->&clave=<!--clave-->`

##### Esta URL es la de un usuario de la lista de VIE TUR en MailChimp:

`http://comunidad.vietur.com.ar/cgi-bin/mainvendedores.pl?especial=A&usuario=ALlanos&clave=Alfredo`

#### Pregunta

Lea estableció que `especial` tenga valor `A`. ¿Eso es correcto o va otro valor @mkreyness ?

**Comment by LeandroBraier** [comment]
MK, confirmanos que el valor de Especial es A para todos y ya mando porfa.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-03-08 14:26 GMT-03:00 Federico Arena notifications@github.com:

**Comment by mkreyness** [comment]
NooOOOoooOOOOooooOOOOooOOOOO
El URL NO SE ARMA.
"URL" es el nombre de una variable que hay que definir de tipo URL, y yo ya exporto CON EL CONTENIDO COMPLETO.
No tiene por que mirar lo que hay ADENTRO del URL, olvidense del contenido, es algo FIJO que yo estoy poniendo COMPLETO, TOTAL, SIN PARTES que rellenar.
No miren lo que dice, no escriban el URL ustedes, solo pongan `*|MMERGE4|*` o 3 o el numero que sea, NO traten de armar el contenido en base a partes. NO contiene variables el URL.

**Comment by mkreyness** [comment]
Por favor miren lo que sale de la exportacion, aca pongo UN renglon de ejemplo:
`ariiadna.rojas@hotmail.com`  (email)
`Ariadna`  (nombre)
`Rojas` (apellido)
`AriadnaRojas` (usuario)
`rojas` (clave)
`http://comunidad.vietur.com.ar/cgi-bin/mainvendedores.pl?usuario=AriadnaRojas&clave=rojas&especial=1117c90dd60372698f141f594723cafbc8a80021` (URL)

ven que el URL ya esta armado y tiene  todo lo que tiene que tener ? NO hay que armarlo

**Comment by mkreyness** [comment]
es exactamente lo mismo que se hizo en LaLeyendaPaty, ahi teniamos 2 URls, uno para un GIF y otro para entrar. Este es como el de entrar, es mas SIMPLE que el de Paty.

**Comment by mkreyness** [comment]
por eso en el de Paty habia un MMERGE3 y un MMERGE4.
Aca hay mas variables pero URL hay uno solo, segun mis cuentas seria MMERGE6

**Comment by FAAREIA** [comment]
Ya esta todo seteado, el MERGE se llama "URL" pero creo que Lea no sabe cómo o de dónde saca esa url que ya esta armada. El exportó e importó datos pero esa URL nunca llegó a mailchimp, sino otra que desconozco su origen

**Comment by mkreyness** [comment]
buaahhh, esta todo en el mismo excel que se exporta, es la ultima columna.
El punto de menu en el CMS se llama "Exportacion de Datos de Vendedores"

**Comment by LeandroBraier** [comment]
La había exportado del lugar equivocado! Perdón. Qué hago? Resubo toda la
base? O con la URL que estamos ahora podemos salir igual?

Es la misma que en los mailings de bienvenida.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-03-08 16:52 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Usen lo que arme por favor, si no no tenemos como saber si la persona se loggeo.

**Comment by LeandroBraier** [comment]
Éxito! Pudimos enviar el mail correctamente! Ya entró el 20% de la base. Gracias!
