### ISSUE TITLE
SUmar Olvidé mi contraseña en Login VIE TUR

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#11]
@FAAREIA nos está faltando esto. No olviden de testearlo que funcione bien. Usemos el mailing de bienvenida como mail de recortario.

abrazo

**Comment by FAAREIA** [comment]
@mkreyness 
Ya esta listo el HTML para recuperar clave:
http://comunidad.vietur.com.ar/recuperar-clave.html

Marce, cuando este listo avisame que habilito el link desde el login.
Abrazo

**Comment by mkreyness** [comment]
Ojo dice "recuperla" en vez de "recuperala".
Cambiale en el form lo que dice "mainvendedores.pl" por "olvidovendedores.pl" y el login.html tendria que tener algun div oculto que diga "en unos minutos recibiras un mail con tu contraseña" o algo asi, y otro de error que diga tipo "Ese email no figura registrado". Yo voy a mandar un contacto=1 en el primer caso y contacto=2 en el segundo.

**Comment by FAAREIA** [comment]
Ok, pero mejor dejemos el mensaje de error o éxito en la misma url, no nos vayamos de ahi. Vos queres ir al login.html por alguna razón?
Si le llega el mail con la clave desde ahi puede ir al login y listo.

**Comment by mkreyness** [comment]
El mail con la clave ya tiene el link para entrar. Yo digo para que no vuelva a hacer send por error del mismo forgot, pero me da igual.
Agregalos y avisame asi yo pongo el resto del codigo que muestra el div que corresponda.

**Comment by FAAREIA** [comment]
http://comunidad.vietur.com.ar/recuperar-clave.html
http://comunidad.vietur.com.ar/recuperar-clave.html?contacto=1
http://comunidad.vietur.com.ar/recuperar-clave.html?contacto=2

**Comment by LeandroBraier** [comment]
No sé por qué varias versiones, yo las veo todas iguales. Tampoco entiendo
por qué el pop up rojo. Probé poner mi mail registrado y me dio error 505.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
no esta terminado @LeandroBraier, me los esta pasando a mi.
Estamos trabajando.

**Comment by mkreyness** [comment]
listo, esta andando. Supuestamente @LeandroBraier deberia haberte llegado el mail de recordatorio de una prueba que hice yo de entrar.
OJO que debido a esto quedaste de nuevo como usuario activo, porque el mecanismo de mandar el mail pisa el estado. Deberia NO mandarle la password a usuarios suspendidos, no ?

**Comment by LeandroBraier** [comment]
Me llegó bien!

Exacto MK. No debería mandarle a usuarios suspendidos.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-03-09 18:12 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
te parece en caso de estar suspendido que le digamos eso, "Su cuenta esta suspendida" en vez de "Ese email no esta registrado" ? O no hace falta ?

**Comment by LeandroBraier** [comment]
Si digamoslo por las dudas. Porque si se intenta registrar con ese mismo
mail no va a poder verdad?

**Comment by mkreyness** [comment]
Exactamente, no se puede repetir mail en una nueva registracion. Ahora le agrego esa validacion y ese cartel entonces.

**Comment by mkreyness** [comment]
Listo. Tu cuenta esta suspendida ahora, fijate como sale

**Comment by LeandroBraier** [comment]
Perfecto!! Gracias a los dos!!
