### ISSUE TITLE
Password Usuario Mantenimiento VIE TUR

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#12]
@mkreyness necesito la password del usuario mantenimiento en el CMS de VIE TUR.

**Comment by mkreyness** [comment]
turvie

**Comment by LeandroBraier** [comment]
Gracias!

**Comment by LeandroBraier** [comment]
@mkreyness necesito que quites lo de las fotos de ahi y me agregues ahi visibles:

"Exportación de datos de vendedores"

y

"Slides de Vendedores"

**Comment by LeandroBraier** [comment]
Necesito que en la "exportacion de datos" incluyas la fecha de registración.

**Comment by mkreyness** [comment]
no estamos guardando ese dato.
Te puedo poner la fecha de la primera vez que ingreso al sistema y se le dieron los puntos por entrar, que es lo mismo.

**Comment by LeandroBraier** [comment]
Ok. Pero no podemos empezar a guardar el dato de la registración?

**Comment by LeandroBraier** [comment]
Es lo mismo, tenés razón. Olvidate. Agregalo nomás.

**Comment by mkreyness** [comment]
ya te hice los cambios en menues, pero ojo: el usuario "Mantenimiento" no esta dado de alta con nivel suficiente como para modificar slides, queres que puedan modificarlos ? Le bajo el nivel de seguridad a esa pantalla.

**Comment by mkreyness** [comment]
Ya esta agregado el dato de fecha de ingreso en la EXPORTACION.

**Comment by LeandroBraier** [comment]
Por ahora no, asi está perfecto. Mil gracias MK!

**Comment by LeandroBraier** [comment]
@mkreyness necesito que le des posibilidad de modificar slides y sumes la lista de vendedores pero que eso si no lo pueda editar.

Se puede?

**Comment by LeandroBraier** [comment]
No te preocupes, ponele la lista de vendedores con permisos de edición total. Está perfecto así. Avisame cuando lo tengas porfa.

**Comment by LeandroBraier** [comment]
@mkreyness cuando va a estar listo esto para avisarle al cliente?

Necesito que agregues la lista de vendedores y que todas las listas que tenga el cliente en este acceso sean editables por él.

abrazo

**Comment by mkreyness** [comment]
no sabia que habias agregado cosas a este thread.
La catarata de mails que llegan de cosas ajenas muchas veces me tapan las mias.
Si llegan cuando estoy online las veo, pero la acumulacion de varias horas es imposible ver todo, si no te contesto algo en el dia SEGURO es que no lo vi.
Ahora lo hago, me lleva 5 minutos

**Comment by mkreyness** [comment]
Ahi lo puse sin permiso de edicion sobre vendedores, pero si queres le agrego los permisos de edicion, como vos necesites.

**Comment by LeandroBraier** [comment]
Si, pongamosle permiso de edición también, por las dudas. Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
listo. Y arregle las imagenes que no se veian

**Comment by LeandroBraier** [comment]
Gracias @mkreyness ! abrazo

**Comment by LeandroBraier** [comment]
@mkreyness mañana le voy a pasar el admin directamente a la gente de VIE TUR para que ellos empiecen a cargar los contenidos. Podemos llegar a tener algún problema? Solo confirmame eso.

**Comment by mkreyness** [comment]
Es una pregunta muy general. El acceso que le vas a dar les permite borrar cosas, si despues de borradas dicen que "desaparecieron", no tengo como demostrar que las borraron ellos, pero seguro las borraron ellos.

**Comment by LeandroBraier** [comment]
Ok. En tal caso, no se puede permitir todo SALVO que eliminen objetos? Es
mucho lio eso?

**Comment by mkreyness** [comment]
Ok, puedo directamente desactivar el boton eliminar de cada cosa, en general igual se los puede poner en estado "ELIMINADO" (que no es mas que una marquita, pero no borra nada).

**Comment by LeandroBraier** [comment]
Dale, perfecto. Hagamos asi!!

**Comment by mkreyness** [comment]
listo
