### ISSUE TITLE
Mailings de Bienvenida automáticos

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#14]
@mkreyness están automatizados los mailings de bienvenida ya? Salen con copia a gabriela@vietur.com.ar ?

Recordá que los de bienvenida tienen que quedar automáticos y con copia a ella en todos. 

@FAAREIA fijate que en Mailchimp le borré al mailing la línea que dice "Estimado vendedor". Borré todo el DIV que tiene esa frase. Lo corregirías porfa en la versión online?

**Comment by mkreyness** [comment]
Si, pero hay que ver si a ella le llegan.
Es facil de probar: date de alta con algun mail que no hayas usado antes, y en UN RATO (no es inmediato) te va a llegar el mail. Ese mismo mail esta Bcc: ella.

**Comment by LeandroBraier** [comment]
Pero ella me dice que sigue sin recibir ni 1 solo. No sé qué más decirle.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-03-10 14:38 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
En la monitorizacion de envios de duplika por cada mail que se mando figura una copia a gabriela@vietur.com.ar, mira:

![image](https://cloud.githubusercontent.com/assets/6135791/13681211/f50017e0-e6da-11e5-81d5-90e888c046c2.png)

**Comment by LeandroBraier** [comment]
Gracias MK! Con esto le puedo responder. Te aviso qué me dice.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Me dice que entonces probemos copiar a: newsletter@vietur.com.ar

**Comment by mkreyness** [comment]
hecho. Veremos.

**Comment by LeandroBraier** [comment]
Gracias!! Me acaba de decir el cliente que es newsletters@vietur.com.ar Faltaba una S.

Disculpas, estos son los bueyos con que aro jeje abrazo

**Comment by mkreyness** [comment]
cambiado.

**Comment by LeandroBraier** [comment]
Mil gracias MK!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Ahi le agregué esa línea lea

Abrazo

**Comment by LeandroBraier** [comment]
Gracias Fede!!!
