### ISSUE TITLE
Bug URGENTE en VIE TUR (revival del problema en Vendedores Parex)

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#15]
@mkreyness otra vez falla el botón de compartir de Facebook en las dinámicas de compartir.

http://comunidad.vietur.com.ar/cgi-bin/jugar.pl?id=13&usuario=LBraya02&clave=vietur

Fijate qué pasa porfa y resolvelo. Peude que facebook haya cambiado algo, yo el link lo subí tal cual los links que subimos en vendedores parex.

abrazo

**Comment by mkreyness** [comment]
y la pagina esta completamente ROTA, esta tomando otro template.
Vietur NO es igual que Parex, cada uno fue teniendo cambios y parches segun lo que necesitabas en cada uno. Ahora reviso.

**Comment by LeandroBraier** [comment]
Entiendo. Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-03-11 16:31 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Este template en particular que estaba usando tenia una referencia vieja (a cuando todavia no estaba el subdominio comunidad.vietur) y hacia cualquier huevada. Fijate ahora como lo ves.

**Comment by LeandroBraier** [comment]
Gracias MK! 

Ahora me tira este error al clickear en "compartir":

<img width="668" alt="captura de pantalla 2016-03-11 a las 5 08 39 p m" src="https://cloud.githubusercontent.com/assets/6719872/13713714/3b24f4d8-e7a9-11e5-93ad-ad1bd2e8a231.png">

**Comment by mkreyness** [comment]
mmm, a mi  me anda bien, quiere decir que el App que cree para VIETUR no la aprobaron, ahora veo que me dicen.

**Comment by mkreyness** [comment]
a ver proba ahora, ya deberia estar suficientemente completo el perfil del App como para que se pueda usar.

**Comment by LeandroBraier** [comment]
Ahora me funciona y me comparte pero no veo registrada la actividad. Es porque estoy suspendido?

**Comment by mkreyness** [comment]
Y si, me dijiste que de los suspendidos no se muestre la actividad.
Pero siempre podes dessuspenderte via el CMS y despues volverte a suspender.

**Comment by mkreyness** [comment]
O ver la actividad por el CMS.

**Comment by LeandroBraier** [comment]
Entiendo. Pero ese es el tema. Busqué la actividad dentro del usuario en el CMS y no la veo impactada.

<img width="1271" alt="captura de pantalla 2016-03-11 a las 5 36 32 p m" src="https://cloud.githubusercontent.com/assets/6719872/13714379/f9d308f4-e7ac-11e5-917c-3e4e53be28f0.png">

**Comment by mkreyness** [comment]
pero no podes tener mas de 95 puntos, acordate. Si ya tenias 15, y esto tiene mas de 80, sonaste. Convendria que te dessuscribas para poder hacer pruebas, si no estas probando un entorno falso y diferente al que ve la gente.

**Comment by LeandroBraier** [comment]
Entonces entonces. Solo quería quedarme tranquilo que está funcionando. Gracias MK!!! abrazo grande

**Comment by mkreyness** [comment]
Ojo, que no te ande por que estas suspendido, no significa que a un no-suspendido SI le ande, yo diria que pruebes como no-suspendido antes que lluevan puteadas.

**Comment by LeandroBraier** [comment]
Confirmé el usuario y lo volví a hacer.  No sumó los puntos.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Urgente porfa resolvelo.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-03-11 17:45 GMT-03:00 Leandro Braier leandrobraier@gmail.com:

**Comment by mkreyness** [comment]
a ver proba de nuevo ahora

**Comment by LeandroBraier** [comment]
Ahora si MK! Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
el programa que suma los puntos (ni idea por que) no tenia permiso de ejecucion.

**Comment by LeandroBraier** [comment]
Lo importante es que está.  Gracias MK!
