### ISSUE TITLE
Usuarios a sumar en VIE TUR

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#16]
@mkreyness te paso un excel con nuevo usuarios a sumar. Cuando estén arriba avisame y les mando los mailings por mailchimp.

[Usuarios a Sumar en VIE TUR 11-03.xlsx](https://github.com/LeandroBraier/Vietur/files/169464/Usuarios.a.Sumar.en.VIE.TUR.11-03.xlsx)

abrazo

**Comment by mkreyness** [comment]
con el tema del bug me quedo recolgado esto y me olvide. Hay un tema: si yo los cargo, el proceso automatico inmediatamente intentaria mandarles, porque estarian en estado "PENDIENTE". Tengo que inventar un estado nuevo que sea "PENDIENTE MAILCHIMP" para que tomes esos, pero despues  quien les va a cambiar el estado a "ENVIADO" ?

**Comment by LeandroBraier** [comment]
Yo se lo cambio a mano. No hay problema. Si pudiera hacerlo de forma
conjunta en todos genial. Para no hacerlo de a uno.

**Comment by mkreyness** [comment]
Te agrego un boton en la exportacion que diga "Pasar todos los Pendientes MAILCHIMP a enviado", eso es facil.

**Comment by LeandroBraier** [comment]
Gracias MK!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
en el curso de la mañana los subo y te dejo todo listo para que los mandes cuando quieras.

**Comment by mkreyness** [comment]
Ya estan subidos. Habia una tal "Mara Martinez" que dio usuario repetido.
Tenia otro email pero parece ser la misma persona, la que esta cargada dice que trabaja en la "Asociacion Italiana" y esta nueva tiene mail italiantur@fibertel.com.ar.
Por si acaso no la cargue.
Todos estan cargados con el estado "PENDIENTE MAICHIMP", con lo cual mi proceso automatico los va a ignorar.
Una vez que hayas hecho la exportacion y el envio, entras a CUALQUIERA de ellos desde la pantalla de Exportacion (no desde la consulta de vendedores) y vas a ver que hay un boton "Marcar Enviados Mailchimp". Lo apretas una vez y te pasa TODOS los que decian "PENDIENTE MAILCHIMP" como "ENVIADO", a partir de ahi para el sistema es lo mismo que si hubieran salido automatico.

**Comment by LeandroBraier** [comment]
Excelente MK!! Muchas gracias!! abrazo

2016-03-13 10:17 GMT-03:00 mkreyness notifications@github.com:

**Comment by LeandroBraier** [comment]
Hecho MK! Funcionó muy bien!

Mantengamos lo mismo para Comunidad de Vendedores, te parece?

**Comment by mkreyness** [comment]
Te referis a Klaukol ?
Lo que pasa es que ahi hay muchos mailings diferentes, es medio complicado llevar un estado por cada mailing

**Comment by LeandroBraier** [comment]
Entiendo entiendo. Igual no te parece que deberíamos hacer lo mismo en
cuanto a mailchimp para los mailings de bienvenida particularmente?

Digo para mayor seguridad de que estén llegando a destino.

**Comment by mkreyness** [comment]
Seguro, vos decis por altas masivas, ya que ahi no hay registracion. 
Bueno, cuando haya que dar la proxima alta masiva hacemos esto mismo y ya queda.

**Comment by LeandroBraier** [comment]
Dale, genial. Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-03-14 10:30 GMT-03:00 mkreyness notifications@github.com:
