### ISSUE TITLE
Nuevo Bug en Comunidad VIE TUR

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#17]
@mkreyness este juego directamente no aparece:

http://comunidad.vietur.com.ar/cgi-bin/jugar.pl?id=14

usuario=LBraya02
clave=vietur

**Comment by mkreyness** [comment]
es que es una mezcolanza, tenes en el mismo tema un juego de compartir y un juego de trivia, no se puede hacer eso. Eliminale el juego de compartir.

**Comment by LeandroBraier** [comment]
El juego es una trivia. Ok. Ahi lo eliminé al de Compartir, pero sigo sin
verlo online.

Tema aparte: Entonces si alguien hace clic en el botón de Compartir no suma
puntos?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-03-14 11:28 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Debe ser porque le falta un video, pusiste la imagen en el campo de video pero no tenes juego que sea video. 
Fijate como esta hecho algun otro trivia en VIE TUR que tenga una trivia solo con imagen.

El boton de compartir existe y funciona SIEMPRE en todos los juegos.

Cuando ponemos que un juego es "tipo COMPARTIR" significa que lo UNICO que tiene es el compartir. Es un placeholder para que haya ALGO en la parte de juegos, si no el tema se queda sin nada y no aparece.

**Comment by LeandroBraier** [comment]
Yo no tengo un espacio en TEMA donde setear qué tipo de juego es. Eso se
hace solo, te acordás?

En VIE TUR nunca tuvimos trivia solo con foto. Es la primera esta. En
Vendedores hace rato lo tenemos. Tenés que fijarte como lo resolviste ahí y
hacer lo mismo. No podemos tomar todo lo hecho en vendedores y pasarlo a
VIE TUR? Es una lástima volver a repetir todos los tropiezos de vuelta si
ya los aprendimos.

2016-03-14 12:21 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Mas o menos, las decisiones que tomás sobre donde poner un dato (si en la imagen o en el video) son las cosas que el programa toma para saber que template usar, mezclado con que TIPOS le pones a los juegos que estan vinculados con el tema (eso si lo haces voluntariamente, cuando cargas el juego!).
No puedo tomar todo lo hecho en KLAUKOL (vendedores son todos) y pasarlo a VIE TUR porque hay cosas que se hicieron en VIE TUR que nunca existieron en KLAUKOL y viceversa.
Justamente muchas cosas quedaron incompatibles entre si por hacer parches de cada lado.

Probaste cambiarle el URL de la imagen al campo de imagen en vez de ponerlo en el de video ? El hecho de que este en el de video es el que hace que vaya a buscar un juego tipo video y no lo encuentra.

**Comment by LeandroBraier** [comment]
En el campo de imagen la imagen está cargada. Siempre copio la url de ahi y
la pego en el de video porque vos me lo pediste para Vendedores de Klaukol.
Es un parche al que me acostumbré digamos.

Ahora le borré la url del campo de video y sigue igual todo. No me abre.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-03-14 12:34 GMT-03:00 mkreyness notifications@github.com:

**Comment by LeandroBraier** [comment]
@mkreyness sigue todo igual. Cuando va a estar corregido? Esto lo tengo que mandar hoy si o si.

**Comment by mkreyness** [comment]
estuve ausente un par de horas, ahora me fijo y lo arreglo.

**Comment by mkreyness** [comment]
listo, no estaba creado el template para este caso. ahi lo fabrique.

**Comment by LeandroBraier** [comment]
Gracias MK!!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399
