### ISSUE TITLE
Chart de Ventas de los Vendedores en el Perfil de Comunidad VIE TUR

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#18]
@FAAREIA y @mkreyness dentro de la semana que viene necesitaría que aparezcan visibles las ventas de cada vendedor en su perfil. El miercoles me van a pasar el excel para subir. Logré simplificar la ecuación: 1 dolar es 1 punto (no me acuerdo MK como habíamos quedado que era la ecuación, pero ahora es 1 a 1 por suerte).

Cualquier duda avisame, incluso mañana cuando tengas el tiempo vos.

@FAAREIA podés tomar de base el chart que usabamos para el Torneo de Potenciados, para las ventas de cada corralón.

abrazo

**Comment by FAAREIA** [comment]
Aca dejo el link para que puedan ir viendo la tabla:
http://comunidad.vietur.com.ar/perfil.html (Denle F5)

Hay que cambiarle los colores pero la base está. ¿Cada columna de la tabla de va a mantener?

**Comment by LeandroBraier** [comment]
Gracias Fede! Lo pusiste tal cual en el Torneo pero no va tal cual.

Por un lado, solo se va a ver en el chart los siguientes datos:

Usuario / Nombre / Apellido / Ventas en USD / Puntos acumulados

Por el otro lado, adaptalo a los colores de VIE TUR: Rojo y azul.

abrazo

2016-03-21 11:25 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Dale F5, ahi la estilicé correctamente.

**Comment by LeandroBraier** [comment]
Está perfecto Fede! Gracias! MK, recordá que es 1 a 1, como en los 90. Así
que 1 dolar 1 punto. Sé que eso implica que las 2 columnas digan lo mismo
pero es la idea.

abrazo

**Comment by mkreyness** [comment]
No entiendo bien  el concepto de "usuario/nombre/apellido", quienes son ?
Porque estamos parados en el perfil de UN usuario cualquiera de ellos, aca no hay "representantes".
Necesito ver el Excel que te van a pasar para entender como organizar la informacion.

**Comment by LeandroBraier** [comment]
Me van a pasar un excel que tiene estos datos. 

Las columnas que va a tener son:

Codigo(=Usuario)/Nombre/Apellido/Dolares/Puntos

**Comment by LeandroBraier** [comment]
@mkreyness ya tengo los puntos de marzo para cargar. La fecha de actualización es HOY 28/3

[Puntos VIE TUR Marzo.xlsx](https://github.com/LeandroBraier/Vietur/files/192609/Puntos.VIE.TUR.Marzo.xlsx)

me avisás cuando esté actualizado en la Comunidad?

abrazo

**Comment by mkreyness** [comment]
ojo que no esta implementado lo de verlo en el perfil todavia, mas alla de que los cargue.
Es una pavada, pero tambien tengo que hacerlo. Para mañana antes de 9:30 va a estar.

**Comment by LeandroBraier** [comment]
Perfecto MK! Gracias!

2016-03-28 21:29 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
el problema es que sigo sin entender lo que va en el perfil.
Estamos hablando de UN usuario. Por que poner una columna con "usuario" y otra con "nombre", si es si mismo ?
Me refiero a esto:

![image](https://cloud.githubusercontent.com/assets/6135791/14097892/9973b820-f54c-11e5-9a1f-d7a77a611f68.png)

No tendrian mas bien que ser los PERIODOS ? Y con un total abajo ?

**Comment by LeandroBraier** [comment]
Tenés razón @mkreyness . Yo te voy a seguir pasando el excel igual, pero en el chart de "Tu Perfil" deberíamos reemplazar la columna de Usuario por la de Fecha, y que esa fecha sea la del día en que te mandó el excel. Con eso quedaríamos bien, no?

**Comment by mkreyness** [comment]
es lo unico que tendria sentido. Ok  Los datos ya los cargue, ahora veo si puedo hacer rapidito esto y te aviso.

**Comment by LeandroBraier** [comment]
Gracias MK! 

No te olvides porfa de los numeros de socio de colocadores que te pedí en este ticket: https://github.com/LeandroBraier/Klaukol/issues/285

abrazo

**Comment by mkreyness** [comment]
Listo VIE TUR.
Colocadores es otro lado, ahora me estoy yendo, despues me fijo en cuanto pueda.

**Comment by LeandroBraier** [comment]
Ok, porfa necesito poder tenerlo dentro del día de hoy, aunque sea a la
tarde.

Es solo poder descargarme los números de socio de cada colocador.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
@mkreyness entendí que ya estaba listo VIE TUR pero el cliente me dice que no ve los puntos cargados en los usuarios.

<img width="1133" alt="captura de pantalla 2016-03-29 a las 11 08 00 a m" src="https://cloud.githubusercontent.com/assets/6719872/14110147/a13d1020-f59b-11e5-8e33-3ab66615e3c0.png">

**Comment by LeandroBraier** [comment]
Porfa apenas puedas tomar esto avisame

**Comment by mkreyness** [comment]
Pero no tiene nada que ver, estos son los puntos por JUGAR, nunca me dijiste que los que me pasaban se sumaban para tickets, es asi ?
Yo pense que era otra cosa.

**Comment by mkreyness** [comment]
Porque si suman, ademas tengo que agregarles montones de tickets a cada uno de estos.

**Comment by LeandroBraier** [comment]
Claro, MK. Los puntos por ventas son muchísimo más importantes para el
cliente que los puntos por jugar, pero los dos suman a lo mismo. Y cada 100
puntos hay 1 ticket.

**Comment by mkreyness** [comment]
ok, pero entonces es mucho mas complicado de lo que pensaba, porque no puedo por simplemente ingresar un excel que automaticamente se asignen los tickets, estos son poca gente pero en cuanto haya mas va a ser un despelote.
Ahora le agrego todo a mano a nivel puntos y tickets.

**Comment by mkreyness** [comment]
y tiene que aparece como actividad "fulanito gano 7318 puntos por ventas" ?
Porque en tal caso habria que dar de alta un "juego" que tenga el texto adecuado, seria ese ?

**Comment by mkreyness** [comment]
ya estan todos los puntos sumados y los tickets generados.

**Comment by LeandroBraier** [comment]
Gracias MK! Si me piden lo del juego te aviso.

Lo que si deberia haber es un pop up que avise que sumaron x puntos por
ventas. Lo podemos incorporar al inicio?

**Comment by mkreyness** [comment]
con que frecuencia se van a incorporar estos puntajes ? Porque tengo que hacer algo para que se lo muestre una sola vez por cada incorporacion.
Pregunta: la proxima vez que manden van a ser un importe y puntos A SUMAR, no un ACUMULADO como mandaba Klaukol, no ? Porque si no es un despelote andar restandole lo que ya se le dio antes.

**Comment by LeandroBraier** [comment]
Se cargan todos los 24 de cada mes. Cada excel va a ser mensual, no
acumulado.  Me parece que con la columna de fecha ya se entiende a que
período corresponde cada cifra no?

**Comment by mkreyness** [comment]
ok pero ponele que un tipo que tiene ahora sumados puntos de marzo no entra hasta abril, y en abril todavia no se sumo nada, igual la primera vez que entre en abril le tengo que mostrar lo que sumo en marzo ? 
Extendiendo el concepto, suponete que un tipo no entro durante todo el año, y entra en enero de 2017, que hago, le muestro 10 popups ?
Nada me asegura que por cada vez que le acredite puntos ventas el tipo va a entrar al sistema a mirarlo.

**Comment by LeandroBraier** [comment]
Si. Acumulemos cuanto se fue sumando cada nes. Que vea los puntos por
ventas de marzo.

**Comment by mkreyness** [comment]
O sea, el texto tendria que ser medio ambiguo porque en algunos casos lo sumó hoy, y en otros casos es acumulado de varios meses (o meses sin ventas en el medio).
Le digo algo tipo "Desde tu ultima visita sumaste XXX puntos por ventas" ? Y ahi le marco todas como vistas y no se lo vuelvo a mostrar hasta que acumule de nuevo, ok ?

**Comment by LeandroBraier** [comment]
Exactamente Marce!! Me parece perfecto.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-03-30 9:44 GMT-03:00 mkreyness notifications@github.com:

**Comment by LeandroBraier** [comment]
Marce, avisame cuando esté esto porfa.

**Comment by mkreyness** [comment]
esta noche lo hago. El problema es que esa frase HOY es mentira, ya que los puntos se los agregue ayer.

**Comment by LeandroBraier** [comment]
Claro. No te preocupes por eso. Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
listo, lo que si no logre que queden AMBOS carteles cuando a su vez es el primer ingreso del dia por ejemplo. El cierre de un cartel cierra ambos. Supongo que no es grave, que si sumo puntos por ventas no le diga "sumaste +5 por el dia", igual sumarlos los  suma.

**Comment by LeandroBraier** [comment]
No hay problema @mkreyness. Está bien así. Gracias!!
