### ISSUE TITLE
Bug Mobile Juego en VIE TUR

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#19]
@mkreyness 

Tema 1) 

Estoy recibiendo quejas del usuario AlbaDarin que se suma a nuestro Facebook o comparte contenidos en Facebook y no le suma puntos.

Tema 2) 

A la vez me meto en la lista de actividades de ese usuario y no me aparece registrada actividad de ese usuario en Facebook, a la vez que me aparece como que jugó 3 veces al juego de Reaccioná a tiempo y no sumó puntos. 

Dice que le avisó que sumaba 100 puntos y no los sumó. ¿Puede ser que quizá no llegó a superar los 20 niveles y nos mintió respecto del cartel?

**Comment by mkreyness** [comment]
Usa PC o algun tipo de tablet/celular ?

**Comment by LeandroBraier** [comment]
No lo sé la verdad. Pero laultima vez que probamos en mobile funcionaba lo
de facebook.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
ya se, pero capaz es justo el caso. Se podra averiguar desde que plataforma se conecta ?
Porque JUSTO lo de facebook y lo del juego por construct todos usan cosas de HTML5 y capaz tiene un browser medio viejo

**Comment by LeandroBraier** [comment]
Puede ser, OK. COnsulto por las dudas.

**Comment by LeandroBraier** [comment]
Confirmado, usó Mobile, pero el cliente me dijo que no le demos más bola, que no tiene idea de tecnología la persona. Cierro. abrazo
