### ISSUE TITLE
Dominio Vie Tur. 28/12

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#2]
@mkreyness yo sé que Vie Tur está parado por ahora, pero necesito avanzar con este punto solo.

El dominio vietur.com.ar lo tiene registrado Alberto (el papá de Eze) a su nombre, por lo cual solo tengo que enviarle un mail para pedirle que nos deje crear el dominio comunidad.vietur.com.ar

Porfa decime qué le tengo que pedir así ganamos tiempo, confirmamos esa URL y podemos ir diseñando los videos y contenidos que incluyen esa URL.

abrazo

**Comment by mkreyness** [comment]
Yo estuve justamente ayer aprovechando para avanzar con cosas de Vietur, y me anda todo bastante mal en el server por NO tener un dominio, asi que JUSTO te iba a proponer avanzar con esto.
Lo que tienen que hacer los que administran el DNS donde esté vietur.com.ar es agregar un "A RECORD" que diga que comunidad.vietur.com.ar esta hosteado en el IP que nos dio Duplika (209.133.209.166). Una vez que apunte ahi haremos los ajustes via CPanel para que apunte a lo que ahora es http://209.133.209.166/~vieturco

**Comment by LeandroBraier** [comment]
Gracias @mkreyness ! Consulta: Quien maneja los dominios es Alberto directamente y no sé si va a saber como aplicar esto. Querés que le pida el acceso y lo hacemos nosotros directamente?

La otra alternativa sería armarle un paso a paso en Nic.Ar de como hacer esto que me pedís.

**Comment by mkreyness** [comment]
Es que nic.ar no tiene arte ni parte en esto. 
Es el proveedor de HOSTING que Alberto tenga.
Lo que tiene que hacer es pedirle a ese proveedor lo que te dije, agregar en su DNS un "A RECORD" que diga que "comunidad.vietur.com.ar" esta en el IP "209.133.209.166".
Como se hace eso en su proveedor de hosting ni idea, cada uno tiene la interface que quiere, lo mas facil es pedirle a alguien de la empresa de hosting que lo haga.

**Comment by LeandroBraier** [comment]
Perfecto, entendido!! Le pido eso entonces. Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2015-12-27 13:25 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
avisame en cuanto supuestamente este asi pruebo, y puedo probar mejor las cosas que fui bajando en el server, porque tenia que toquetear tantas cosas (al pedo) para que funcionara con el esquema de IP/~vieturco que revertirlo iba a ser mas trabajo.

**Comment by LeandroBraier** [comment]
Dale. Calculo que van a demorar igual.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2015-12-27 13:56 GMT-03:00 mkreyness notifications@github.com:

**Comment by LeandroBraier** [comment]
Hecho @mkreyness !! Me dicen de Vie Tur que está hecho.

Confirmame porfa.

abrazo

**Comment by mkreyness** [comment]
Si, perfecto. Ahora falta hacer un par de cosas en Duplika para apuntarlo bien, pero de eso me ocupo yo.

**Comment by mkreyness** [comment]
ya tengo bastantes cosas funcionando y estuve adaptando un poco los templates de Braulio.
Le voy a pedir un par de cosas via el otro thread.

**Comment by LeandroBraier** [comment]
Buenisimo MK! Cierro este entonces, así seguimos directamente por el otro.

abrazo
