### ISSUE TITLE
Usuarios desaparecidos

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#21]
@mkreyness tenemos un problema en VIE TUR.

El usuario MK tuyo y un usuario más al menos desaparecieron mágicamente. El otro usuario era:

DNI: 23987987
password VIETUR 

El cliente dice que no eliminó ningún usuario. Que solo eliminó 1 hasta ahora que era de un vendedor real que se lo pidió.

Cuando puedas fijate qué puede estar pasando.

**Comment by mkreyness** [comment]
No esta pasando nada. El usuario con ese DNI esta suspendido, no desaparecio de ninguna manera y MUCHO MENOS magicamente.
Alguien tuvo que haberlo suspendido, nada pasa solo.
Saquemosle el permiso de modificar vendedores.
Vas a ver como apenas no tengan permiso de hacerlo, la magia va a esfumarse como por arte de sí.

**Comment by LeandroBraier** [comment]
Dale, saquemoselo por las dudas. Gracias MK!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-03-23 16:07 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
hecho

**Comment by LeandroBraier** [comment]
Le vamos a tener que dar acceso de nuevo porque ella carga usuarios directamente en el CMS.

Me preguntó por qué de pronto no podía cargar y le dije que mientras averiguabamos qué pasó con ls usuarios desaparecidos tuvimos que desactivar un par de permisos.

El lunes dale acceso de nuevo y olvidemonos del tema mejor.

abrazo y gracias!

**Comment by mkreyness** [comment]
Seria mucho mas prudente que los ingresara via la registracion, que para eso esta.
Asi se asegura que le lleguen los mails de bienvenida, por ejemplo.
