### ISSUE TITLE
Bug en Posteo a compartir VIE TUR

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#22]
@mkreyness una vez más falló en detectar que el tema es para compartir. El botón de compartir no funciona, funciona solo como link:

http://comunidad.vietur.com.ar/cgi-bin/jugar.pl?id=18&usuario=LBraya02&clave=vietur

Porfa corregimelo lo antes posible.

abrazo

**Comment by mkreyness** [comment]
Le di mil vueltas.
A mi me anda (siempre este mismo link, eh) A VECES BIEN y A VECES NO.
Lo unico que noto cuando anda mal es que le da un error (variable) de que no puede ejecutar algo, pero evidentemente ese algo no esta dentro de nuestras cosas, es algo de la carga de los modulos de facebook, sobre lo cual no tengo control.

La clave es esperar a que la pagina TERMINE DE CARGAR y recien ahi hacer click en el boton.
Vas a ver que asi te anda.
Ya se que eso no es en si misma una solucion, pero me gustaria saber si a vos tambien te anda haciendo asi.
Si es asi, vemos con @FAAREIA como hacer para que el boton se oculte hasta que este totalmente terminado de cargar, te parece ?

**Comment by LeandroBraier** [comment]
Dale, hagamos eso ahora para poder ya publicarlo porfa.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-03-29 17:05 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
listo, probalo, a mi me anda perfecto.

**Comment by LeandroBraier** [comment]
Gracias @mkreyness !!! Quedó perfecto. Abrazo
