### ISSUE TITLE
Ranking Anual en la Home. 08/04

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#23]
@FAAREIA además del top 5 mensual que aparece en la Home, necesito que subamos el Ranking Anual, es decir, el Top 5 del acumulado de puntos total que tienen los usuarios.

Esto es porque a fin de año el que más puntos hizo gana un premio especial.

Puede ser para mañana o pasado todo bien. abrazo

**Comment by FAAREIA** [comment]
@mkreyness fijate el template `aside-usuarioT.html`. Ahi agregué el bloque de ranking anual y tiene un `style="display: none;"` asi queda oculto por ahora.

Lea te adjunto la foto, si esta OK marce ya podría avanzar.
![sin-titulo-3](https://cloud.githubusercontent.com/assets/6184969/14354826/2a054452-fcb5-11e5-84e0-2c7c4b858565.png)

**Comment by LeandroBraier** [comment]
Está perfecto Fede!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
En un rato lo programo y libero.

**Comment by mkreyness** [comment]
ya quedo implementado

**Comment by LeandroBraier** [comment]
Muchas gracias!!!
