### ISSUE TITLE
Agregar Campo de Fecha de Nacimiento a Mi Perfil y Formulario de Registro VIE TUR. 08/04

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#24]

**Comment by LeandroBraier** [comment]
Necesitaríamos eso para el vienres @mkreyness Llegamos?

**Comment by mkreyness** [comment]
es mas un tema de maquetacion que mio, una vez que esten maquetados ambos, agregar el campo me lleva un rato nomas.

**Comment by LeandroBraier** [comment]
Ok @FAAREIA cuando puedas agregalo. Puede ser para el viernes. abrazo

**Comment by FAAREIA** [comment]
Ya lo puse en los 2 lugares.
http://comunidad.vietur.com.ar/registro2.html
El template lo toqué y lo nombre -> perfil2T.html
Cuando este subido avisenme que perfil 2 no pude verlo, pero debería de funcionar bien

**Comment by FAAREIA** [comment]
Pasenme un usuario y clave asi cuando este implementado lo veo

**Comment by LeandroBraier** [comment]
Muchas gracias! 

Te paso mi usuario Fede:

usuario=LBraya02

&clave=vietur

**Comment by LeandroBraier** [comment]
@FAAREIA avisame cuando tengan esto porfa.

abrazo

**Comment by FAAREIA** [comment]
Ahi lo agregué oculto y sin el `required` al perfil. Lo quería ver pero con tu usuario me da login incorrecto. Estan bien los datos?

**Comment by mkreyness** [comment]
se le habia cambiado la password por error (el autocomplete del browser se la piso).
Proba de nuevo que ahora ya esta repuesta esa.

**Comment by FAAREIA** [comment]
Ya lo vi y se ve bien.
Osea, ya esta para implementar lo del registro y lo del perfil.
Acordate de agregarle el `required` al del perfil y sacarle el `display: none;` @mkreyness

**Comment by mkreyness** [comment]
Ok, ahora me estoy yendo, a la tarde lo pongo a andar.

**Comment by LeandroBraier** [comment]
Ok chicos. Gracias! A la tarde dejemoslo resuelto y estamos bien.

abrazo

**Comment by mkreyness** [comment]
Todo listo y funcionando, PERO: al menos a mi en Chrome cuando hago click en el desplegable de años (en el datepicker de la fecha de nacimiento del perfil) como se superpone de alguna manera con el boton de upload de foto, me abre para subir una foto. Habria que hacer algo para aislar una cosa de la otra.

**Comment by LeandroBraier** [comment]
Gracias MK! A mi me pasa lo mismo. Corrijamoslo @FAAREIA  porfa.

**Comment by FAAREIA** [comment]
Solucionado

**Comment by LeandroBraier** [comment]
Muchas gracias Fede! abrazo
