### ISSUE TITLE
Consulta Puntos Juegos VIE TUR

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#25]
Buen día @mkreyness ! 

Consulta: existe la posibilidad de permitir que los usuarios de Comunidad VIE TUR sumen puntos todas las veces que juegan al mismo juego? 

Hablo del juego de la pelotita o el que estamos por subir de las banderas, no las trivias y demás dinámicas.

**Comment by mkreyness** [comment]
Si, hay que anular un par de controles nada mas.

**Comment by LeandroBraier** [comment]
Genial. Hagamoslo porfa en VIE TUR nomas. No en parex. Puede ser a la tarde
tranqui no hay apuro.

Abrazo y gracias!

**Comment by mkreyness** [comment]
es simple porque cada juego (siempre hablando de los de HTML5) te dejaba jugar hasta que sumes el total de puntos declarados para el juego (suponiendo que podes sumar cantidades menores por resultados parciales).
Le saque esa limitacion. Probalo por las dudas.

**Comment by LeandroBraier** [comment]
Gracias MK!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-04-11 10:30 GMT-03:00 mkreyness notifications@github.com:
