### ISSUE TITLE
Usuario que sí pueda borrar cosas en VIE TUR

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#26]
@mkreyness necesito que me pases un nuevo usuario que sí pueda limpiar cosas

Más allá de eso, necesito saber si ese usuario puede borrar imágenes sin descripción. No podrías hacer que todas las columnas de los items sean clickeables para acceder al item?

Por ejemplo, la opciones de la primer pregunta de este quiz:

http://comunidad.vietur.com.ar/cgi-bin/trivia.pl?id=55

&usuario=LBraya02

&clave=vietur

DEADLINE: Tranqui con tiempo.

abrazo

**Comment by mkreyness** [comment]
Es que por la forma que lo hicimos, ya no depende del usuario, lo de que no se puedan borrar cosas en esas pantallas ya esta fijo (los programas NO tienen boton de borrar). Tendria que hacer un cambio grande en el CMS para que la aparicion o no de los botones dependa del nivel del usuario.
Todos los items clickeables creo que me inhabilitaria otras funciones que hay. Lo ideal seria que no se permita ingresar items sin nada en la primer columna nunca, o que aparezca un icono de editar o algo asi. Lo que voy a hacer mal y rapido es que si la columna clickeable esta vacia ponga aunque sea "---" asi hay donde clickear.

**Comment by LeandroBraier** [comment]
Dale me parece perfecto. Y de ultima agrega ststus de publicado o
suspendido a los demas items también.  Ya que no se puede eliminar al menos
despublicar.

Graccias!

**Comment by mkreyness** [comment]
ya esta lo de "---", podes entrar a todo (al menos en VIE TUR). Despues lo extiendo a Parex.
Ponerle estado a cada pequeña cosa tambien es muy engorroso. Dejame ver si puedo hacer algo que a partir de cierto nivel aparezca siempre el boton borrar aunque no este habilitado en esa pantalla.

**Comment by mkreyness** [comment]
listo, entra con el usuario admin2, clave turvie, le puse nivel 1000 (el admin tiene nivel 999) y puse que a todo usuario con nivel de 1000 en adelante le aparezca siempre el boton eliminar.

**Comment by LeandroBraier** [comment]
Muchas gracias Mk! Abrazo grande

**Comment by LeandroBraier** [comment]
Sos un genio MK. Lo resolviste al toque. Gracias otra vez!

**Comment by mkreyness** [comment]
Es la argentinidad al palo, ni alambres uso, lo ato con cinta scotch y sale andando.
