### ISSUE TITLE
URGENTE- BUG en imagen de exito en TRivia Trapsatur

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#27]
@FAAREIA aparece rota la imagen esta mirá

<img width="699" alt="captura de pantalla 2016-04-13 a las 9 12 07 a m" src="https://cloud.githubusercontent.com/assets/6719872/14492320/e3267f48-0154-11e6-8c40-452bfe417b47.png">

El link es:

http://comunidad.vietur.com.ar/cgi-bin/trivia.pl?id=55

&usuario=LBraya02

&clave=vietur

Porfa resolvelo lo antes posible.

abrazo

**Comment by FAAREIA** [comment]
No hay imagen parece.
El link de la imagen es: `/vendedores/img/temas/opciones/` lo cual no apunta a ningun archivo, sino que es una ruta. ¿Esta bien cargada la imagen?

**Comment by LeandroBraier** [comment]
Es que la imagen es una de uds me parece. La que le dice al usuario que
hizo las cosas Ok no? Yo no tengo como subir esa imagen.

**Comment by LeandroBraier** [comment]
Aaaaahh ya me acordé es el resultado esa imagen. Perdon. Yo lo resuelvo.
Mala mia. Abrazo
El abr. 13, 2016 1:24 PM, leandrobraier@gmail.com escribió:

Es que la imagen es una de uds me parece. La que le dice al usuario que
hizo las cosas Ok no? Yo no tengo como subir esa imagen.
El abr. 13, 2016 12:12 PM, "Federico Arena" notifications@github.com
escribió:

No hay imagen parece.
El link de la imagen es: /vendedores/img/temas/opciones/ lo cual no apunta
a ningun archivo, sino que es una ruta. ¿Esta bien cargada la imagen?

**Comment by FAAREIA** [comment]
@mkreyness

**Comment by LeandroBraier** [comment]
Olvidatw Fede! Te mandé otro mensajw pero no llegó.  Es una imagen mia
tenes razón.  La tengo que subir yo.

Abrazo
