### ISSUE TITLE
Sumar Numero de Legajo como Campo al Usuario Vendedor en CMS

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#28]
@mkreyness necesito que cuando puedas sumes el Numero de Legajo como un Campo mas al Usuario Vendedor en el CMS de VIE TUR.

abrazo

**Comment by mkreyness** [comment]
listo, por lo que veo el legajo no es del vendedor sino de la agencia en que trabaja, porque muchos se repiten. Lo agrego tambien a la "Exportacion de Datos de Vendedores" o no hace falta ahi ?

**Comment by LeandroBraier** [comment]
Gracias MK!

Dale, porfa!

**Comment by mkreyness** [comment]
listo

**Comment by LeandroBraier** [comment]
Genio! Gracias!
