### ISSUE TITLE
Favicon Comunidad VIE TUR (sin apuro) 26/04

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#29]
@FAAREIA cuando puedas fijate si podés hacer uno a modo de una especie de forma resumida del logo de la Comunidad.

Puede ser para la semana que viene. abrazo

**Comment by FAAREIA** [comment]
http://comunidad.vietur.com.ar/cgi-bin/mainvendedores.pl
Dale F5 y decime que te parece.
Abrazo

**Comment by LeandroBraier** [comment]
Quedó buenisimo Fede!! Apliquemos en producción nomás.

abrazo

**Comment by FAAREIA** [comment]
Hola Lea, ya esta aplicado al sitio original

**Comment by LeandroBraier** [comment]
Muchas gracias @FAAREIA ! En Firefox lo veo joya pero en Chrome no. Vos en Chrome lo ves? Fijate, dale F5 y confirmame. Porque yo meta darle F% Ctrl+R y no aparece.

**Comment by FAAREIA** [comment]
Es el caché, lo vaciaste?

**Comment by LeandroBraier** [comment]
Si. Lo vacie también pero si vos lo ves en chrome me quedo tranquilo.

**Comment by FAAREIA** [comment]
Esas cosas no fallan excepto por el caché, pero lo revisé y si lo veo.

**Comment by LeandroBraier** [comment]
Perfecto entonces. Gracias Fede!!
