### ISSUE TITLE
Detalle Comunidad VIE TUR

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#30]
@FAAREIA podrás cambiar el orden de TOP 5 y Ranking Anual en la Columna derecha?

Necesito que TOP 5 quede arriba de Ranking Anual, quedando el orden de la columna así:

TU PERFIL
TUS LOGROS
TOP 5
RANKING ANUAL
Actividad reciente
Comparti y gana (facebook)

Cuando hayas aplicado el cambio avisame porfa.

abrazo

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias @FAAREIA !! abrazo

**Comment by LeandroBraier** [comment]
@FAAREIA el cliente me pide agregar la palabra "Mensual" al TOP 5. Es decir, se llamaría TOP 5 Mensual.

Me confirmás cuando lo puedas hacer? No es urgente.

abrazo

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Mil gracias Fede!! abrazo
