### ISSUE TITLE
Puntos VIE TUR de Abril

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#31]
@mkreyness te paso los puntos de abril actualizados a fecha de hoy 26/04. Confirmame cuando esté arriba.

[Puntos VIE TUR Abril.xlsx](https://github.com/LeandroBraier/Vietur/files/237486/Puntos.VIE.TUR.Abril.xlsx)

abrazo

**Comment by mkreyness** [comment]
subidos con fecha de hoy y acreditados.
Cuando cada uno entre se le avisara la cantidad de puntos nuevos (no salen en la lista de "fulanito gano xx puntos").

**Comment by LeandroBraier** [comment]
Mil gracias Mk! Abrazo grande
