### ISSUE TITLE
Agregado de Descripción automático en CMS VIE TUR

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#32]
@mkreyness cuando puedas ponés que se agregue solo el **--** a la descripción de los elementos en el CMS de VIE TUR? Es lo mismo que ya hiciste en el de Parex. Fijate que tengo uno con descripción vacía que creó el cliente, hay forma de editarlo o borrarlo al menos?

<img width="1472" alt="captura de pantalla 2016-04-27 a las 5 37 48 p m" src="https://cloud.githubusercontent.com/assets/6719872/14866802/d2daeef6-0c9b-11e6-885d-ec9c9836658e.png">

abrazo

**Comment by mkreyness** [comment]
Pero si es al reves, lo hice en el de VIE TUR, nunca lo toque en le de Parex. Capaz no funciona en todos los casos. Ahora reviso.

**Comment by LeandroBraier** [comment]
Estoy en Juegos. Gracias!

Igual por las dudas en Parex aplicalo también. Estamos sumando neófitos ; )

abrazo

**Comment by mkreyness** [comment]
listo VIE TUR, habia dos tipos de links, el que reemplaza en la misma pantalla y el que abre un pop de la ventana. El toque habia sido solo en los que abrian pop.
Ahora paso ambas cosas a PAREX.

**Comment by LeandroBraier** [comment]
Gracias @mkreyness !
