### ISSUE TITLE
Detallecito Bases y Condiciones VIE TUR. 06/05

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#33]
Sin apuro, @FAAREIA Cuando puedas, es un ajustecito del texto de bases y condiciones.

en **4.LOS PARTICIPANTES**

en el 2do renglon donde dice MINTUR sigue con “on legajo...” falta la c  

el parentesis quedó una parte en un renglon y otra en el de abajo. Agregale un espacio antes de "el/los" y se resuelve.

Te paso como debería quedar:
1. Los participantes
   Podrán participar en la PROMOCIÓN exclusivamente las personas físicas mayores de edad que se desempeñen en Agencias de Viajes habilitadas por el MINTUR **con** Legajo vigente y sigan la mecánica descripta en el apartado MECÁNICA DE PARTICIPACIÓN de estas BASES (en **adelante, el /los** “ PARTICIPANTE/S”). 
   Esta participación es “ Sin obligación de compra”.
   El personal de VIE TUR, sus representados, proveedores, representantes y demás personas vinculadas a VIE TUR, como asi también cualquier persona que no trabaje en una Agencia de Viajes, podrán capacitarse y competir pero no podrán acceder a la premiación en ninguna de sus formas la que solo queda reservada para el personal de las agencias de viajes.

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias Fede! Estoy tratando de verlo pero lo veo igual, sin la C y con el texto pegado. Me avisás cuando esté?

Le di F5 y borré el caché en 2 navegadores.

http://comunidad.vietur.com.ar/cgi-bin/bases-condiciones.pl?

usuario=LBraya02

&clave=vietur

abrazo

**Comment by FAAREIA** [comment]
@mkreyness nos confirmas si los templates se estan regenerando?
Toqué el de bases y condiciones ubicado en `/templates/vendedores/` y nada. Acordate esto es vietur, no confundir

**Comment by mkreyness** [comment]
no hay nada que regenerar, ese concepto es solo para las paginas de novedades y productos.
Aca estas ejecutando directamente el programa, que lee el template y te lo muestra.
El problema es que el que tocaste se llama bases-y-condicionesT.html ,y el que el programa lee se llama bases-condicionesT.html, igual que lo que va en el URL.

**Comment by mkreyness** [comment]
No se si te encontraste con ambos y modificaste uno incorrecto, o lo trajiste directo de otro lado con ese nombre. Si es esto ultimo, es solo cuestion de renombrarlo.

**Comment by FAAREIA** [comment]
ahora si, gracias marce

**Comment by LeandroBraier** [comment]
Ahora si joya!!! Gracias a los dos!

abrazo
