### ISSUE TITLE
Ajustecitos en Registración Comunidad VIE TUR. 17-05

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#34]
Buen día @mkreyness ! Sin apuro, cuando puedas, necesito que en el registro de usuarios ciudad y provincia sean datos obligatorios.

A la vez me pidieron si podemos agregar un desplegable para Ciudades. Si te paso una lista de ciudades por provincia, podemos hacer eso? O conviene que te de la lista y usarla para un autocompletar?

abrazo

**Comment by mkreyness** [comment]
Pasame la lista y la usaria para autocompletar, me parece que para el usuario es mas practico.
Pero decime un plazo maximo para cuando tendria que estar, porque la carga de trabajo en este momento es altisima.

**Comment by LeandroBraier** [comment]
Si, lo sé. Por eso te consulto nada más. Es sin apuro, para la semana que viene tranqui en el momento que puedas. 

Te paso la lista que tengo.

[Listado de Ciudades de mas de 45.000 habitantes.xlsx](https://github.com/LeandroBraier/Vietur/files/263409/Listado.de.Ciudades.de.mas.de.45.000.habitantes.xlsx)

abrazo

**Comment by LeandroBraier** [comment]
@mkreyness cuando exporto los datos de vendedores no me exporta columna de Género, pero en el Formulario de Registración si está. Te fijás qué puede ser?

**Comment by mkreyness** [comment]
no lo habre agregado en esa consulta. Ahora te lo agrego.

**Comment by mkreyness** [comment]
ahi lo agregue en la "consulta de actividad y datos de vendedores". Lo necesitas en el de exportacion para mailings tambien ?

**Comment by LeandroBraier** [comment]
Por las dudas si porfa.

Abrazo

**Comment by LeandroBraier** [comment]
Y en la lista general de vendedores también.  Tiene fecha de nac pero no
sexo.

**Comment by mkreyness** [comment]
listo todo

**Comment by LeandroBraier** [comment]
Gracias @mkreyness ! Copio a @FAAREIA para que la semana que viene sume los campos de Provincia y Localidad al Formulario de Registración como obligatorios.

abrazo

**Comment by LeandroBraier** [comment]
@FAAREIA hoy podés resolver esto porfa antes de la call?

**Comment by FAAREIA** [comment]
Hecho
@mkreyness 
http://comunidad.vietur.com.ar/registro2.html

**Comment by LeandroBraier** [comment]
Avisame MK cuando este listo este.

**Comment by mkreyness** [comment]
Esta puesto en produccion, pero faltaria lo del autocompletado de ciudades

**Comment by LeandroBraier** [comment]
Ok, avisenme cuando esté final porfa.

**Comment by mkreyness** [comment]
ya agregue el autocomplete de ciudades en la registracion con el listado que me pasaste.
Si queres agrego al CMS un lugar para agregar mas ciudades.
Puse que busque solo desde el principio del nombre, pero en algunos casos eso es choto: por ejemplo si en Cordoba pones Rio... no trae nada, porque Rio Cuarto figura como "Ciudad de Rio Cuarto".

**Comment by LeandroBraier** [comment]
Mm ok. Dejamelos en el CMs entonces y yo los edito. Gracias MK!

**Comment by mkreyness** [comment]
listo, esta en Configuracion->Ciudades

**Comment by LeandroBraier** [comment]
Listo @mkreyness ! Ya lo subí y funciona, pero faltan ciudades puede ser? Las que te pasé están todas?

**Comment by LeandroBraier** [comment]
Olvidate, son ciudades con menos de 45.000 habitantes las que faltan. Ya queda cerrado esto. Gracias!!
