### ISSUE TITLE
Ajustecito en "Mis Datos" de VIE TUR. Sin apuro

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#35]
El recuadro que dice 60 puntos debería decir 120 puntos porque ahora cambiamos eso en el CMS.

<img width="709" alt="captura de pantalla 2016-05-13 a las 11 47 20 a m" src="https://cloud.githubusercontent.com/assets/6719872/15250943/8cccab5c-18fd-11e6-9617-61ad98f58c76.png">

Cuando puedas, sin apuro.

abrazo

**Comment by mkreyness** [comment]
En realidad habria que hacer eso variable y que lo lea realmente del CMS.

**Comment by LeandroBraier** [comment]
Exacto. Como en Parex. Sin apuro, insisto.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
@mkreyness  hoy podés resolver esto porfa antes de la call?

**Comment by mkreyness** [comment]
variable estaba, pero estaba apuntando a un ID de juego mal (el de klaukol).
La intencion era que los mismos numeros bajos se respetaran pero como se cargaron algunos juegos reales antes que estos virtuales, se me corrio todo. Fijate ahora.

**Comment by LeandroBraier** [comment]
Perfecto. Gracias!
