### ISSUE TITLE
Pequeño Bug de Maquetación VIE TUR

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#36]
@FAAREIA cuandotengas un ratito fijate porfa por qué se descuajeringa la columna derecha cuando da los resultados de una trivia.

<img width="405" alt="captura de pantalla 2016-05-16 a las 6 52 27 p m" src="https://cloud.githubusercontent.com/assets/6719872/15304533/457c108c-1b94-11e6-8a8d-696517582a15.png">

**Comment by LeandroBraier** [comment]
El link es: http://comunidad.vietur.com.ar/cgi-bin/finquiz.pl

**Comment by mkreyness** [comment]
Asi suelto sin user/pass y sin haber jugado antes no lo puede ver.
El template del fin de trivia es este, @FAAREIA :
www/templates/vendedores/quiz-completaT.html
pero el contenido ese que muestra la foto proviene del aside-usuarioT.html, como todo el resto.

**Comment by FAAREIA** [comment]
Necesito usuario y clave

**Comment by LeandroBraier** [comment]
usuario=LBraya02
clave=vietur

**Comment by LeandroBraier** [comment]
@FAAREIA hoy podés resolver esto porfa antes de la call?

**Comment by FAAREIA** [comment]
Job Done, cuando termines la trivia dale F5 si lo seguis viendo mal

Abrazo

**Comment by LeandroBraier** [comment]
Ahi lo estoy viendo bien en ese template, pero probé en otras trivias que
tienen otro template, llamado fintrivia.pl

Ese tempalte sigue teniendo el bug. LO podrás ajustar también porfa?

http://comunidad.vietur.com.ar/cgi-bin/fintrivia.pl

**Comment by mkreyness** [comment]
son dos templates completamente distintos que forman parte de TODAS las trivias: uno es de las preguntas (triviaT.html) , y otro es del resultado final (trivia-completaT.html)

**Comment by LeandroBraier** [comment]
el que yo digo es fintrivia.pl

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
ese es el programa, pero lo que tiene que revisar @FAAREIA es trivia-completaT.html que es el template leido por el programa fintrivia.pl.

**Comment by LeandroBraier** [comment]
ah entiendo. Gracias!

Espero eso.

**Comment by LeandroBraier** [comment]
Ahi lo probé y está solucionado. Gracias!
