### ISSUE TITLE
Nuevo tipo de Juego: imagen incógnita

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#37]
@mkreyness el cliente pide hacer una nueva versión de las trivias que sea:

. cuestionario (es decir, hay 1 respuesta correcta)

. pero que las preguntas o las respuestas puedan ser tanto imagen como texto.

Lo que necesito que me digas es, una vez entregado Revear, para cuando podríamos sumar este tipo de trivia. Por ejemplo, martes 24/05 lo ves posible? O viernes 27/05?

Espero tu respuesta.

abrazo

**Comment by mkreyness** [comment]
O sea una mezcla de la trivia original con el quiz posterior. Sera un par de dias de trabajo.
Tenes que incluir tiempo de Fede porque hay que maquetar eso.
El problema es que hay un cronograma de SiguitDS que no tiene contemplado mas que lo de Revear. Se termina haciendo de goma eso (y encima necesito cosas de Fede que ni me dio bola todavia).

**Comment by LeandroBraier** [comment]
Entiendo. Bueno si. Esto iría antes de siguit. Entonces la fecha seria:
terminado siguit 2 dias mas no? Fines de la semana que viene.

**Comment by mkreyness** [comment]
Queras decir "terminado Revear", porque Siguit no va  a terminar antes de mediados de junio con suerte.

**Comment by LeandroBraier** [comment]
Tal cual. Terminado revesr 2 dias mas no?

**Comment by mkreyness** [comment]
si pero seguro que hay rebotes de revear.

**Comment by LeandroBraier** [comment]
Por eso digo. Terminado Revear. Igual a los rebotes les damos más tiempo.
Lo importante es lanzar correctos. Después si quieren agregados se hacen
después del lanzamiento con más tiempo. Vos entraste al final pero esto
tuvo mil idas y vueltas de diseño y contenido antes. Hicimos todo en MockUp.

**Comment by LeandroBraier** [comment]
@mkreyness hoy podés ver esto porfa asi lo hablamos en la call?

**Comment by LeandroBraier** [comment]
Esto lo vemos la semana que viene, después de Potenciados.

**Comment by LeandroBraier** [comment]
@mkreyness y @FAAREIA esto habría que armarlo. Primero lo maquetás vos Fede? me confirmás cuantas horas te llevaría?

**Comment by mkreyness** [comment]
si las imagenes son como las del quiz yo creo que se podria reutilizar esa maqueta. El tema es como se mostrarian los resultados, porque la de resultados de quiz es otra cosa. Aca seria mostrar la imagen correcta sola ?

**Comment by LeandroBraier** [comment]
En este caso la imagen está en la pregunta. Por ejemplo: ¿ a qué país corresponde esta foto?

Tanto las opciones para responder como los resultados son en texto sin imagen, es decir, son iguales al cuestionario, no al quiz.

**Comment by mkreyness** [comment]
Entonces seria agregar una imagen a la maqueta habitual de las trivias. Eso hay que maquetarlo, si.
@FAAREIA la maqueta de trivia es templates/vendedores/triviaT.html (no la trivia-completaT.html, esa es la de resultados), yo diria que en base a triviaT.html generes una trivia-con-imagenT.html

**Comment by FAAREIA** [comment]
http://comunidad.vietur.com.ar/trivia-simple-img.html

**Comment by LeandroBraier** [comment]
Genial, avisenme cuando puedo cargar un ejemplo.

abrazo

**Comment by mkreyness** [comment]
ya esta (no en produccion, pero podes cargarlos en el CMS).
Aca tenes un ejemplo
http://comunidad.vietur.com.ar/cgi-bin/triviaimagen.pl?usuario=LBraya02&clave=vietur&id=78

**Comment by LeandroBraier** [comment]
Mil gracias MK!! Muy bueno el chiste además. Lo mando al cliente para ver si está OK les decimos que podemos incorporar este tipo de dinámicas.

abrazo

**Comment by LeandroBraier** [comment]
@mkreyness estamos haciendo pruebas con el cliente y aún no funciona puede ser?

Este es el del cliente:

http://comunidad.vietur.com.ar/cgi-bin/trivia.pl?id=80&usuario=PComu04&clave=vietur

Como le cargo una imagen innecesaria creé otra versión pero sigue sin funcionar:

http://comunidad.vietur.com.ar/cgi-bin/trivia.pl?id=81&usuario=PComu04&clave=vietur

Nos falta hacer algo o hay algún bug?

**Comment by mkreyness** [comment]
Fue la primer imagen que tuve "a mano" y hubo que improvisar.

**Comment by LeandroBraier** [comment]
Pero entonces ajustás?

**Comment by mkreyness** [comment]
No esta pasado a produccion, tenes que usar triviaimagen.pl, no trivia.pl

**Comment by mkreyness** [comment]
si esta todo ok, entonces hago el reemplazo

**Comment by LeandroBraier** [comment]
Ah, si. Si te referís a esta:

http://comunidad.vietur.com.ar/trivia-simple-img.html

Está ok. Adelante.

**Comment by mkreyness** [comment]
no no, eso es el mockup
Mira el URL que YO te pase y los que VOS me estas pasando y vas a ver a que me refiero.
Donde estas poniendo trivia.pl tenes que poner triviaimagen.pl

**Comment by LeandroBraier** [comment]
El ID 80 lo veo bien. El ID 81 no. No sé por qué.

**Comment by mkreyness** [comment]
El juego 81 no existe. No se de donde obtuviste ese ID. Es el 83.

**Comment by mkreyness** [comment]
http://comunidad.vietur.com.ar/cgi-bin/triviaimagen.pl?id=83&usuario=PComu04&clave=vietur

**Comment by LeandroBraier** [comment]
Tenés razón. Está OK. Pasalo a producción nomás y avisame.

Gracias!

**Comment by mkreyness** [comment]
A las 4 llego y lo paso

**Comment by LeandroBraier** [comment]
Gracias!

**Comment by mkreyness** [comment]
Listo

**Comment by LeandroBraier** [comment]
Muchas gracias MK!!!
