### ISSUE TITLE
Límite a la cantidad de puntos que puede sumar un juego

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#38]
@mkreyness es mucho lio limitar los juegos de VIE TUR a que sumen como máximo una determinada cantidad de puntos?

Por ejemplo, el de las banderas quieren limitarlo a 500 puntos.

**Comment by mkreyness** [comment]
puedo hacerlo hardcoded para hacer mas rapido, implementar algo configurable desde el CMS llevaria mas tiempo.

**Comment by LeandroBraier** [comment]
Genial! Entonces ponele 500 a las banderas y 1000 a Reacciona a tiempo.
Puede ser? Lo podes tener para mañana entonces?

**Comment by mkreyness** [comment]
Si

**Comment by LeandroBraier** [comment]
Gracias MK!

**Comment by mkreyness** [comment]
Ahi lo implemente para "banderas", fijate si te funciona bien.
Tene en cuenta que antes solo sumaba puntos si no lo habias jugado en el mismo dia. Ahora le saque esa restriccion, suma puntos hasta los 500, aunque sea el mismo o distintos dias. 
El problema es que el cartel que dice "Ganaste xx puntos"  esta fijo en otro lado, no sabe ni que juego es, y se fija en el valor del juego standard. Lo que puedo hacer es que si no le sumo los 100 puntos completos ya no le aparezca el cartelito.

**Comment by mkreyness** [comment]
Ah, son 50 en este juego, ok. 
Ojo para probar tenes que dessuspenderte porque si no nunca pasas de 100.
En definitiva, o le suma 50 o no le suma nada, con lo que podria no mandarle el cartel cuando no suma nada. Ahora ajusto eso.

**Comment by LeandroBraier** [comment]
Excelente MK! Gracias!

**Comment by mkreyness** [comment]
falta el "reacciona" todavia.

**Comment by mkreyness** [comment]
Che pero el reacciona tiene un limite de 100.
Por default ningun juego deja sumar mas de 100 (el caso de "banderas" es diferente)
Subo ese limite de 100 a 1000 en general ?

**Comment by LeandroBraier** [comment]
Pero las trivias solo suman 1 vez igual no?

**Comment by mkreyness** [comment]
Las trivias no pasan por este mecanismo, hablo del que se activa desde los juegso Construct.
Todo el resto de cosas (trivias/compartir/etc.) solo se pueden usar una vez, se les bloquea.

**Comment by LeandroBraier** [comment]
Ah, perfecto. Entonces no está el limite de más de 100 puesto para todos
los juegos de construct, porque antes de lo que hiciste recién, el juego de
Banderas venía sumando como loco.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
El de Banderas tenia (por algo que me pediste vos) otro tipo de limites: solo se podia jugar una vez por dia.

**Comment by mkreyness** [comment]
El Reacciona tiene algo muy raro: solo una persona lo ganó, y de alguna forma hizo montonazo de puntos, y todo el resto de gente 0. Es cierto que si jugas y no haces puntos se guarda (para que haya historia) el registro con 0 puntos, pero me llama mucho la atencion que solo una persona (Alba Darin) haya ganado, y tantas veces, siendo que teoricamente hay un limite.

**Comment by LeandroBraier** [comment]
No es tan raro lo de tanta gente con0, porque no es tan fácil el juego,
porque a veces se torna aburrido y requiere mucha concentración.

Si es raro lo de Alba Darín si estaba el freno.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-05-17 21:22 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
no, definitivamente nunca le sumo puntos a nadie, porque todo esto venia de un primer juego en que los puntos estaban dados por la cantidad de aciertos y en este caso no viene nada. Entonces estaba harcoded forzar 100 puntos si lograbas los 20 niveles, pero el numero de juego hardcoded era el de parex. Para mi que esta Alba se quejo y le cargaste puntos a mano o algo asi ? Porque el programa asi como estaba no le podia dar puntos a NADIE.
Ya lo arregle (a futuro).
Si queres a c/u que jugo y grabo le pongo sus 100 puntos y le agrego una ficha, porque  otro puntaje no podrian haber sacado. Supuestamente si no llegas a los 20 niveles, directamente no llama a mi programa de sumar.

**Comment by LeandroBraier** [comment]
Dale. Me parece bien. Hagamos asi.

Que cagada esto. Podremos revisar que no pase lo mismo en parex?

**Comment by mkreyness** [comment]
En parex no pasa, justamente el programa estaba copiado de Parex y tenia los ids internos de los juegos de parex.
El tema tambien es que al no haber funcionado el control de no pasarse de 100, puede haber gente que jugo muchisimas veces y le este poniendo puntos de mas. A esos no les doy mas de 10 veces, no ? (asi no se pasan de 1000).

**Comment by LeandroBraier** [comment]
Exacto.

**Comment by mkreyness** [comment]
igual eso lo voy a hacer a la tarde, ahora quiero tenerte lo antes posible lo de Tendencias de Revear.

**Comment by LeandroBraier** [comment]
Dale perfecto.  No hay apuro con esto.

**Comment by LeandroBraier** [comment]
@mkreyness  hoy podés resolver esto porfa antes de la call?

**Comment by mkreyness** [comment]
Esto era lo que habia quedado pendiente, ya estan dados los puntos y fichas correspondientes a los dias que el juego no sumaba.
A la unica que no le di fue a Alba Darin porque ya tenia mas de 2200 puntos sumados de antes y habiamos dicho que esto no pase de 1000.

**Comment by LeandroBraier** [comment]
Excelente. Gracias MK!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
@mkreyness apenas pueda me confirmás cuál limite de puntos le quedó al juego de Agentes Furiosos en VIE TUR?

Necesito que el límite sea 1500 puntos. Me avisás porfa?

**Comment by mkreyness** [comment]
Hay un unico limite general que es 1000, fijo.
Le pongo que sea 10x de cualquier juego que sea (como vos pensabas que era) y te aviso.

**Comment by LeandroBraier** [comment]
Dale, perfecto. Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Listo, lo probe con el tuyo (sacandole temporariamente la suspension) y anduvo bien.

**Comment by LeandroBraier** [comment]
Muchas gracias MK!!!! abrazo grande
