### ISSUE TITLE
Puntos VIE TUR de Mayo

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#39]
@mkreyness te paso los puntos de mayo actualizados a fecha de hoy 26/05. Confirmame cuando esté arriba.

[Puntos.VIE.TUR.Mayo.xlsx](https://github.com/LeandroBraier/Vietur/files/285014/Puntos.VIE.TUR.Mayo.xlsx)

abrazo

**Comment by mkreyness** [comment]
a  simple vista esta lleno de duplicados, con iguales y diferentes datos de puntaje.
Creo que tendrian que chequearlo un poco mejor antes de que lo suba.
Ejemplos: 
BVULCANO24, datos DISTINTOS, deberia sumarlos ? Probablemente si.
Pero por ej DCarnevale59 datos IGUALES, dificilmente deba sumarlos.

**Comment by LeandroBraier** [comment]
No entiendo MK. Estos datos se suman a lo que ya está y se canjean para
este mes, no se reemplazan eh.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-05-26 15:46 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Mira el excel que mandaste y te vas a dar cuenta de lo que digo.
DENTRO del excel mucha gente esta DOS VECES, en algunos casos con los mismos datos y en otros casos con DISTINTOS datos.
No puedo cargar dos registros para el mismo mes y mismo vendedor.
Tengo que elegir o SUMAR lo que estan DOS VECES, o descartar alguno. Si descarto, seguro que va a haber gente con menos puntaje que el que debe. Si los SUMO ENTRE SI, seguro va a haber gente con MAS puntaje del que deberia.

**Comment by LeandroBraier** [comment]
Perdon, no habia visto eso. No subas nada, consulto con el cliente. Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-05-26 15:50 GMT-03:00 mkreyness notifications@github.com:

**Comment by LeandroBraier** [comment]
Corregido @mkreyness !

[Puntos.VIE.TUR.Mayo.xlsx](https://github.com/LeandroBraier/Vietur/files/285207/Puntos.VIE.TUR.Mayo.xlsx)

**Comment by mkreyness** [comment]
todo cargado. Ojo esta pendiente todavia ajustar eso que detecte del juego que no habia sumado puntos.

**Comment by LeandroBraier** [comment]
Gracias MK! OK, eso cuando lo podés ver? O necesitabas más feedback de mi?

**Comment by mkreyness** [comment]
no, es algo que tengo que hacer yo, trato de liquidarlo esta noche.

**Comment by LeandroBraier** [comment]
Dale, genial. Gracias!

2016-05-26 17:29 GMT-03:00 mkreyness notifications@github.com:
