### ISSUE TITLE
Newsletter VIE TUR 28/01

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#4]
@braulio-evangelisti necesitaría para mañana un diseño de newsletter para VIE TUR. Simplemente en un PSD, nada de maquetación. En este PDF tenés los contenidos que irían y una sugerencia de diseño, aunque no hace falta que la sigas. SI ES IMPORTANTE que sigas las estéticas, logos y demás que tiene hoy la Comunidad VIE TUR.

[Newsletter VIE TUR Lanzamiento Enero 2016.pdf](https://github.com/LeandroBraier/Vietur/files/107037/Newsletter.VIE.TUR.Lanzamiento.Enero.2016.pdf)

Cualquier duda avisame. 

abrazo

**Comment by LeandroBraier** [comment]
@braulio-evangelisti pudiste ver esto? Lo necesitaría a más tardar para mañana.

**Comment by braulio-evangelisti** [comment]
Si lea estuve tratando de armar algo desde el Miercoles pero fue todo cortado con el resto de cosas prioritarias. Hoy durante el transucurso del dia te lo mando.

**Comment by LeandroBraier** [comment]
Buenisimo Brau! Entiendo. Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-01-29 10:28 GMT-03:00 Braulio Evangelisti notifications@github.com:

**Comment by braulio-evangelisti** [comment]
Lea que te parece algo asi?

Abrazo

![newsletter-bienvenida](https://cloud.githubusercontent.com/assets/11272253/12684464/e21b2bcc-c69d-11e5-9733-e4cf12a4e490.gif)

**Comment by LeandroBraier** [comment]
Me gusta mucho la idea!! El gif me encanta.

PUNTOS:

. Lo que veo es mucha disparidad de fuentes y tamaños de fuentes, 

. El fondo cortado (gris/blanco/gris) que no me termina de gustar. 

. Preferiría que fuera todo gris o todo blanco y con un más elementos rojos y azules para destacar.

. Por qué el GIF de la tablet aparece cortado? Por qué no está la tablet entera?

. Faltan más imágenes como las de los slides del slideshow, para que tenga una estética más homogénea. Te paso aquí los editables:

https://www.wetransfer.com/downloads/3bc394b9c600ee09de0ab8def8e4550420160129153359/6386f6

abrazo

**Comment by braulio-evangelisti** [comment]
Lea Buen día

Te comento sobre los puntos. Si te sigue sin cerrar arranco algo diferente de cero.
- Los textos tienen todos la misma fuente y en el mismo tamaño, a excepción de los títulos y las llamadas a acción que deben destacarse
- Header gris - cuerpo blanco - footer gris: Es la estructura base de de toda la comunidad por eso lo implemente
- La imagen del gif es un mockup de una notebook en realidad, aparece de esa manera ya que generalmente las newsletter se miran en un espacio reducido del total de la ventana del navegador y la vas viendo de a partes, la idea es sugerir visualmente que más abajo sigue o "hay algo mas", le puse ahora la barra de estado como detalle para que sea un poco más explícito que es una notebook pero para el objetivo seria lo mismo en realidad.

En general, al diseño lo pensé directamente para el objetivo que tiene que cumplir y la plataforma en la que se va a visualizar, en este caso que la gente se registre, al ser un mail explicativo la prioridad es el contenido, pero el primer obstáculo es que llegue, y si llega, que se vea bien en la mayor cantidad de dispositivos posibles, por eso no usé imágenes de más ni fuentes extravagantes que después haya que convertir en imágenes como termina pasando muchas de las veces.

![newsletter-bienvenida-b](https://cloud.githubusercontent.com/assets/11272253/12715856/6667a4a4-c8bb-11e5-841e-778508954a40.jpg)

**Comment by LeandroBraier** [comment]
Buen día @braulio-evangelisti ! Entiendo lo que decís y los motivos, pero igual me parece que no termina de quedar bien el newsletter. Probemos con @FAAREIA que está de vuelta, a ver si le da una vuelta final de diseño y me lo mandan en PSD porfa así lo mando al cliente.

abrazo

**Comment by FAAREIA** [comment]
Algo asi?

![newsletter-bienvenida-10- convertido](https://cloud.githubusercontent.com/assets/6184969/12720523/14471bea-c8da-11e5-8c84-bcb6a3cf3b5b.png)

**Comment by LeandroBraier** [comment]
Lo veo mejor @FAAREIA Paso últimos ajustes para que ya me manden el PSD con esto incluido:

1) Agregar tilde a "está online" de la primer frase

2) Falta el efecto de GIF animado, que estaba muy bueno lo que había hecho Braulio y mostraba: Página de registración/ Página de Bienvenida/ Lista de Juegos

2) Sobre el botón rojo y el footer azul, cuando dice COMUNIDAD VIE TUR deberían utilizar el logo en lugar de texto (en texto alt si diría Comunidad VIE TUR)

3) La url está mal. Es www.comunidad.vietur.com.ar

4) El texto "¡Los esperamos!" debería estar en el mismo tamaño de fuente que "¿Querés ser parte de..."

5) El texto en gris del footer abajo de todo no se lee. Cambienle el color o algo.

abrazo

**Comment by mkreyness** [comment]
@LeandroBraier , "www.comunidad" no funciona, lo que esta cargado es solo "comunidad".
Acordate que eso fue porque asi les pedimos a los que controlan el dominio vietur.com.ar que lo hiciera, nunca les pedimos "www.comunidad", y no creo que lo podamos solucionar SOLO del lado de Duplika.

**Comment by LeandroBraier** [comment]
Perfecto MK. Gracias por alertar. Quitemosle el WWW no hay problema. Pero
pongan la url correcta en el news.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-02-01 12:34 GMT-03:00 mkreyness notifications@github.com:

**Comment by braulio-evangelisti** [comment]
Ahi? cuando me des el ok el final le pongo el gif.

![newsletter-bienvenida-10- convertido](https://cloud.githubusercontent.com/assets/11272253/12726477/8c03773e-c8f6-11e5-8322-1c9137289a28.jpg)

**Comment by LeandroBraier** [comment]
Lo veo bien, pero la aplicación del logo de la Comunidad está mal. Este tipo de cosas deberías verlas apenas lo diseñás, Brau. 

Acá no se destaca:

<img width="426" alt="captura de pantalla 2016-02-01 a las 6 31 42 p m" src="https://cloud.githubusercontent.com/assets/6719872/12731412/9b02f624-c90f-11e5-994f-d781a70f71e2.png">

Y acá no se lee VIE TUR:

<img width="348" alt="captura de pantalla 2016-02-01 a las 6 31 45 p m" src="https://cloud.githubusercontent.com/assets/6719872/12731418/a1b71ca2-c90f-11e5-8a22-01ea454b9698.png">

Tendrías que resolver este tema antes de enviarmelo, salta mucho a la vista. Después ya agregale el GIF y mandame el PSD nomás.

abrazo

**Comment by LeandroBraier** [comment]
Chicos, mañana porfa sin falta pasenme este PSD que ya tenemos que mandarlo al cliente.

abrazo

**Comment by braulio-evangelisti** [comment]
[newsletter-bienvenida-comunidad-vitur.zip](https://github.com/LeandroBraier/Vietur/files/113791/newsletter-bienvenida-comunidad-vitur.zip)

![newsletter-bienvenida-c-gif](https://cloud.githubusercontent.com/assets/11272253/12747844/3aa7b9ec-c985-11e5-8fa4-a16d1627e64b.gif)

**Comment by LeandroBraier** [comment]
Quedó muy bueno Brau! Gracias!

**Comment by LeandroBraier** [comment]
@braulio-evangelisti me pasás las fuentes también porfa? O me decís cuales son?

**Comment by braulio-evangelisti** [comment]
Son las fuentes **Arial** y **Verdana**. 
La palabra **Comunidad** en el logo de VIE TUR utiliza una que se llama **DINAlternate-Bold** pero nunca me la mandaron a esa cuando me pasaron el .ai del logo de la comunidad. Encontré una buscando pero es similar no es la misma.

**Comment by LeandroBraier** [comment]
Ok. Perfecto. Gracias Brau!
