### ISSUE TITLE
Nueva dinámica para VIE TUR: Invitar a otros vendedores a sumarse

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#40]
@mkreyness ya tenemos esto desarrollado para la otra comunidad, si bien nunca lo publicamos. Te fijás si lo podemos trasladar a VIE TUR?

**Comment by mkreyness** [comment]
dejame ver, no se si realmente estaba terminado.

**Comment by mkreyness** [comment]
el tema es que tiene un template bastante diferente a los juegos de verdad, esto lo tendria que remaquetar @FAAREIA con la estetica de VIE TUR.
Este es el template de Parex:
http://www.parexklaukol.com.ar/templates/parexklaukol/vendedores/juego-invitacionT.html
Yo voy pasando los programas y las tablas y cuando este la maqueta lo pruebo.

**Comment by LeandroBraier** [comment]
Genial @mkreyness ! Entiendo. @FAAREIA estéticamente y en contenidos no cambiaría casi nada.

Solo pondría "Agencia" en lugar de "Tu corralón" y listo. Las tipografías y colores del juego se podrían aplicar tal cual sobre el fondo de la Comunidad VIE TUR. Recordá que le vamos a hacer una primera entrega al cliente y puede pedir sumar o sacar campos, por eso prefiero que lo dejes tal cual, de ultima pide sacar campos y los sacamos.

abrazo

**Comment by FAAREIA** [comment]
Ya estaba hecho en: http://comunidad.vietur.com.ar/templates/vendedores/juego-invitacionT.html
Lo revisé bien y no hay nada que tocarle creo, una vez implementado capas que se puede ajustar algo pero para mi sale andando solo

**Comment by LeandroBraier** [comment]
Genial Fede!! MK, subilo funcional a VIE TUR cuando puedas (puede ser a la
tarde, no hay tanto apuro) reemplazando el campo de "Tu corralón" por
"Agencia" y lo mando a aprobar al cliente.

abrazo

2016-06-02 9:35 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Ya esta hecho eso cambio del nombre ;)

**Comment by mkreyness** [comment]
No "estaba hecho", lo copie yo anoche desde Parex, por eso lo encontraste @FAAREIA.

No se puede poner asi nomas porque el desplegable de provincias y localidades surge de la base de corralones, que obviamente aca no aplica. Requiere unos cuantos cambios para que sea como el de registracion (con autocomplete).
Me va a llevar un buen rato ajustar esos detalles, lo hago a la tarde pero no creo que se pueda poner a funcionar hoy, hay que probar todo. Esto mandaba un mail creo al "invitado", tengo que ver todo eso.

**Comment by FAAREIA** [comment]
ajaja, ya me pareció raro haberlo encontrado ^^
Cualquier cosa que haya que ajustar decime

**Comment by mkreyness** [comment]
tuve que cambiar varias cosas porque no tenemos una lista de agencias, y como dije antes tuve que poner el autocompletar del registro.
Hay dos cosas mal: el desplegable que hace el autocompletar queda (no se por que) transparente y se pisa con lo que hay debajo. 
Y el input de nombre esta desfasado, algo debe sobrar o faltar.
Aca se puede ver:
http://comunidad.vietur.com.ar/cgi-bin/jugarinvitacion.pl?

Y a eso agregarle esto (los separo por el tema del indexado de Google)

usuario=LBraya02&clave=vietur&gracias=1&id=29

@LeandroBraier habria que cargar alguna imagen en el "Tema" para que se vea arriba en la parte de imagen, o si no sacar eso de la maqueta.
Esta funcional en el sentido de que lo que pongas se guarda en la base, pero nunca se llego a implementar mandar el mail ni la suma de puntos cuando el tipo se registre ni nada, todo eso habria que hacerlo y algo de tiempo siempre quita.

**Comment by LeandroBraier** [comment]
Está perfecto así @mkreyness 

Te paso la imagen que me pedís, porque no encuentro donde cargarla en el CMS:

![recomenda-vie-tur-vendedores-y-gana_03](https://cloud.githubusercontent.com/assets/6719872/15779452/d2a01a80-2972-11e6-92e2-ebe6201a078e.png)

Con esto así lo muestro al cliente y, si me lo aprueba, avanzamos con la parte de implementación que mencionás.

**Comment by FAAREIA** [comment]
Marce, ahi creo que estilicé el autocompletado pero el problema que hay es que la lista aparece debajo del `#footer` y debería de aparecer obligatoriamente dentro del `div.autocompletado`. Una vez hecho eso, me avisas y chequeo si se ve según lo esperado.

Abrazo

**Comment by mkreyness** [comment]
@LeandroBraier esto de la imagen es para cargar en el Tema, como todos los juegos, hay que ponerle un thumb para que aparezca en la lista, y otro mas grande para que aparezca al entrar.
Esto es un "Tema" como cualquier otro, lo cargue en elaboracion obviamente para que no se vea.

**Comment by LeandroBraier** [comment]
Hecho @mkreyness !

Ahora:

1) Me aparece el POP UP como que ya invité a alguien apenas entro, pero todavía no escribí nada en el formulario @mkreyness 

2) Queda muy pegada la imagen al formulario. @FAAREIA Dejá un **/br** o algo en el medio porfa, que no quede tan pegado (PORFA NO PISES ENCIMA DE LO QUE HICE MK)

3) El resto ya está funcional? El mail de envío no lo tenemos aún no?

**Comment by mkreyness** [comment]
1) si ya lo vi. Antes no pasaba, de hecho esta oculto y supuestamente la unica forma que se muestre es que venga un parametro que diga "gracias". No se que le pasa.
2) Yo ya no lo toco mas, me estoy yendo. Revisa lo de la transparencia esa rara, yo no estoy poniendo nada debajo del footer, capaz es algo que hace automaticamente la rutina de autocompletado, que no es mia. Fijate como zafar porque no tengo mucho control sobre lo que hace.
3) No, no hay envio de mails, de hecho no creo que se haya diseñado o maquetado nunca como tendria que ser el mail, no ?

**Comment by LeandroBraier** [comment]
3) @FAAREIA si me pasás el link al mailing de bienvenida que tenemos por defecto para los nuevos inscriptos a la Comunidad yo les paso el contenido y las modificaciones de diseño necesarias.

**Comment by FAAREIA** [comment]
http://comunidad.vietur.com.ar/_mailing/bienvenida-comunidad/bienvenida-comunidad.html

**Comment by FAAREIA** [comment]
Todo hecho.
http://comunidad.vietur.com.ar/cgi-bin/jugarinvitacion.pl? -> usuario=LBraya02&clave=vietur&id=29
- El link mostraba el mensaje de "Gracias" porque el link lo pedia.
- Lo del autocompletado lo fixié.
- La separación entre foto y formulario esta hecha.

**Comment by LeandroBraier** [comment]
Gracias @FAAREIA ! El mail que le mandemos al invitado sería igual al que me mandaste, solo con dos cambios mínimos:

1) Donde dice "Bienvenido a la Comunidad VIE TUR" debe decir lo siguiente:

**"Tu colega XXXXNOMBRE DEL USUARIO QUE INVITÓXXXX te ha invitado a la Comunidad VIE TUR"**

2) Donde dice "Este año tenemos un nuevo espacio para trabajar juntos y alcanzar mejores resultados ¡Y vos ya formás parte!" 
debe decir:

**"Este año tenemos un nuevo espacio para trabajar juntos y alcanzar mejores resultados ¡Y queremos que vos también formes parte!"**

3) Quitar nombre de usuario y contraseña y el botón de Ingresar lleva a la página de Registración

Solo eso abrazo y gracias!

Avisame cuando esté resuelto porfa así hago el testeo final y lo presentamos.

**Comment by FAAREIA** [comment]
http://comunidad.vietur.com.ar/_mailing/invitacion/invitacion.html
En donde dice "Tu colega...te ha invitado bla bla", ahi donde estan los 3 puntos estan las variables de nombre y apellido. @mkreyness

**Comment by LeandroBraier** [comment]
Gracias @FAAREIA !! @mkreyness avisame porfa cuando estén automatizados estos envios.

abrazo

**Comment by mkreyness** [comment]
voy a tratar de liquidarlo todo hoy asi nos lo sacamos de encima.

**Comment by LeandroBraier** [comment]
Genial @mkreyness ! Gracias! Ya creé la actividad que suma puntos cuando el invitado se suscribió.

abrazo

**Comment by mkreyness** [comment]
En realidad quedaron varios rastros adentro del tema de usuario y contrasenia en el link, hago que todo lleve a registro no ? 
Me hace ruido la parte de abajo que dice "todavia no ingresaste?" si en realidad se tiene que registrar.

**Comment by LeandroBraier** [comment]
Gracias @mkreyness ! Tal cual, sin nombre de usuario y pass en ningun lado. Solo nombre del que lo invitó arriba.

En cuanto a la frase de abajo ya fue. Si el cliente dice algo lo cambiamos pero no creo. 

Ya quedó entonces?

**Comment by mkreyness** [comment]
no no, antes de tocar nada preguntaba.

**Comment by mkreyness** [comment]
Subject del mail ?

**Comment by mkreyness** [comment]
ups, me mande un par de pruebas y no vi que estaba copiado comunidadvietur@gmail.
Ahi lo descopie.
Confirmame el tema del subject y ya estaria lista esa parte, solo me falta lo de sumar puntos al referral cuando se registre.

**Comment by mkreyness** [comment]
ya esta todo implementado, confirmame subject y lo dejo todo en condiciones de que publiques el juego de invitacion y el resto se hace solo. Le ajuste el cartel de gracias que decia que sumaba 220 puntos (eso venia asi de lo que se iba a hacer para Parex), le puse 100 porque vi que el juego tiene 100. OJO que si cambias eso tengo que ajustar el template, no es automatico.

**Comment by LeandroBraier** [comment]
Perdón, no sabía. 

El subject sería:

"Tu colega XXNOMBREXXX te ha invitado a sumarte a la Comunidad VIE TUR"

**Comment by mkreyness** [comment]
Y sin apellido ?
No le pongo su propio nombre ? Tipo asi ?

"LEANDRO, tu colega EZEQUIEL te ha invitado a sumarte a la Comunidad VIE TUR"

**Comment by LeandroBraier** [comment]
Ah, si mejor. Nombre y Apellido, si, mejor. Yo te puse nombre en un sentido
general. Quedaría

"LEANDRO, tu colega MARCELO KREYNESS te ha invitado a sumarte a la
Comunidad VIE TUR"

**Comment by mkreyness** [comment]
Listo, si queres "invitate" a alguna otra direccion para verlo.
Igual no te va  a sumar puntos porque estas suspendido, pero si te dessuspendes podes, registrandote con la otra direccion, ganar 100 puntos.
Si ves todo ok, pasa el juego a PUBLICADO y listo.

**Comment by LeandroBraier** [comment]
Ahi lo probé y quedó perfecto. Muchas gracias @mkreyness !! abrazo grande

**Comment by LeandroBraier** [comment]
@mkreyness cuando puedas tranqui (puede ser para mañana) me pidieron que en este formulario el DNI no sea obligatorio. Me confirmás porfa?

**Comment by mkreyness** [comment]
En realidad salvo el nombre y el mail todo el resto de los datos se descarta, ni se para que los pedimos. El tipo que se registre tiene que ingresar todo de nuevo...

**Comment by LeandroBraier** [comment]
Quitemosle el dni nomas porfa.

**Comment by mkreyness** [comment]
Listo.

**Comment by LeandroBraier** [comment]
Gracias MK!
