### ISSUE TITLE
Bug en Botón "Compartir" VIE TUR 

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#41]
http://comunidad.vietur.com.ar/cgi-bin/jugar.pl?id=36  &usuario=LBraya02&clave=vietur

@mkreyness no sé por qué no funciona el Compartir en ninguna de las dinámicas de VIE TUR.

En Parex funciona perfecto. ¿Cuando tengas un ratito te fijas? Esto tiene cierta urgencia porque está en producción, aunque el cliente todavía no se dio cuenta.

**Comment by mkreyness** [comment]
No se en otros casos, pero en este, el nombre del archivo que contiene la imagen que va a compartir es

"2. Thumbnail Trivia Grupos Especiales (1).png"

Eso es terrible, tiene blancos, parentesis, todas cosas que rompen la sintaxis del sharer.

Habria que reuplodearlo como 

thumbnail-trivia-grupos-especiales.png

y es mas probable que funcione. Asi, seguro que no.

**Comment by LeandroBraier** [comment]
Ah ese debe ser el problema. El thumbnail nunca es lo que queremos
compartir pero además Mariela, al cargar la trivia, cargó una imagen en el
campo "Imagen" que no iba y ahora no la podemos eliminar. Esa imagen no va.
Lo que queremos compartir es el video. Puede ser eso?

Mirá que no me funciona ahora en ninguna trivia de video el compartir.

**Comment by mkreyness** [comment]
Porque no estan cargando nada en el campo donde precisamente va lo que se comparte, que es el URL.
Al estar eso vacio, el sistema lo completa con la imagen thumbnail.
MIra como ahora que le COPIE EL URL DEL VIDEO EN EL CAMPO URL anda perfecto...

**Comment by LeandroBraier** [comment]
Brillante MK! Gracias!! AHora entendí. Lo voy a corregir en los demás. Muchas gracias!! abrazo
