### ISSUE TITLE
El CMS no acepta subir imagenes con Ñ u Acentos

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#42]
No se puede solucionar eso? Que los reemplace por simbolos automáticamente?

**Comment by mkreyness** [comment]
Aceptar te acepta, lo que pasa es que despues segun donde lo uses puede traer kilombo o no, si lo usas en un sharer de facebook, seguro trae kilombo.
Si yo te lo cambio y vos crees que todavia se llama como lo pusiste (al referenciarlo desde un URL), tambien va a fallar y vas a tener que adivinar vos que cambios hice, no es mas facil ponerlo bien antes de subirlo ?

**Comment by LeandroBraier** [comment]
Dale. Dejemoslo asi por ahora. No te preocupes.

Era mas que nada para el cliente, que no referencia desde las url pero no
te preocuped. Dejemoslo asi entonces. Abrazo
