### ISSUE TITLE
Sumar puntos por ventas de Junio en VIE TUR

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#43]
Hola @mkreyness ! Cómo va?

Te paso acá el excel con los puntos a sumar en Junio.

[Puntos a sumar en Junio-Comunidad VIE TUR.xlsx](https://github.com/LeandroBraier/Vietur/files/335094/Puntos.a.sumar.en.Junio-Comunidad.VIE.TUR.xlsx)

Recordá, estos se suman a lo acumulado.

NO pisan lo acumulado.

abrazo

**Comment by LeandroBraier** [comment]
@mkreyness me avisás cuando estén subidos porfa?

**Comment by mkreyness** [comment]
ayer se me traspapeló completamente esto, recien ahora que me mandaste el wasap lo vi.
Listo.
