### ISSUE TITLE
Agregar Sección de Ganadores y Espacio en la Home de Ganadores

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#44]
@FAAREIA necesito agregar estos dos elementos de la Comunidad de Vendedores en la Comunidad VIE TUR. Tranqui, para el martes que viene necesitaría la maquetación y para miércoles o jueves la parte de programación y CMS de @mkreyness . Me confirman si llegamos?

**Comment by FAAREIA** [comment]
Sería como lo de comunidad de vendedores no?

**Comment by LeandroBraier** [comment]
Tal cual!

**Comment by FAAREIA** [comment]
Esta caido Vietur. Imagino que es Duplika, si lo mudaron avisen.

**Comment by mkreyness** [comment]
a mi me anda, pero sí, lo mudaron sin avisar hace unos dias. No entres por IP, entra por comunidad.vietur.com.ar

**Comment by FAAREIA** [comment]
Ahora si, gracias

**Comment by FAAREIA** [comment]
Ya esta listo, hay que programarlo nomás.

http://comunidad.vietur.com.ar/cgi-bin/mainvendedores.pl
El div esta oculto y se llama "ultimos-ganadores"

http://comunidad.vietur.com.ar/ganadores.html
Ya estaba hecho y fijense la palabra "ganadore" que esta mal.

**Comment by LeandroBraier** [comment]
Muchas gracias @FAAREIA !! @mkreyness cuando puedas programalo y avisame así cargo los ganadores en el CMS y pasamos a producción.

abrazo

**Comment by mkreyness** [comment]
yo diria al reves, anda cargando los ganadores asi puedo probar.

**Comment by LeandroBraier** [comment]
Ya cargué ganador de Junio MK. Como para que puedas probar.

abrazo

**Comment by mkreyness** [comment]
gracias, yo ya estoy haciendo mi parte, en un rato termino todo.

**Comment by LeandroBraier** [comment]
Genial! Gracias MK!

**Comment by mkreyness** [comment]
La pagina especifica de ganadores ya esta:
http://comunidad.vietur.com.ar/cgi-bin/ganadores.pl?usuario=LBraya02&clave=vietur

falta el agregado de "ultimos ganadores" en la home.

**Comment by mkreyness** [comment]
listo, ya sale en la home tambien.

**Comment by LeandroBraier** [comment]
Impecable chicos!! muchísimas gracias!!
