### ISSUE TITLE
Pequeños Ajustes en Mailing de Bienvenida VIE TUR- 12/07

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#45]
Buen día @FAAREIA ! Te paso un pedido para hoy pero una vez que esté terminado lo de Paty Chile.

Necesito que hagas un mailing de BIenvenida aparte del que tenemos ahora para VIE TUR con ciertos ajustes específicos (no lo reemplaces, simplemente es una nueva versión)

http://comunidad.vietur.com.ar/_mailing/bienvenida-comunidad/bienvenida-comunidad.html

![mailing-de-bienvenida-vie-tur-alternativa](https://cloud.githubusercontent.com/assets/6719872/16766318/c772717e-480f-11e6-9f12-b04998c2b798.png)

URL de las imágenes de ganadores para sumar al GIF:
http://comunidad.vietur.com.ar/vendedores/img/ganadores/Junio-Sabrina-Alvarez-Teseo-Viajes-Ganadores-VIE-TUR.jpg
http://comunidad.vietur.com.ar/vendedores/img/ganadores/Abril-Soledad-Gonzalez-Mauna-Kea-Ganadores-VIE-TUR.jpg

**Comment by FAAREIA** [comment]
Hola Lea, no creo que llegue para hoy aún sigo ajustando lo responsivo del sitio de Paty. Y todavía falta actualizar el mailing

**Comment by LeandroBraier** [comment]
El mailing de Paty Chile lo podés dejar para mañana tranqui. Siendo así
llegás para hoy?

Son ajustes muy puntuales los de VIE TUR.

**Comment by FAAREIA** [comment]
Pero dejo de hacer lo responsivo del sitio de paty?

**Comment by FAAREIA** [comment]
Entendí mal, todavía no termino con el responsivo del sitio y los cambios son varios, no creo que llegue para hoy

**Comment by LeandroBraier** [comment]
Ok, dejá lo responsivo del sitio frenado por un rato y dale prioridad a VIE
TUR entonces porfa. Necesito entregarlo hoy porque lo tengo demorado de la
semana pasada. Después si no terminás el sitio de PAty hoy no importa ya lo
terminás mañana.

abrazo

**Comment by FAAREIA** [comment]
@mkreyness marce, fijate que se agregó un nuevo link en el que hay que enviar un email automaticamente. Esta en el footer el link, fijate en el primer post

**Comment by LeandroBraier** [comment]
Fede, pasame el link prmero porfa así lo hago aprobar antes.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
El link que te dice el mensaje que estas desuscripto?
Aún no lo hice eso

**Comment by LeandroBraier** [comment]
No no, ese no. Me refiero al link donde puedo mostrar el mailing nuevo para que vea el cliente. Como este link:

http://comunidad.vietur.com.ar/_mailing/bienvenida-comunidad/bienvenida-comunidad.html

**Comment by FAAREIA** [comment]
http://comunidad.vietur.com.ar/_mailing/bienvenido-agente/bienvenido-agente.html
http://comunidad.vietur.com.ar/_mailing/bienvenido-agente/desuscripcion.html

Hay que hacer funcionar la desuscripción y que te redireccione a alguna url cuando te desuscribas.

**Comment by LeandroBraier** [comment]
Muchas gracias Fede!! Avancen con eso entonces. Yo le mando al cliente para que apruebe mientrás tanto.

**Comment by mkreyness** [comment]
Esa desuscripción qué seria, dar de baja la cuenta ? Porque el resto de los mailings (que son insoportables, yo los recibo todos) tiene su propio unsubscribe de MailChimp.

**Comment by LeandroBraier** [comment]
jajaja Yo los recibo también. 

En este caso sería solo que le escriban un mail a info@benteveo.tv con el título de "Desuscribirme de la Comunidad" y me llegue con copia a mi, así yo lo desuscribo manualmente. No necesito más que eso. Yo le aviso a la gente de VIE TUR que se comunique con ellos para ver por qué se desuscribieron etc.

Vos decís que es necesario una pantalla de "Has sido desuscripto exitosamente"? Si se puede en pop up podemos hacerlo, sino no vale la pena.

**Comment by mkreyness** [comment]
arriba dice que mande el mail a info@vietur.com.ar, no a benteveo.com.ar
De todos modos yo haria que sea un simple "mailto:", acordate que esto lo recibe por mail, no podemos poner javascript ni nada muy raro.

**Comment by LeandroBraier** [comment]
Claro si. Por eso. Mi idea era que le mande un mail a Info nada más. Con
eso estamos ok. Que los de de baja el cliente directamente.

**Comment by mkreyness** [comment]
ya se puede usar ese template nuevo ? O todavia falta algun OK ?
Porque si no falta nada le modifico esto como mailto, y te mando uno de prueba.

**Comment by LeandroBraier** [comment]
No está aprobado @mkreyness . Me pidieron cambios @FAAREIA Te los paso. Decime si podés hacerlos mañana a la mañana. No parecen complicados.

1) Quitar el link de "Registrate gratis"

2) Cambiar el texto "¿Todavía no descubriste la comunidad VIE TUR?
¡TUS VENTAS TIENEN UN NUEVO INCENTIVO!" por lo siguiente:

"TE INVITAMOS A PARTICIPAR DE LA COMUNIDAD VIE TUR JUNTO CON TU AGENCIA"

3) En el GIF animado agregar 2 fotos más de usuarios premiados: 

http://comunidad.vietur.com.ar/vendedores/img/ganadores/Marzo-Marcela-Martin-Avatar-Viajes-Ganadores-VIE-TUR.jpg

http://comunidad.vietur.com.ar/vendedores/img/ganadores/Mayo-Enrique%20Levstein-Dviajedestinos-Ganadores-VIE-TUR.jpg

(Fijate si podés hacer que queden mejor recortadas las fotos, hay una que pobre le cortaste la cabeza).

4) El texto de "Agente de Turismo" reemplazarlo por el siguiente:

Estimado XXXXNOMBREXXXXX:
Te invitamos a sumarte a la Comunidad VIE TUR. Tendrás BENEFICIOS EXCLUSIVOS y participarás por espectaculares premios todos los meses.
¡Es muy fácil! Solo tenés que capacitarte y jugar en la plataforma.

5) Cambiar el botón INGRESÁ AHORA A LA COMUNIDAD VIE TUR por el siguiente texto: SUMATE AHORA A LA COMUNIDAD VIE TUR 

6) Después de Usuario y Contraseña va el siguiente texto:

"Aprovechá la oportunidad de descubrir todo lo que tenemos pensado para vos y tus pasajeros.!

Y a continuación una lista de los beneficios de la Comunidad a modo de nube de tags en colores con los siguientes items:
CAPACITACIÓN
JUEGOS
BENEFICIOS EXCLUSIVOS
GRANDES PREMIOS TODOS LOS MESES
UN GRAN PREMIO ANUAL

7) Arriba del Footer azul agregar la leyenda "Promoción sin obligación de compra" y pasar junto a esa leyenda la parte de "Desuscripción  de la Comunidad", cambiando el texto por "Si querés desuscribirte de este mail hacé clic aquí o respondé este mail"

abrazo

**Comment by FAAREIA** [comment]
Fijate ahora Lea. La nube de frases/palabras no quedó como tal por la poca cantidad de frases, pero la idea está.

**Comment by LeandroBraier** [comment]
Gracias @FAAREIA ! Lo de la nube está muy bien. Solo te pido:

1) Sumá las fotos nuevas al GIF, que no las veo, y ajustalas para no cortarle la cabeza a las ganadoras.

2) Esta parte de los íconos ponela debajo de la nube de tags:

<img width="674" alt="captura de pantalla 2016-07-13 a las 10 05 19 a m" src="https://cloud.githubusercontent.com/assets/6719872/16803650/edb5f936-48dd-11e6-9af9-50d558143843.png">

Con eso estamos. Gracias!

**Comment by FAAREIA** [comment]
Fijate ahora Lea, dale F5

**Comment by LeandroBraier** [comment]
Lo veo perfecto al mailing! Pero en el GIF no hay más fotos de ganadores, puede ser?

**Comment by FAAREIA** [comment]
Si había subido un archivo viejo ^^
F5

**Comment by LeandroBraier** [comment]
Gracias Fede! Ahora si, pero otra vez les cortamos las cabezas jeje No se puede ajustar eso?

Mirá:

<img width="650" alt="captura de pantalla 2016-07-13 a las 10 38 37 a m" src="https://cloud.githubusercontent.com/assets/6719872/16804484/84f78446-48e2-11e6-82de-81fbde1dac48.png">
<img width="691" alt="captura de pantalla 2016-07-13 a las 10 38 31 a m" src="https://cloud.githubusercontent.com/assets/6719872/16804485/84feabae-48e2-11e6-9cfb-002697bc2706.png">

Lo demás perfecto.

**Comment by FAAREIA** [comment]
La primer foto es vertical, si se ve su cara entera no se ve el premio o se ve parte del mismo y parte del logo que no es vietur
La otra no hay drama, pero se va a ver más el fondo de lo que se ve ahora.
Avisame

**Comment by LeandroBraier** [comment]
Ajustalas a las 2. El logo que no es VIE TUR no molesta, porque VIE TUR es agencia mayorista. La agencia que ves detrás es un cliente de VIE TUR, asi que todo bien. Con esos ajustes lo mando nomás. Gracias!

**Comment by FAAREIA** [comment]
Dale F5

**Comment by LeandroBraier** [comment]
Ahora si, perfecto Fede!! Muchas gracias!!!

Dale nomás a la Landing de Paty Chile entonces. 

abrazo grande

@mkreyness te aviso cuando me den el OK

**Comment by LeandroBraier** [comment]
Feedback puntual del cliente (sin prioridad, para después de Paty Chile, si no llegás hoy, queda para mañana a la mañana):

1 – En el titulo “Te invitamos a participar de la comunidad VIE TUR junto con tu agencia “
cambiar por: "Ya sos suscriptor de VIE TUR. Ahora te invitamos a registrarte en nuestra comunidad exclusiva."

2.- En el texto: "Te invitamos a sumarte a la Comunidad VIE TUR. Tendrás BENEFICIOS EXCLUSIVOS y participarás por espectaculares premios todos los meses.
¡Es muy fácil! Solo tenés que capacitarte y jugar en la plataforma."

Cambiar por el siguiente:

"Hace tiempo que recibís y te informás con nuestros envíos de novedades. Por eso queremos invitarte a dar un paso más y sumarte a la Comunidad VIE TUR, donde tendrás BENEFICIOS EXCLUSIVOS y participarás por espectaculares premios todos los meses.
¡Es muy fácil! Solo tenés que capacitarte y jugar en la plataforma.

3 -  el “capacitacion” esta mas chiquito que juegos y beneficios exclusivos. Que esté en el mismo tamaño. 
4 – la leyenda “Si querés desuscribirte de este mail hacé clic aquí o respondé este mail” agrandala un poco más

Solo eso. Una vez que termines con Paty Chile recién. Antes no.

**Comment by FAAREIA** [comment]
Ahi le modifiqué todo eso.
A la leyenda de desuscripción le agrandé 1pt y le puse un gris más oscuro
La palabra Capacitación la puse igual que la última frase ya que si la ponia igual que la frase que tiene al lado, va a prestar a confusión porque parecería una sola frase.

**Comment by LeandroBraier** [comment]
Gracias Fede!!! Perfecto. Solo te pido que agrandes 2 puntos más la leyenda de desuscripción porque el cliente no va a notar la diferencia. Con eso le mando de vuelta. Muchas gracias!!

**Comment by LeandroBraier** [comment]
Me pide que CAPACITACIÓN quede igual que la frase que tiene al lado, aunque no te guste jeje

Lo pide así.

**Comment by LeandroBraier** [comment]
Nos dieron el OK @FAAREIA ! Solo piden esto que te decía de Capacitación y cambiar el texto de arriba:

1 – En el titulo "Ya sos suscriptor de VIE TUR. Ahora te invitamos a registrarte en nuestra comunidad exclusiva." cambiar por "Ya recibís nuestros newsletters. Ahora te invitamos a registrarte a nuestra COMUNIDAD VIE TUR"

2- Que CAPACITACIÓN quede igual que la frase que tiene al lado

Con eso ya queda final.

**Comment by LeandroBraier** [comment]
Avisame cuando esté @FAAREIA porfa.

@mkreyness cuando esté corregido podés aplicar sumar este mailing a los mailings de VIE TUR (no reemplaces el de Bienvenida automática, ese sigue igual).

abrazo

**Comment by mkreyness** [comment]
Sumar en que sentido ? Cuando se tendria que mandar ?

**Comment by LeandroBraier** [comment]
Digamos: tenemos que mandarlo apenas Fede lo cierro a los 5000 nuevos usuarios. Envialos de a poco, sin bardear al servidor ni spamear, de a poco pero firme pero empezando lo antes posible. Igual @FAAREIA tiene que corregir esos dos detalles primero. Mañana lo vemos.

abrazo

**Comment by mkreyness** [comment]
Y por que no se hace desde Mailchimp ? 
5000 mails a 200 por hora (maximo que nos permite Duplika) son 25 horas.
Esos 5000 nuevos usuarios es un Excel que me vas a pasar o algo asi ?

**Comment by LeandroBraier** [comment]
Si, te lo pasé en este Issue:

https://github.com/LeandroBraier/Vietur/issues/46

El tema es que el mailchimp de VIE TUR lo manejan ellos. Prefiero que lo resolvamos todo nosotros, por eso decía de mandarlo como mandamos todos los mailings de Bienvenida. Es mucho lio?

No me molesta que tarde 25 hs. Incluso te diría que solo mandemos de 6 am a 23 hs, así que tardaría 2 días seguro.

**Comment by LeandroBraier** [comment]
Mmm, entiendo. Vos sugerís que lo mandemos por el mailchimp del cliente verdad?

Hagamos así. Sumalos a todos a la Comunidad sin mandarles el mail y le aviso al cliente de esto. Te parece?

**Comment by mkreyness** [comment]
Pero fijate que esta lleno de errores el excel, mira en el correspondiente issue.

**Comment by LeandroBraier** [comment]
Ok. Borro estos comments de acá para no joderlo a Fede.

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias @FAAREIA !!
