### ISSUE TITLE
Sumar nuevos usuarios a Base VIE TUR y enviar mailing nuevo

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#46]
@mkreyness necesito que sumes estos casi 5.000 usuarios nuevos a VIE TUR y les envies el mailing nuevo que diseñó Fede en este ticket:

https://github.com/LeandroBraier/Vietur/issues/45

[Sumar Base de Usuarios VIE TUR 05-07.xlsx](https://github.com/LeandroBraier/Vietur/files/362300/Sumar.Base.de.Usuarios.VIE.TUR.05-07.xlsx)

Me confirmás cuando los sumes y se manden los mailings?

**Comment by mkreyness** [comment]
hay acentos, comillas raras, grupos de puntos en los codigos, todo eso es para problema, quien va a escribir un codigo con acentos en un login ?
Y aunque lo hiciera, cuando se pasan por URL de una pagina a a otra seguro van a fallar.
Hay gente que su codigo es solo "..", otra que el codigo es solo "ANA",  Y despues hay unos 150 duplicados dentro mismo del Excel, ni hablar si comparo contra la base cargada.

**Comment by LeandroBraier** [comment]
Fuck. Ok. Efectivamente comparaste también con la base cargada? Confirmame
si hay repetidos con la base cargada también así le aviso al cliente junto
con lo demás y le pido que la mande corregida.

2016-07-13 21:48 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
No, todavia no compare. Ahora reviso y te digo.

**Comment by mkreyness** [comment]
Todos estos estan repetidos con la base. Empezando por Alba Darin, que siempre suma muchos puntos.
AlbaDarin
AlejandraCartasegna
AlejandraPacifico
AlejandroZenga
AnaliaFernandez
AnaMariaDiaz
AnaPeralta
CarolinaBordachar
CintiaHecker
DenisaCostabel
DiegoGoldbaum
ElianaCano
EmanuelaDeOliveira
EstelaGarcia
EvelinaAbello
FedericoDeFalco
FernandoKulik
FernandoLopezEsposito
FernandoValenzuela
FlaviaMazzarello
GabrielaRodriguezArmas
GracielaAres
JulietaMolina
KarinaColombo
MaraMartinez
MaraMoreno
MariaInesBesso
MarianaCarril
MatiasBologna
MercedesSolari
MiguelDibetto
MiriamWacht
MirthaAsis
MonicaAparicio
MonicaBalbi
MonicaBiscaldi
MonicaCaporale
MonicaGiraudo
MonicaSabatini
NataliaAndreetta
NataliaCaetanoPombo
NataliaEscobar
NataliaLeiro
NataliaOchoa
NataliaPontieri
NicolasBustos
NicolasDelVecchio
NievesMaldarelli
NoeliaDelpech
NoeliaMontanaro
NoemiPolonski
NoraValdez
OmarMendez
PabloMartinez
PatriciaSalomone
PatricioDeMaestri
PaulaIndarte
PerlaMartin
RobertoHambra
RubenMarcos
SandraPerez
SilviaAlbini
SilvinaRios
VaninaGargiulo
VeronicaDeMataBrito
VivianaAntolin
VivianaMoroni

**Comment by LeandroBraier** [comment]
Gracias MK. Lo hablo con el cliente y te aviso.

**Comment by LeandroBraier** [comment]
@mkreyness va de nuevo el excel, ultra recontra re-chequeado. Confirmame si ahora está bien.

[Sumar Base de Usuarios VIE TUR 15-07.xlsx](https://github.com/LeandroBraier/Vietur/files/369572/Sumar.Base.de.Usuarios.VIE.TUR.15-07.xlsx)

**Comment by mkreyness** [comment]
Así a vuelo de pájaro y desde el celular veo a este tipo repetido :

AlejandroPundyk

Seguramente hay más.  Lo chequeo tipo 4 cuando llego a mi oficina

**Comment by LeandroBraier** [comment]
Dale, porfa. Yo revisé todas la lista varias veces, los caracteres raros,
los nombres y demás. El cheque contra la base de ya inscriptos lo hizo el
cliente. Si sigue habiendo repetidos, le envío esta lista al cliente y que
quite los repetidos, aunque si pudieras rastraerlos y no importarlos sería
ideal, así no seguimos dando vuelta con esto. Simplemente los repetidos que
no se importen.

2016-07-18 14:16 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Sigo viendo a la inefable Alba Darin encabezando la lista de gente que ya esta en la base, y varios mas siguen ahi.

El tema es que yo no creo que todos los codigos duplicados sean la misma persona, pueden ser personas que se llamen igual, el METODO para generar los codigos esta mal, porque no esta tomando nada mas que nombre y apellido.
No tengo exacto una lista de cuales son los duplicados, pero yo tomo la columna de 4886 codigos, lo pego en un editor, le aplico una operacion de "ordenar eliminando duplicados" y me quedan 4707.
Eso significa que ahora hay 169 codigos duplicados.
Si se toman la molestia de ordenar el Excel por la primer columna y la recorren a ojo, van a ver que NO son la misma gente. O capaz si, pero cual de los dos es el correcto si difiere el email, la agencia, etc.
Por ejemplo: 
VivianaPerezRodil. Cual es la buena, la de caldenaviajes.com.ar que vive en Mendoza o la de suntravel.com.ar, que no tiene direccion ?

Cual es la verdadera ValeriaFlores ? La de delposto.com.ar o la de turismoya.com ?
Y SusanaBlanco ? Es la de Clementine Tours o la de CordonBleuTour ?
Y SabrinaHambra ? Es "abinahambra@gmail.com" (parece mal cargado) o "shambra@gcgestion.com.ar" ?
Lo mismo SabinaLascano, es la de TimeArg o la de ViajesMemorables.com ?
Y don RobertoAntonucci que esta TRES veces a falta de una ?
O RicardoSabatini, o RaulGustavoDelgado, o PaulaMartinez, PaulaPerezMelo, PaulaIribarren, PatricioRapaport, donde quieras que mires vas a ver gente repetida, o tal vez NO repetida.

Y esta es mi favorita: su codigo es
"Patricia(NoUsarCambioDeEmpresa)Berazategui"
No podrian borrarla del excel mejor ?

Sigue habiendo muchos apostrofos en los codigos (y por lo tanto tambien en las passwords), tambien es para problema, por ejemplo WalterAlfredoD'albora

**Comment by LeandroBraier** [comment]
jajaja me hacés reir mucho. En medio de dos campañas enormes que estamos
lanzando me tomé demasiadas molestias ya por este excel. Hagamos así: vos
subí los 4707 no duplicados y cuando tengo tiempo de corregir los
duplicados te lo paso.

abrazo

2016-07-18 16:40 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
O sea vos decis que solo suba los que estan una UNICA vez ? O que los que estan n veces suba la primera que vea y listo ?

**Comment by LeandroBraier** [comment]
Los que están una UNICA vez nada más.

2016-07-18 16:46 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
y los que ya esten en la base con ese codigo tampoco. Ok, igual tengo que hacer una purga manual.

**Comment by LeandroBraier** [comment]
No no. Agregale al final de todos los usuarios la frase "VIE" y con eso
estamos, así no se repiten los usuarios. No lo hagas manual. Simplemente
dejá afuera los que tienen el mismo nomre de usuario dentro del excel.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Pero la funcion automatica de eliminar duplicados en Excel siempre deja el primero que encuentra, no sirve para eliminar TODAS las instancias duplicadas.
SI quiero que queden solo aquellos que figuran una sola vez, no queda otra que barrerlo a mano.

**Comment by LeandroBraier** [comment]
Entonces dejalo MK. Yo lo reviso y te lo paso. Dejalo así porfa.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-07-18 18:01 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
ok

**Comment by LeandroBraier** [comment]
@mkreyness acá tenés el excel impecable. Subilo tal cual a ciegas, que está impecable:

[Sumar Usuarios Unicos VIE TUR 19-07.xlsx](https://github.com/LeandroBraier/Vietur/files/372746/Sumar.Usuarios.Unicos.VIE.TUR.19-07.xlsx)

A su vez, revisé la base subida a la Comunidad y encontré mails repetidos, mirá.

**Usuarios suscriptos con mail repetido:**

AlejandraCartasegna
FernandaCartasegna
GracielaGaraventa
JorgeJordan
EstebanParolin
CarmenCasasbellas
GastonParolin
APERALTA67
AnaPeralta
StellaDiLeila
LucasSaladino
YamilaDreus
MiguelPassennheim
MirthaLevano
EduardoMaluf
MartaCaluch
LoryRoccaDeRey
RicardoHectorReyAvila
StefaniaSaco
GladysCosciari
Ariel Pinazzi
Adriana Ortiz
CynthiaCanovas
MabelMarchese
ManuelaFalibene
AndresCunati
AgustinaIsely
MarianoRotman
NataliaCa
NCASAS64
NoeliaDuarte
VeronicaKrauss
DinaBravo
AlbertoMosquera
MonicaCaporale
SandraSanchez
AnaMariaStefanni
MariaCeciliaDeToro
LidiaMariaDeRosa
MiguelFernandezCosta
DCarnevale59
MatiasCarnevale
Mbello de 37
MarianaBello
LeonardoPizzuto
LucasCayian
MaximilianoSalafia

**Mismo mail 2 usuarios, pero uno no tiene código:**

ventas1@arcoiristravel.tur.ar
ventas1@arcoiristravel.tur.ar

abrazo

**Comment by mkreyness** [comment]
Ok, lo hare tan a ciegas que cuando me tire errores de duplicacion estare mirando para otro lado :)

Distintos usuarios con el mismo mail no hay problema. Siempre que dan algo tipo "ventas@pirulotur.com" y se anotan 3 vendedores, mala suerte, recibiran los 3 mails en la misma direccion, pero con los datos de acceso de c/u.
En cuando al que no tiene codigo, obviamente nunca tuvo actividad asi que lo borro.

**Comment by LeandroBraier** [comment]
Genial. Gracias!

**Comment by mkreyness** [comment]
listo, te los cargue todos en estado "pendiente Mailchimp", para que puedas si queres exportarlos (asi te queda compatible el formato con el de la maillist que tengas armada en Mailchimp, o podes usar el excel que ya tenes, pero despues de enviado igual deberias darle "marcar Enviado" para que despues cuando entren se procese bien.

**Comment by LeandroBraier** [comment]
No entiendo una cosa. LO usuarios están funcionando entonces, no? Más allá
de que yo todavía no les haya mandado el mail.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-07-20 2:58 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Si, funcionan igual que cualquiera (recien probe con uno), pero no recibieron nunca su usuario y contraseña por mail, asi que como sabrian como entrar ?

**Comment by LeandroBraier** [comment]
Sisi, eso obviamente. Gracias @mkreyness !!!!
