### ISSUE TITLE
Quiz sin imágenes

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#47]
@mkreyness fijate que se ven negras las imágenes de opciones. Estuve investigando y no pude descular por qué. Me decís?

http://comunidad.vietur.com.ar/cgi-bin/quiz.pl?id=100

usuario=LBraya02

clave=vietur

**Comment by mkreyness** [comment]
En el CMS veo que hay imagenes asociadas a la PREGUNTA, pero no a las OPCIONES. Por ejemplo, entras en la de james bond, y en la opcion MANDARIN no hay anda.

**Comment by mkreyness** [comment]
"nada"

**Comment by LeandroBraier** [comment]
Es que la imagen tiene que estar en la pregunta, no en las opciones de
respuesta. Es un agregado que te pedimos la otra vez y lo agregaste. Por
eso está ahí. Te lo pedimos como un desarrollo especial te acordás?

**Comment by mkreyness** [comment]
Estas usando el tipo equivocado de juego entonces. Fijate como era el que salio bien, y ponele ese mismo tipo.

**Comment by mkreyness** [comment]
Lo que yo veo es que hay TRIVIAS con imagen, pero no QUIZES con imagen.
Me parece que lo que queres nunca se hizo.

**Comment by LeandroBraier** [comment]
Tenés razón, era eso. Era un cuestionario no un quiz. Gracias @mkreyness ! abrazo
