### ISSUE TITLE
Borrado de listado de usuarios

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#48]
@mkreyness el cliente se dio cuenta de que hay usuarios que sumamos la semana pasada y no le sirven. Se puede eliminar por listado también?

Espero tu confirmación.

**Comment by mkreyness** [comment]
Si me mandas una lista de usuarios a borrar (codigo solamente) yo los limpio, si.

**Comment by LeandroBraier** [comment]
perfecto. Gracias!

**Comment by LeandroBraier** [comment]
@mkreyness te paso la lista de usuarios a borrar. Puede ser para mañana tranqui.

[Listado de Usuarios a Eliminar de Comunidad VIE TUR 28-7.xlsx](https://github.com/LeandroBraier/Vietur/files/389538/Listado.de.Usuarios.a.Eliminar.de.Comunidad.VIE.TUR.28-7.xlsx)

abrazo

**Comment by mkreyness** [comment]
listo, todos estos borrados.

**Comment by LeandroBraier** [comment]
Muchas gracias MK!!

**Comment by LeandroBraier** [comment]
@mkreyness cuando puedas tranqui borrá esta listita también.

[Listado de Usuarios a Eliminar de Comunidad VIE TUR 29-7.xlsx](https://github.com/LeandroBraier/Vietur/files/391556/Listado.de.Usuarios.a.Eliminar.de.Comunidad.VIE.TUR.29-7.xlsx)

abrazo

**Comment by LeandroBraier** [comment]
Buen día @mkreyness ! Avisame cuando los tengas eliminados.

abrazo

**Comment by mkreyness** [comment]
Ah, habia una segunda lista, no lo habia visto. Ok ahora lo hago.

**Comment by LeandroBraier** [comment]
Gracias!

**Comment by mkreyness** [comment]
listo

**Comment by LeandroBraier** [comment]
Muchas gracias MK! abrazo

**Comment by LeandroBraier** [comment]
@mkreyness tengo una listita nueva a eliminar. Puede ser para mañana, no hay apuro. abrazo

[Listado de Usuarios a Eliminar de Comunidad VIE TUR 4-8.xlsx](https://github.com/LeandroBraier/Vietur/files/402050/Listado.de.Usuarios.a.Eliminar.de.Comunidad.VIE.TUR.4-8.xlsx)

**Comment by mkreyness** [comment]
listo

**Comment by LeandroBraier** [comment]
Gracias MK!

**Comment by LeandroBraier** [comment]
Marce, tengo un nuevo listado de usuarios para eliminar. Me confirmás cuando los hayas eliminado?

[Listado de Usuarios a Eliminar de Comunidad VIE TUR 19-8.xlsx](https://github.com/LeandroBraier/Vietur/files/427532/Listado.de.Usuarios.a.Eliminar.de.Comunidad.VIE.TUR.19-8.xlsx)

**Comment by mkreyness** [comment]
Listo

**Comment by LeandroBraier** [comment]
Gracias Marce!!

**Comment by LeandroBraier** [comment]
@mkreyness va la última tanda de usuarios de Comunidad VIE TUR a eliminar. Me avisás cuando esté hecho porfa?

[Listado de Usuarios a Eliminar de Comunidad VIE TUR 30-8.xlsx](https://github.com/LeandroBraier/Vietur/files/445832/Listado.de.Usuarios.a.Eliminar.de.Comunidad.VIE.TUR.30-8.xlsx)

abrazo

**Comment by mkreyness** [comment]
listo

**Comment by LeandroBraier** [comment]
Gracias MK!
