### ISSUE TITLE
Sumar puntos por ventas de Julio en VIE TUR

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#49]
@mkreyness hoy cuando puedas durante el día los subís porfa?

[Puntos a Sumar en Julio- Comunidad VIE TUR.xlsx](https://github.com/LeandroBraier/Vietur/files/386581/Puntos.a.Sumar.en.Julio-.Comunidad.VIE.TUR.xlsx)

abrazo

**Comment by mkreyness** [comment]
ahora lo proceso

**Comment by mkreyness** [comment]
listo

**Comment by LeandroBraier** [comment]
Gracias @mkreyness !
