### ISSUE TITLE
Pequeños Bugs de Comunidad VIE TUR

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#5]
@mkreyness tengo un problemita medio raro. Borré el link de la Documentacion en una Trivia y sigue apareciendo. Te fijás qué puede ser?

Quería probar de paso si desaparecía el texto de "Documentación" si no hay ninguna para linkear.

http://comunidad.vietur.com.ar/cgi-bin/jugar.pl?id=5

usuario=mk

clave=pepe

**Comment by mkreyness** [comment]
Esa no es la forma. Lo que tenes que hacer es eliminar el "juego" de trivia por documentacion del tema, asi cambia de template.
El truco no es si hay documentos, sino la seleccion del template segun los "juegos".

**Comment by LeandroBraier** [comment]
Ahhhhhh OK. Igual me resultaba raro que mantenga el Link al Catalogo que borré pero claro, está cargado en el juego también. Me olvidaba jeje Gracias!
