### ISSUE TITLE
Agregar Sección Beneficios a Comunidad VIE TUR. 04/08

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#50]
@FAAREIA como te comenté por Skype, necesitamos agregar una sección de beneficios a la Comunidad VIE TUR. Para eso haremos lo siguiente:

1) Tendría una sección propia como ganadores, pero con una maquetación más parecida a esta, con thumbnails cuadrados clickeables con diseños:

<img width="788" alt="seccion beneficios" src="https://cloud.githubusercontent.com/assets/6719872/17266016/47ef4d78-55ca-11e6-8188-a27eb52843ec.png">

2) Al hacer clic en cada beneficio, se abre la imagen en tamaño grande, preferentemente 1000x1000, para que se lea toda la info en la imagen.

3) En la home aparecería en la columna derecha debajo de TUS LOGROS bajo el nombre de TUS BENEFICIOS

El diseño sería algo parecido a esto, con pequeñas miniaturas que muestra la variedad de Beneficios:

<img width="371" alt="captura de pantalla 2016-07-06 a las 8 04 59 p m" src="https://cloud.githubusercontent.com/assets/6719872/17266038/7d778c4e-55ca-11e6-96fe-77060d872891.png">

Cualquier duda avisame. 

abrazo

**Comment by FAAREIA** [comment]
Algo asi lea?

![prueba](https://cloud.githubusercontent.com/assets/6184969/17623984/2747ff5c-6079-11e6-856b-a1c4adbc8f00.jpg)

**Comment by LeandroBraier** [comment]
Perfecto para el punto 1!

**Comment by LeandroBraier** [comment]
Armame los diseños de 1, 2 y 3 y lo mando a aprobar al cliente.

**Comment by FAAREIA** [comment]
Ahi van los otros dos:

![sin-titulo-1](https://cloud.githubusercontent.com/assets/6184969/17698982/94adb672-6394-11e6-8094-0d527c405bed.png)
![temp](https://cloud.githubusercontent.com/assets/6184969/17698984/9502a632-6394-11e6-8b4d-63d39dee404c.jpg)

**Comment by LeandroBraier** [comment]
Excelente Fede!!! Ya le mandé al cliente. Esperemos feedback.

Si podés resolvé ahora esto que son 2 segundos, un cambio de texto: https://github.com/LeandroBraier/Vietur/issues/52

abrazo

**Comment by LeandroBraier** [comment]
El cliente dio el OK! avancemos con la maquetación nomás y pasale a @mkreyness  así puede armar la parte del CMS.

abrazo

**Comment by FAAREIA** [comment]
El bloque de beneficios solo va en el home o en todas las secciones?
Lo ve el usuario registrado también?

**Comment by FAAREIA** [comment]
Todo hecho y subido, falta el desarrollo nomás @mkreyness 
http://comunidad.vietur.com.ar/beneficios.html
El bloque de beneficios que va en el aside esta oculto, con un `style="display: none;"` Lo puse en los 2 templates de aside, el común y el registrado.

**Comment by LeandroBraier** [comment]
Si lo ven ambos, registrados y no registrados. Aparte de la home no hace
falta que esté en otro.

**Comment by LeandroBraier** [comment]
Gracias Fede! Adelante mk!

**Comment by FAAREIA** [comment]
El tema aca es que si lo ve en una página lo ve en todas, esta hecho diferente que en revear que es el más nuevo por ejemplo. Igual si es necesario lo dejamos solo en el home. Avisa

**Comment by mkreyness** [comment]
Pero entiendo ademas que hay algun tipo de proceso de asignacion de los beneficios a los usuarios ?

**Comment by LeandroBraier** [comment]
Nono. Los beneficios no son para los usuarios. Es como un beneficio de los
planes que ellos venden.  No hay una funcionalidad diferente de la
informativa.

Fede dejala en todas las paginas. No pasa nada.

**Comment by mkreyness** [comment]
Ah ok, entonces los campos a tener en el CMS serian un titulo, un numero de orden, una descripcion mas larga, un thumbnail y una foto grande ?.

**Comment by LeandroBraier** [comment]
Tal cual MK. Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
pregunta: en lo que aparece en el aside, que es mas chiquito todavia, es fijo y de adorno lo que esta puesto o tiene que ir una miniimagen (mas chiquita todavia que el thumbnail) de los verdaderos ? 
O sea, tendria que agregar un segundo thumbnail ?

Aca pueden ver version (no publicada todavia) para usuarios

http://comunidad.vietur.com.ar/cgi-bin/mainvendedores2.pl?dni=16203035&clave=aaaa

 y para no usuarios
http://comunidad.vietur.com.ar/cgi-bin/mainvendedores2.pl

al hacer click lleva a la pagina de beneficios, con un par de boludeces que cargue en el CMS (esta al final de la parte Adm. del Club de Vendedores).
Hablando del CMS, el editor del texto del contenido, tendria que ser HTML ? Porque no esta instalado ese feature en Vietur, si no hace falta no vale la pena instalarlo.

**Comment by LeandroBraier** [comment]
Gracias @mkreyness !

Te respondo: En el aside de la home van los mismos thumbnails que en la página de beneficios pero en tamaño menor. Los puedo cargar como un segundo thumbnail en el tamaño que vos me digas, como hacemos siempre. Todo bien.

FEEDBACK: Debe haber faltar algo de programación o de maquetación porque veo todo descuajeringado, sin imagenes en el aside y en la página de beneficios un lio. Te paso capturas:

Podremos resolver esto para hoy así llego a cargar los beneficios?

<img width="380" alt="captura de pantalla 2016-08-18 a las 10 49 22 a m" src="https://cloud.githubusercontent.com/assets/6719872/17775255/c7573d4c-652d-11e6-9637-35f5a2e9a368.png">

<img width="1139" alt="captura de pantalla 2016-08-18 a las 10 49 16 a m" src="https://cloud.githubusercontent.com/assets/6719872/17775256/c757c8a2-652d-11e6-872d-883dcf489c05.png">

**Comment by mkreyness** [comment]
Estas usando los URLs que te pase ? Porque a mi me sale todo perfecto, probaste dar F5 ? Capaz te faltan estilos en el CSS que tenes cacheado.

**Comment by mkreyness** [comment]
Ahora te agrego el campo del 2do thumbnail para que vayas cargando en el CMS lo que corresponda y sobre eso trabajo esta tarde en poner los thumbnails reales en el aside.

**Comment by LeandroBraier** [comment]
Tenias razon. Hice F5 y los veo perfectos. Adelante nomás. Avisame cuando lo tengas.

abrazo

**Comment by mkreyness** [comment]
Ya esta agregado el campo nuevo, fijate. Avisame cuando tengas todo cargado y ajusto lo necesario en el programa, lo probamos, y lo liberamos.

**Comment by LeandroBraier** [comment]
Gracias MK! Lo cargo y te confirmo.  Abrazo

**Comment by LeandroBraier** [comment]
Ahi probé subir 2 beneficios y no se ven bien.

1) Lo de la home es una imagen fija, no muestra las imágenes subidas en los beneficios (para lo cual entendí que eran los minithumbnails, no?

2) Tomé de referencia de tamaño para los Thumbnails una imagen tuya y resulto equivocada. Decime el tamaño real de la imagen y lo adapto.

3) El titulo BENEFICIOS en la maquetación no se ve bien. Paso captura de beneficios y ganadores para que veas a qué me refiero:

<img width="1062" alt="captura de pantalla 2016-08-18 a las 7 43 02 p m" src="https://cloud.githubusercontent.com/assets/6719872/17792681/af46a648-6578-11e6-86fa-4fd14656ded9.png">

<img width="1140" alt="captura de pantalla 2016-08-18 a las 7 45 12 p m" src="https://cloud.githubusercontent.com/assets/6719872/17792684/b16cdf1e-6578-11e6-8ba9-882eb1be3cb3.png">

Si podés cambiarlo a Beneficios VIE TUR mejor.

abrazo

**Comment by mkreyness** [comment]
No esta todavia aplicado lo de los minithumbnails, justamente necesito que subas 6 imagenes (del tamaño correcto) para poder probarlo.
Los tamaños correctos (para cualquier cosa) son los de la maqueta de Fede obviamente, tomalos de ahi, yo subi cualquier foto que tenia a mano.
Ademas estaba pendiente mi pregunta de lo del editor HTML.
Lo del texto de beneficios, es tema de la maquetacion, obviamente puedo cambiar el texto, pero no la posicion @FAAREIA lo tocas directamente sobre el template ? esta en /templates/vendedores/beneficiosT.html

**Comment by LeandroBraier** [comment]
@faareia porfa pasame los tamaños qie deben tener los 3 tipos de imagenes
también, porque no me puede fiar ni los archivos originales ni en captura
de pantalla porque depende de la resolución.

2016-08-18 19:43 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
ya hice que tome los thumbnailcitos en el aside. Cuando completes los 7 va a verse mejor.

**Comment by LeandroBraier** [comment]
Gracias MK!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
http://comunidad.vietur.com.ar/cgi-bin/beneficios.pl?dni=16203035&clave=aaaa
En las imágenes thumb nunca pongan un flyer o algo con tanto texto ya que en mobile nunca va a verse bien y hasta capas ni se lee el texto. La imagen tiene que ser un fondo y un título como máximo, el cual estaría repetido con el título en texto abajo.
La imagen thumb tiene que ser 228x216
La imagen de adentro es libre, se adapta a lo ancho.

Cuando este terminado veo lo del título y ajusto lo que haga falta.

**Comment by LeandroBraier** [comment]
Entendido Fede!! Gracias!!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-08-19 9:27 GMT-03:00 Federico Arena notifications@github.com:

**Comment by mkreyness** [comment]
avisame cuando ya se pueda pasar a produccion

**Comment by LeandroBraier** [comment]
Dale, en 10 lo termino de cargar y te confirmo.

**Comment by LeandroBraier** [comment]
@mkreyness estoy cargando los beneficios pero tengo 5 en total nomás. No tenés forma de repetir 2 para que quede bien la home?

**Comment by mkreyness** [comment]
Decime cuales queres que repita y listo.

**Comment by LeandroBraier** [comment]
Dale. Repetí Paseo en Barco en Dinamarca y Crucero Panorámico en Paris. Mientras estoy cargando los 2 que faltan para los 5.

**Comment by LeandroBraier** [comment]
Perdón. Repetí también el de Hard Rock Café, porque tengo 4 nada más. No sé por qué pensé que tenía 5. Ya están los 4 cargados.

**Comment by mkreyness** [comment]
listo pero queda un poco evidente si los pongo en el mismo orden, queres que los desordene un poco ?

**Comment by LeandroBraier** [comment]
Dale porfa.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
fijate, los ordena random, cada vez los pone diferente (siempre repite las mismas posiciones, pero el contenido varia).
Esto solo afecta ahi, en la lista de beneficios despues siempre aparecen en el orden que los cargaste.

**Comment by LeandroBraier** [comment]
Impecable @mkreyness !! Me parece perfecto así!

Solo falta lo del espaciado del título y demás que es tuyo @FAAREIA Con eso lo mando.

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias @FAAREIA ! te aviso cuando tenemos OK para pasar a producción.

abrazo

**Comment by LeandroBraier** [comment]
@FAAREIA me quiero matar. Me acabo de dar cuenta que la imagen que usaste de fondo para el banner del 0800 es una foto que no podemos usar más (empleado despedido). La podés cambiar por la que pusimos actualmente en Club de Colocadores? Con el colocador nuevo?

Te la paso acá:

![foto-tu-trabajo-vale-colocadores-new](https://cloud.githubusercontent.com/assets/6719872/17856587/a0944a2c-6854-11e6-821b-b43622f98f21.png)

Confirmame porfa apenas lo hayas actualizado porque me mata el cliente jeje

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Todo OK lo de beneficios @FAAREIA y @mkreyness !! Perdón que les subí la foto en el ticket equivocado jeje

Todo OK para pasar a producción apenas puedan. Confirmame porfa.

abrazo

**Comment by mkreyness** [comment]
Yo lo habilito todo en un rato, tengo que renombrar los programas (sacarle el '2').

**Comment by LeandroBraier** [comment]
Excelente MK!! Gracias!

**Comment by LeandroBraier** [comment]
@FAAREIA cuando puedas tranqui, me pidieron modificar el texto de "MIRÁ NUESTRO BENEFICIOS" de la Home a "TUS BENEFICIOS"

Les dije que va a estar pero más adelante, sin apuro.

abrazo

**Comment by mkreyness** [comment]
ya esta puesto todo en produccion (salvo ese cambio de la home que decis)

**Comment by LeandroBraier** [comment]
Perfecto MK! Muchas gracias!

**Comment by LeandroBraier** [comment]
@FAAREIA dejo el ticket para que me avises nomás cuando tengas listo el cambio de diseño, tranqui.

abrazo

**Comment by FAAREIA** [comment]
Hecho lo del cambio de título

**Comment by LeandroBraier** [comment]
Excelente!! Gracias Fede!!!

**Comment by LeandroBraier** [comment]
@FAAREIA el cliente se quedó sin beneficios para mostrar y me pide si podemos ocultar los beneficios en la home hasta que tengan nuevos. Parece que puede llevar un tiempo.

Me confirmás si se puede hacer?

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias @FAAREIA !
