### ISSUE TITLE
Invertir Orden de Ganadores VIE TUR 11/08

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#51]
@mkreyness  tranqui para el jueves necesito que los ganadores de la sección ganadores de VIE TUR se vean del último al primero.

Actualmente veo primero el ganador de marzo, después abril y demás. Ellos quieren al revés.

abrazo

**Comment by mkreyness** [comment]
listo

**Comment by LeandroBraier** [comment]
Gracias @mkreyness !
