### ISSUE TITLE
Pequeño Cambio: Agregar frase en Bases y Condiciones

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#52]
@FAAREIA cuando puedas fijate si podés agregar esta frase en bases y condiciones.

<img width="1069" alt="captura de pantalla 2016-08-12 a las 6 51 31 p m" src="https://cloud.githubusercontent.com/assets/6719872/17637489/3a4f61da-60ba-11e6-8e9c-595e890b402a.png">

Frase:
**Todos los impuestos, tasas y demás cargos que se apliquen sobre las tarifas aéreas comprendidas en los premios serán a exclusivo cargo del ganador.**

abrazo

**Comment by LeandroBraier** [comment]
@FAAREIA esto para cuando lo podemos tener?

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias Fede!
