### ISSUE TITLE
Nuevo Juego VIE TUR- Memory Test

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#53]
@valentinsabbath te paso el nuevo juego que tenemos que armar para VIE TUR. 

https://www.wetransfer.com/downloads/57accd106b8158a4104a04206b7539a320160819161544/24d7b7

Me confirmás si lo podés abrir todo bien? Esta vez nos aseguramos que se pueda abrir con Construct 2.

https://codecanyon.net/item/c2-memory-matrix/13715961?s_rank=3

**Comment by ghost** [comment]
Dale ahi te aviso

**Comment by ghost** [comment]
Funciona perfecto

**Comment by LeandroBraier** [comment]
Excelente. Me pasás cuales son las piezas que hay que rediseñar por acá?
Así las pido.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by ghost** [comment]
Dale, ahi te las mando, pero antes podes ver el juego, tiene algunas cosas que por ahi están de mas y  pueden volar

**Comment by ghost** [comment]
Este es el link del preview
http://preview.codecanyon.net/item/c2-memory-matrix/full_screen_preview/13715961

**Comment by LeandroBraier** [comment]
Si, lo vi. O sea, pasame todas las IMG que tengas. Quizá no vamos a poner
tantas variantes de imágenes pero necesitamos cambiar el fondo, el nombre
del juego, el ciervito del principio, todo. Las banderas por ahí queden,
pero todo lo demás cambia.

**Comment by ghost** [comment]
Ahi está todo Lean
[images.zip](https://github.com/LeandroBraier/Vietur/files/427593/images.zip)

**Comment by LeandroBraier** [comment]
Muchas gracias Valen!

La semana que viene te paso las fotos y ya lo reemplazamos. Vos sabés cómo
ir haciendo la programación para que sume los puntos y demás?

**Comment by ghost** [comment]
La suma de puntos es similar al juego de las banderas?

**Comment by LeandroBraier** [comment]
jeje No recuerdo como era. Es un total de puntos por jugarlo o por pasar X
nivel verdad? Si es así, sí.

Es decir, pasando el nivel 3 ya sumaste 300 puntos. Después podés seguir
jugando pero no sumás más puntos.

**Comment by ghost** [comment]
Cuando llegaba a x cantidad de puntos y finalizaba el juego, @mkreyness  me pidió que llamara  a una url. Hay que ver si tiene que hacer algo el para que yo pueda llamar a ese programa

**Comment by LeandroBraier** [comment]
Exacto. Hagamos eso. Creo que lo que hace es pasar de nivel, pero fijate en
la programación del juego y decime.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-08-19 15:11 GMT-03:00 valentinsabbath notifications@github.com:

**Comment by ghost** [comment]
En este juego tenes por un lado "SCORE" y por otro lado "NIVEL".
A qué te gustaría darle bola para sumar puntos?

**Comment by LeandroBraier** [comment]
Si se puede nivel mejor. Al que pase el nivel 3 sumale los 300 puntos.

**Comment by ghost** [comment]
Genial, le hice una consulta por mail a mk y me de el ok lo hago

**Comment by ghost** [comment]
y el que no pasa de nivel hay que dejarlo volver a jugar?

**Comment by LeandroBraier** [comment]
A todos hay que dejarlos volver a jugar todo lo que quieran. Simplemente
suman los 300 puntos una sola vez.

**Comment by mkreyness** [comment]
De si ya sumo no te tenes que preocupar @valentinsabbath , yo ni te paso el ID del juego cuando el tipo ya lo jugó, y en tal caso no tenes que llamar al URL, simplemente deja que el juego vuelva a empezar.
Lo mismo yo diria que si no superó el nivel ni llames al URL, dejalo volver a empezar.

**Comment by ghost** [comment]
Entonces llamo al url solo si supera el nivel 3

**Comment by LeandroBraier** [comment]
Tal cual.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Ah, al final este es Construct2 ? Me confundi con el ultimo ese que habia sido un bolonki. 

@LeandroBraier lo tenes que poner como juego tipo HTML5, igual que el "Coloca con Klaukol".
y al tema ponele como URL DE VIDEO esto: img/vendedores/banderas

@valentinsabbath tenes acceso FTP al servidor de Klaukol ? Te hice una carpeta donde bajar el juego (el index.html tiene que quedar dentro de esta carpeta):
~/public_html/parexklaukol/vendedores/img/banderas

lo unico que tengo que ver bien es a que URL estas llamando desde adentro del juego, confirmame.

**Comment by ghost** [comment]
@mkreyness  el juego al finalizar dispararia esto
URL: "/cgi-bin/sumapuntos.pl?juego= http://sumapuntos.pl/?juego=" &
Browser.QueryParam("juego") & "&usuario="  & Browser.QueryParam("usuario")
& "&clave="  & Browser.QueryParam("clave")

**Comment by mkreyness** [comment]
Ademas de lo del nivel, tenes que llamarlo SOLO si Browser.QueryParam("juego") es mayor que cero.
Si no, significa que ya lo jugo y no corresponden sumar mas puntos.
Tenes el acceso FTP como para bajar todo a la carpeta que te dije ?

**Comment by ghost** [comment]
No tengo acceso

**Comment by mkreyness** [comment]
te lo paso por mail, todo lo que escribamos aca es publico.

**Comment by mkreyness** [comment]
ahi te mande, cualquier duda consultame, y plis no borres ni formatees nada :)

**Comment by ghost** [comment]
Ahora lo unico que vas a ver es un error 404 ;) gracias!

**Comment by ghost** [comment]
Voy a subir el juego para testing de los puntos, aclaro porque todavía no
está maquillado para vie tur

**Comment by LeandroBraier** [comment]
Perfecto. Probemoslo todo lo posible antes.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-08-22 18:23 GMT-03:00 valentinsabbath notifications@github.com:

**Comment by mkreyness** [comment]
Para poder probar tiene que estar cargado el tema+juego en el CMS, en estado ELABORACION para que el resto de gente no lo vea.
Si no no vas a tener el dato del numero de juego en el URL.

**Comment by mkreyness** [comment]
AIIIII pero esto es VIE TUR ?? Tengo todo confundido.
Entonces estamos hablando de MEMORY TEST, no de BANDERAS, todo lo que yo dije era de BANDERAS en Klaukol !

**Comment by mkreyness** [comment]
Los datos de acceso que pase e instrucciones son PARA BANDERAS EN KLAUKOL

**Comment by mkreyness** [comment]
Ahora te paso de nuevo por mail los datos de VIE TUR para el MEMORY TEST.

**Comment by mkreyness** [comment]
Listo, seguimos (lo digo para mi mismo) en VIE TUR MEMORY TEST. Quien necesita un MEMORY TEST, eh ?
@LeandroBraier El juego crealo con tipo HTML5, y en el url de VIDEO del tema pone 

/vendedores/juegos/memorytest

**Comment by LeandroBraier** [comment]
Hecho @mkreyness ! Tema y Juego creados.

**Comment by valentinsabbath** [comment]
El juego está seteado pero no me puedo conectar al server
Acá está el juego 
https://drive.google.com/drive/folders/0B0BybArEfuZoeU1JaHB2eWgtLU0?usp=sharing

**Comment by mkreyness** [comment]
Por favor Valen comprimilo en un tar.gz y pasame un solo link a un solo archivo, no puedo estar subiendo folders con cosas sueltas.

**Comment by valentinsabbath** [comment]
[Memory Matrix.tar.gz](https://github.com/LeandroBraier/Vietur/files/433049/Memory.Matrix.tar.gz)

**Comment by mkreyness** [comment]
No publiques el tar aca ! Todo lo que publiques aca se indexa y sale en Google. 
Borra tu entrada anterior y tene en cuenta lo que dije en el de banderas: lo que tenes que pasarme es la carpeta que genera la EXPORTACION a HTML5, no el fuente/resources/backups/etc. del proyecto.

**Comment by ghost** [comment]
El de Parex estoy seguro que estaba bien.
Te mandé los dos exports de parex y vietur por mail.
Avisame si estàn ok

**Comment by mkreyness** [comment]
Este esta bien (el de VIE TUR) justamente el que estaba mal era el de Parex.

**Comment by mkreyness** [comment]
aca esta andando VIE TUR:
http://comunidad.vietur.com.ar/vendedores/juegos/memorytest/

**Comment by ghost** [comment]
@LeandroBraier no se puede hacer que el que pase el tercer nivel sume los puntos, porque el juego solo tiene 3 niveles.
Cuando terminas el tercer nivel, sumas mas de 800 pts. Entonces le puse que al sumar mas de 800 pts llame a sumapuntos

**Comment by LeandroBraier** [comment]
Está perfecto @valentinsabbath ! Te estoy pasando en breve las imágenes a reemplazar así ya queda.

**Comment by LeandroBraier** [comment]
Necesitaría que me pases los textos a traducir porfa. Así te los voy pasando. Tenés forma de pasarme eso?

**Comment by ghost** [comment]
Los textos a traducir en realidad son imágenes que están en el zip images.zip mas arriba

**Comment by LeandroBraier** [comment]
Perfecto, entonces lo tenemos cubierto. Gracias!

**Comment by LeandroBraier** [comment]
Buen día @valentinsabbath ! Cómo va?

Acá ya tengo las imágenes a reemplazar.

A su vez, del menú de íconos, te pido que dejes solo el de las banderas y el que subimos en la imagen "iconsapp-sheet1.png". Las demás opciones de íconos para recordar quitalas porfa.

[images nuevas Juego Memoria de Agente VIE TUR.zip](https://github.com/LeandroBraier/Vietur/files/439282/images.nuevas.Juego.Memoria.de.Agente.VIE.TUR.zip)

Confirmame cuando esté arriba el juego porfa así lo probamos.

abrazo

**Comment by LeandroBraier** [comment]
@valentinsabbath me confirmás para qué hora podría estar subido el juego?

**Comment by ghost** [comment]
Lean en breve se lo paso a mk para que lo suba porque todavia no puedo conectarme al server

**Comment by LeandroBraier** [comment]
Ok, te espero. Gracias!

**Comment by mkreyness** [comment]
me gustaria entender por que no te podes conectar...

**Comment by ghost** [comment]
intento con este comando
 sftp.exe -P 4444 vieturco@comunidad.vietur.com.ar

**Comment by ghost** [comment]
@LeandroBraier estaba teniendo problemas con el juego y es porque iconsapp-sheet1.png no existe sin iconsapp-sheet0.png. O sea faltaria que diseñen este ùltimo. O van a dejar los íconos que están por defecto?

**Comment by LeandroBraier** [comment]
Queriamos dejar uno solo de los dos. ¿No podés renombrar iconsapp-sheet1.png
como iconsapp-sheet0.png y listo?

**Comment by ghost** [comment]
No, porque uno tiene muchas mas imágenes que el otro. O sea que habrìa un faltante de íconos correspondiente al nivel 2 y 3 y asi no corre el juego

**Comment by LeandroBraier** [comment]
Ok, dejame que te lo resuelvo y te lo mando.

**Comment by ghost** [comment]
Otra pregunta, querés que le saque los dados horribles ?

**Comment by LeandroBraier** [comment]
Siii! Mejor!!

**Comment by mkreyness** [comment]
El port 4444 es para entrar por SSH, proba sin ponerle port.
Si no mejor usa un cliente como el Bitvise que hace todo junto, te abre SSH y una sesion de archivos en otra ventana.

**Comment by ghost** [comment]
Con tu programa tampoco. El servidor no me quiere
![image](https://cloud.githubusercontent.com/assets/16599421/18017602/a3902244-6ba8-11e6-9910-402430da7a19.png)

**Comment by mkreyness** [comment]
debe estar mal la password, dejame ver si hubo algun cambio, la que te pase era la inicial de cuando se dio de alta el servidor. Lamentablemente yo la uso pero no la puedo ver (la tiene guardada el programa).

**Comment by mkreyness** [comment]
fijate que te mande password de nuevo por mail. A mi me anda perfecto

**Comment by LeandroBraier** [comment]
@valentinsabbath ya te paso acá la imagen que te faltaba para armar todo. Confirmame cuando esté arriba porfa.

[iconsapp-sheet1.png.zip](https://github.com/LeandroBraier/Vietur/files/440138/iconsapp-sheet1.png.zip)

abrazo

**Comment by ghost** [comment]
Ok justo ahora estoy en la calle en una hora mas o menos va a estar

**Comment by LeandroBraier** [comment]
Genial, gracias! Avisame nomas.

**Comment by ghost** [comment]
Subido @LeandroBraier !

**Comment by LeandroBraier** [comment]
Gracias @valentinsabbath ! Funciona excelente! El tercer nivel es dificil. Me acabo de dar cuenta que nos faltó reemplazar el ciervo por el avión de VIE TUR. Te puedo pasar esa imagen ahora y lo ajustás? Tendría que decir el texto "Clickea sobre el avión para empezar"

Por lo que probé es el único problema.

Además te paso el instructivo para subir a IMG.

**Comment by ghost** [comment]
Oka pásamelo

**Comment by LeandroBraier** [comment]
Gracias Valen!

Acá van

INSTRUCTIVO:

[Instructivo-para-juego-Memoria-de-Agente-VIE-TUR.png.zip](https://github.com/LeandroBraier/Vietur/files/440353/Instructivo-para-juego-Memoria-de-Agente-VIE-TUR.png.zip)

IMAGEN DEL AVIÓN PARA REEMPLAZAR AL CIERVO

[dear-sheet0.png.zip](https://github.com/LeandroBraier/Vietur/files/440363/dear-sheet0.png.zip)

Fijate si queda bien la animación del avión o hay que ajustarle algo.

abrazo

**Comment by ghost** [comment]
Listo!

**Comment by LeandroBraier** [comment]
Perfecto Valen!!! Gracias!!! Buen fin de semana!!

**Comment by LeandroBraier** [comment]
@mkreyness / @valentinsabbath  en la versión de Firefox 44.0000 no anda el juego (supongo que no soporta HTML5 o algo similar). 

¿Podemos agregar un mensaje para aquellos que no les cargue el juego para que actualicen su navegador?

**Comment by mkreyness** [comment]
No puede ser que la version 44 no soporte HTML5, es de enero de 2016.
Capaz no ande con NINGUNA version de Firefox ?

**Comment by LeandroBraier** [comment]
Nop. Ami en la 48 me funciona perfecto.

**Comment by mkreyness** [comment]
para mi que no es un tema de version, capaz esa persona tiene alguna restriccion activada o algun problema particular. @valentinsabbath podes bajarte una version 44 y probarlo ?

**Comment by ghost** [comment]
Dale me la bajo y les aviso

**Comment by ghost** [comment]
@LeandroBraier  me pasas el link que me lleva al juego?

**Comment by LeandroBraier** [comment]
El ID es 50.

Podés usar mi usuario:

usuario=LBraya02
clave=vietur

**Comment by ghost** [comment]
La pàgina está caida o soy yo?

**Comment by ghost** [comment]
@LeandroBraier te podrías fijar si podés entrar a la página ?

**Comment by LeandroBraier** [comment]
Yo puedo entrar sin problemas.

http://comunidad.vietur.com.ar/

Logeado con mi usuario y password.

**Comment by mkreyness** [comment]
una cosa fea que veo es que si no te loggeas y haces click en el slide (para entrar al juego por ejemplo) tira error de un URL que no existe (en vez del correcto para hacer login).
En cuanto pueda lo arreglo, hoy estoy medio a las corridas.

**Comment by LeandroBraier** [comment]
No entiendo bien el error que decís MK. Yo accedo por url directa y me funciona bien. Lo tendré cacheado?

**Comment by mkreyness** [comment]
entra sin loggearte a comunidad.vietur.com.ar, y hace click en cualquier slide.

**Comment by LeandroBraier** [comment]
Ah, ya entendí. Siempre debería ir al login en esos casos.

**Comment by LeandroBraier** [comment]
@valentinsabbath pudiste acceder?

**Comment by mkreyness** [comment]
ya arregle ese bug.

**Comment by ghost** [comment]
Pude acceder y jugar en Firerox version 44

**Comment by mkreyness** [comment]
Como yo me sospechaba, no sabemos cual es el problema de quien no pudo jugar, @LeandroBraier, pero no tiene sentido achacarselo a la version del navegador.

**Comment by LeandroBraier** [comment]
Mmm, ok. Gracias! Es raro. Porque es el cliente que en su misma máquina
probó en Chrome y le anduvo bien y en Firefox no. Es decir que no conviene
poner el pop up no?

**Comment by mkreyness** [comment]
capaz tiene deshabilitada cosas en el Firefox, no veo el sentido de asustar a otra gente por algo que no les va a pasar.

**Comment by LeandroBraier** [comment]
Ok MK. Gracias!!
