### ISSUE TITLE
Sumar puntos por ventas de Agosto en VIE TUR

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#54]
@mkreyness apenas los tengas subidos me avisás porfa?

[Puntos a Sumar en Agosto en Comunidad VIE TUR.xlsx](https://github.com/LeandroBraier/Vietur/files/439372/Puntos.a.Sumar.en.Agosto.en.Comunidad.VIE.TUR.xlsx)

abrazo

**Comment by mkreyness** [comment]
los subo cuando llego tipo 4 en adelante.

**Comment by LeandroBraier** [comment]
Perfecto MK.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Todo subido. Puntos y fichas correspondientes generadas.

**Comment by LeandroBraier** [comment]
Gracias MK!
