### ISSUE TITLE
Trivia que no suma puntos

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#55]
@mkreyness apenas puedas te fijás esta trivia?

http://comunidad.vietur.com.ar/cgi-bin/jugar.pl?id=53

usuario=LBraya02
&clave=vietur

Tiene varios problemas:

1) Respondí todo OK y no me tomó los puntos. Hice 150 y me grabó 0.

2) Además, me permite volver a jugar indefinidamente.

3) Probé dar me gusta, compartir y ver video:
- me gusta suma lo que puse, todo ok
- compartir me lo registra pero me suma 0
- ver video no me lo registra.

Te fijás qué puede estar pasando?

Si resulta ser algo más general habría que probar otras trivias también.

Dale prioridad a esto porfa.

abrazo

**Comment by mkreyness** [comment]
1) vos estas suspendido, no te puede sumar esa cantidad de puntos
2) como no sumaste puntos, te deja volver a jugar.
Dessuspendete y volve a probar.

**Comment by LeandroBraier** [comment]
Perfecto, mil disculpas MK!!

abrazo y gracias

**Comment by mkreyness** [comment]
pero probá, capaz no es eso.

**Comment by LeandroBraier** [comment]
Era era, jeje por eso te digo. Gracias y disculpas de nuevo!

**Comment by mkreyness** [comment]
no hay problema
