### ISSUE TITLE
Sumar puntos por ventas de Septiembre en VIE TUR

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#56]
Van de nuevo!

[Puntos a Sumar en Septiembre en Comunidad VIE TUR.xlsx](https://github.com/LeandroBraier/Vietur/files/493603/Puntos.a.Sumar.en.Septiembre.en.Comunidad.VIE.TUR.xlsx)

Avisame porfa cuando estén arriba.

abrazo

**Comment by mkreyness** [comment]
listo

**Comment by LeandroBraier** [comment]
Gracias @mkreyness !
