### ISSUE TITLE
Juego Colorful Clock para VIE TUR 14/10

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#57]
@valentinsabbath ya tengo todas las imágenes para reemplazar en el juego. Se va a llamar REFLEJOS VIE TUR 

En el instructivo que te paso tenés cuántos puntos suma y cuántas veces se puede jugar. Cualquier duda avisame.

[Imagenes Internas Reflejos VIE TUR.zip](https://github.com/LeandroBraier/Vietur/files/525827/Imagenes.Internas.Reflejos.VIE.TUR.zip)

![2 instructivo reflejos vie tur- juego](https://cloud.githubusercontent.com/assets/6719872/19331159/686c3370-90b9-11e6-93f0-884e4a4b93f4.png)

Esto para el viernes estamos perfectos.

abrazo

**Comment by ghost** [comment]
@LeandroBraier funcionan bien las imágenes.
A qué puntaje querés que sume puntos?

**Comment by LeandroBraier** [comment]
Genial @valentinsabbath ! Fijate que te lo puse en el instructivo. Al superar los 20 puntos del juego suman 300 puntos en la Comunidad. Y pueden sumar hasta 10 veces esos 300 puntos, pero creo que eso es algo que seteó @mkreyness para todos los juegos en general.

**Comment by ghost** [comment]
Lean proba el juego
http://comunidad.vietur.com.ar/vendedores/juegos/Reloj/?usuario=LBraya02&clave=vietur&juego=54

**Comment by LeandroBraier** [comment]
Buen día @valentinsabbath ! No me abre el juego, puede ser? Me da error 404.

**Comment by ghost** [comment]
Ahora si, tenía una letra distinta el otro link
http://comunidad.vietur.com.ar/vendedores/juegos/reloj/?usuario=LBraya02&clave=vietur&juego=54

**Comment by LeandroBraier** [comment]
Funciona bien Valen!!! Ya está subido en el CMS? O como lo subo?

**Comment by ghost** [comment]
Eso haria falta que me lo explique mr. kreynes porque nunca lo hice

**Comment by LeandroBraier** [comment]
@mkreyness como subimos el juego este a la comunidad? Explicale a Valen porfa.

**Comment by mkreyness** [comment]
Tenes que crear un tema y un juego, como siempre, eso lo manejaste siempre vos. El TIPO del juego si es por ejemplo como el de las banderas, tenes que ponerle tipo "Juego HTML5", y en el campo URL del TEMA fijate como esta cualquiera de los otros, tenes que poner en este caso (por lo que veo) /juegos/reloj

**Comment by mkreyness** [comment]
aunque si miro uno que se llama "memoria de agente", veo que el URL tiene la imagen de instructivo y en el campo VIDEO iria /vendedores/juegos/reloj

No se por que el de Banderas esta al reves.

**Comment by ghost** [comment]
@mkreyness me mandás por mail el user y pass del cms?

**Comment by mkreyness** [comment]
Podes acceder con root y lo mismo de siempre igual que en todos los CMS.
Pero esto lo tiene que hacer Leandro, es el que decide en que momento ponerlo activo, que orden darle, que textos ponerle, etc. etc.

**Comment by ghost** [comment]
No puedo entrar con root y lo mismo de siempre en 
/cgi-bin/red.pl

**Comment by ghost** [comment]
listo, ya entré

**Comment by ghost** [comment]
ok, se lo dejo a @LeandroBraier entonces

**Comment by LeandroBraier** [comment]
ok, pasenme el link a poner y yo lo creo.

**Comment by ghost** [comment]
me parece que está caido el server

**Comment by LeandroBraier** [comment]
Muchachos ya está creado el juego pero intento subir las imágenes a los campos de thumbnail e imagen y no funciona. Ya nos había pasado otra vez @mkreyness te acordás?

Les dejo las imagenes acá asi prueban y ven cual puede ser el problema:

THUMBNAIL
![thumbnail reflejos-vie-tur](https://cloud.githubusercontent.com/assets/6719872/19498714/eed01bd0-9568-11e6-85b9-07bebac126a3.png)

INSTRUCTIVO
![instructivo reflejos-vie-tur](https://cloud.githubusercontent.com/assets/6719872/19498723/f3049a6e-9568-11e6-839b-2bdaa1770f90.png)

abrazo

**Comment by mkreyness** [comment]
aca los nombres de archivo que tienen las imagenes no son los originales tuyos, seguro es algo no-safe en el nombre. Ahora yo me los bajo de aca, les pongo un nombre safe y los vuelvo a subir.

**Comment by mkreyness** [comment]
listo.

**Comment by LeandroBraier** [comment]
Pero eran safe! Los chequee y volvi a subir varias veces. Ni tildes ni ñ ni
espacios. Que puede ser no safe que no sea eso?

**Comment by mkreyness** [comment]
espacios en blanco por ejemplo...

**Comment by mkreyness** [comment]
ah, ya dijiste "ni espacios". No se, pero a mi me los tomo sin problema.

**Comment by mkreyness** [comment]
Que nombres tenian ?

**Comment by mkreyness** [comment]
ya lo vi, era un "guion largo medio" que no es el guion normal. 
Cuando se pasa eso al URL sale asi:
THUMBNAILâ€“Reflejos-VIE-TUR.png 

Con basuritas.

**Comment by LeandroBraier** [comment]
aaahhhhhhh fuck. OK. Tendría que pasar el nombre de los archivos por UTF 8
para asegurarme de que sean safe no?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Para mi es algo que te hace la Mac,  No se como hacer para evitarlo, pero si cuando los subis despues haces click en el lugar donde se ve la imagen rota, y le das que abra el URL en otra ventana, ahi te aparece bien en el URL donde esta la basurilla.

**Comment by LeandroBraier** [comment]
ah, buen dato ese MK. Gracias!! Por todo! jeje A vos también @valentinsabbath !! abrazo grande
