### ISSUE TITLE
Estimado de tiempos para Desarrollo de Mails de Cumpleaños en Comunidad VIE TUR

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#58]
@mkreyness necesitamos cotizar tiempos para ofrecerle a VIE TUR lo mismo que tenemos en la Comunidad de Vendedores de Parex-K para los cumpleaños. ¿Me pasarías un estimado de horas tuyas (sin las de Fede)?

**Comment by mkreyness** [comment]
Quedo medio incoherente en ParexK porque por un lado pusimos unos regalos a entregar cada mes, y despues eso se congelo y quedo algo que suma 1000 puntos y mandar un mail.
Cual de esas dos cosas seria ? 
Mira que mucha gente esta sin fecha de nacimiento.
Si es eso, ponele 3 horas mias.

**Comment by LeandroBraier** [comment]
Gracias @mkreyness !

**Comment by LeandroBraier** [comment]
Seria la version puntos nada mas. Sin regalo. Son 3 hs nomas?

**Comment by mkreyness** [comment]
Si
