### ISSUE TITLE
Sumar Puntos por Ventas en Octubre

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#59]
Van más puntos MK! Avisame porfa cuando estén arriba.

[Puntos a Sumar en Octubre en Comunidad VIE TUR.xlsx](https://github.com/LeandroBraier/Vietur/files/553812/Puntos.a.Sumar.en.Octubre.en.Comunidad.VIE.TUR.xlsx)

abrazo

**Comment by mkreyness** [comment]
listo

**Comment by LeandroBraier** [comment]
Gracias MK! Cuando puedas le podés sumar puntos a un usuario en particular? Me lo agregó recién el cliente:

Usuario: FabioAllende 
Puntos a sumar: 517931 

abrazo

**Comment by mkreyness** [comment]
puntos sin dolares ? Son muchos puntos esos, va a tardar un siglo generando fichas de a 100 puntos.

**Comment by mkreyness** [comment]
El que MAS tiene acumulado en todo lo que lleva el sistema, tiene 189600, y eso lo fue adquiriendo de a poco.
517931 todo de golpe va a ser 5179 fichas para ESTE sorteo, obviamente lo va a ganar.

**Comment by LeandroBraier** [comment]
Si, serían puntos forzados en realidad. Me dice el cliente que "es una persona que compra MUCHO pero que no venia sumando puntos y es candidato a ganar el premio anual". 

Dejame que lo chequeo con ellos con esta info que me das y te confirmo.

**Comment by LeandroBraier** [comment]
Solución: sumale los puntos todos juntos el 31 a la tarde, así no figura en el ranking mensual. Con eso está OK el cliente.

abrazo

**Comment by mkreyness** [comment]
Ok por favor recordamelo, me lo voy a agendar para ese dia pero por si acaso tipo 6 de la tarde preguntame si lo hice.

**Comment by LeandroBraier** [comment]
Dale, agendado!

Muchas gracias.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Buen día @mkreyness ! Cómo estás? No te olvides hoy a la tardecita de sumar estos puntitos.

abrazo

**Comment by mkreyness** [comment]
Si, tipo 6, ok ?

**Comment by LeandroBraier** [comment]
Perfecto. Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Listo, ya esta cargado y las 5180 fichas generadas... Este si que tiene todos los numeros comprados...

**Comment by LeandroBraier** [comment]
jajajjaja así es. Muchas gracias @mkreyness !
