### ISSUE TITLE
Mailing de Bienvenida VIE TUR

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#6]
@braulio-evangelisti te paso pedido de mailing de bienvenida genérico para VIE TUR.

Es una adaptación del newsletter que ya hiciste. Te paso captura con los cambios que necesito.

![modificaciones-mailing-bienvenida-vie-tur](https://cloud.githubusercontent.com/assets/6719872/13286110/c04dd126-dadd-11e5-9c71-b97f13891937.png)

Además, en el gif, necesito que cambies la pantalla del menú de juegos por la pantalla actual, ya que cambiamos los íconos (ahora parecen estampillas, están mejor).

abrazo

**Comment by braulio-evangelisti** [comment]
@FAAREIA me pasarias lo ultimo de este news? maqueta o illustrator lo que haya quedado último.

**Comment by braulio-evangelisti** [comment]
![newsletter-bienvenida-d-gif](https://cloud.githubusercontent.com/assets/11272253/13297441/31d47416-db11-11e5-9e1e-cd0673fb6497.gif)

**Comment by LeandroBraier** [comment]
Está perfecto! Pongalo funcional porfa con MK asi ya los mandamos cuando MK
inscriba a la primera tanda.

**Comment by mkreyness** [comment]
yo ya cargue los usuarios, no tenian password, le puse a c/u su nombre de pila como password.
Como les vas a avisar cual es su password si el mailing es generico ?
De todos modos: esperá que descule lo de la bienvenida que no anda antes de mandarlos.

**Comment by LeandroBraier** [comment]
Tenés razón, me faltó ese detalle jeje. No tan pequeño:

@braulio-evangelisti tenemos que agregar nombre de usuario y password de la misma forma que está en el de vendedores, debajo del botón de login automático.

abrazo

**Comment by mkreyness** [comment]
@braulio-evangelisti avisame el URL donde queda esto asi le agrego las variables y lo puedo mandar automatico (o esto iba a ir por mailchimp, @LeandroBraier ?)

**Comment by LeandroBraier** [comment]
No debería ir por mailchimp porque debería salir automático no?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-02-24 18:23 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Y porque contiene info personalizada como user/pass que en realidad no deberiamos darle a MailChimp (me imagino que en este caso no pasa nada, pero con una empresa que tenga protocolos de seguridad etc, no se deberia hacer).
Ok, lo preparo en cuanto sepa donde esta fisicamente el archivo.

**Comment by mkreyness** [comment]
Creo que ya esta solucionado lo de la bienvenida, era un problema del URL al que llamaba la registracion (algo que en vendedores de Klaukol no existe).
Fijate que cuando te das de alta aca te pone 30 puntos, y al dia siguiente si volves a entrar, 5 puntos.
Con la gente que di de alta yo (y que estaba usando para probar) no pasaba porque no venia de la registracion.
Hablando de eso: que hacemos con el tema del mailing, porque en realidad si se registra no deberia ir directo a ingresar a la home sino decirle que le va a llegar un mail y que entre desde ahi, no ? O lo vamos dejando entrar igual ?

**Comment by LeandroBraier** [comment]
Lo dejamos entrar igual no pasa nada. Si seria importante saber cuales
entraron desde el mail y cuales no. Es decir, cuales verificaron su mail.

Podemos tener ese dato MK?

**Comment by mkreyness** [comment]
Tendriamos que poner un URL con algo encriptado entonces, para que si se entra por ahi se marque que el email esta verificado, sin esto constituir un cambio de estado del usuario.
En cambio si entra tipeando DNI y clave no podemos dar por verificado nada, porque el usuario que se autoregistró ya sabe esos datos, no necesita haber recibido un mail.

**Comment by LeandroBraier** [comment]
Exacto. No hay problema. Solo quiero saber si su email está verificado nada
más, lo de si entró o no ya lo puedo saber exportando las actividades
realizadas, verdad?

2016-02-24 19:38 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Claro. Bueno voy viendo eso para cuando mande el mail, todavia no se donde esta el template del mailing.

**Comment by LeandroBraier** [comment]
@mkreyness dos coss importantes:

1) Avisame cuando estén listos y mandame uno de prueba pero igual no los mandes hasta que la Comunidasd no esté lista.

2) Mandale copia de cada mailing de bienvenida a gabriela@vietur.com.ar 

abrazo

**Comment by braulio-evangelisti** [comment]
Para tenerlos al tanto nomas, lo estoy maquetando todavia, hasta ayer ultima hora no habia nada maquetado estaba todo en diseño aun. Apenas este le aviso por aca a Marcelo

**Comment by LeandroBraier** [comment]
Dale, genial. Solo avisaba eso nomás.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-02-25 11:13 GMT-03:00 Braulio Evangelisti notifications@github.com:

**Comment by mkreyness** [comment]
Ok, yo tengo todo lo mio listo, cuando me avises engancho las dos cosas y mando pruebas.

**Comment by braulio-evangelisti** [comment]
@mkreyness cree una carpeta **http://comunidad.vietur.com.ar/_mailing/** para subir la maqueta pero una vez arriba no puedo acceder a los archivos desde el navegador

**Comment by braulio-evangelisti** [comment]
http://209.133.209.166/~vieturco/_mailing/bienvenida-comunidad/bienvenida-comunidad.html

**Comment by mkreyness** [comment]
yo lo veo bien:

http://comunidad.vietur.com.ar/_mailing/bienvenida-comunidad/bienvenida-comunidad.html

**Comment by mkreyness** [comment]
le meto mano para completarle las cosas y te mando uno de prueba @LeandroBraier

**Comment by LeandroBraier** [comment]
Dale, lo espero MK.

**Comment by mkreyness** [comment]
Ah, ojo, aca esta mandando al login para que TIPEE su usuario y contraseña, no a la pagina main.
Si bien me parece perfecto a nivel seguridad (por el tema de que Google no lo indexe), a nivel marcar que vino desde el mail se me complica.
Puedo ponerle que vaya directo a la main ? Si no tengo que hacer algunas modificaciones en el formulario de Login para que traslade la clave especial del mail que estoy mandando.

**Comment by LeandroBraier** [comment]
Directo a la MAIN todo bien.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-02-26 16:10 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
recibiste ?

**Comment by LeandroBraier** [comment]
Recibí muy bien yo. Te paso captura de un solo detalle que ve mal el cliente.

<img width="626" alt="captura de pantalla 2016-02-26 a las 7 38 47 p m" src="https://cloud.githubusercontent.com/assets/6719872/13367013/e97ede00-dcbd-11e5-8f65-af1e5a5cd80e.png">

@braulio-evangelisti sabés qué puede ser?

**Comment by mkreyness** [comment]
Justo es la zona que tuve que tocar para cambiar los URLs, capaz rompi algo.

**Comment by braulio-evangelisti** [comment]
si no es muy complicado mandenme una prueba y reviso bien si es un tema de maquetado o no.

**Comment by LeandroBraier** [comment]
Ok, Brau. Ahi te reenvie la prueba mia.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by braulio-evangelisti** [comment]
Ahí hice lo mismo pero en otro formato, debe ser algo específico del cliente de mails que este usando porque en la todos los dispositivos y plataformas que probé lo veo bien.

**Comment by LeandroBraier** [comment]
Genial @braulio-evangelisti ! Avisale a @mkreyness donde lo modificaste así podemos hacer un nuevo testeo enviado a nosotros y al cliente gabriela@vietur.com.ar

abrazo

**Comment by braulio-evangelisti** [comment]
Actualice sobre el mismo archivo, descargue el viernes el que habia modificado que le agrego las variables y trabaje sobre ese:

http://comunidad.vietur.com.ar/_mailing/bienvenida-comunidad/bienvenida-comunidad.html

**Comment by LeandroBraier** [comment]
Gracias @braulio-evangelisti ! @mkreyness cuando puedas hacé el envío. Si ahora no estás puede ser 16 hs todo bien.

abrazo

**Comment by mkreyness** [comment]
no estuve en todo el dia hoy. Igualmente tenia en mente que esto se iba a mandar el JUEVES, no habia otra cosa pendiente ? Cargar mas gente ? Todavia no las cargue.
A la mañana temprano te mando una prueba que salga directo cc: gabriela, confirmame sobre eso, cargo lo que falta y largo todo.

**Comment by LeandroBraier** [comment]
Buen dia MK! Hoy manda la prueba nomas. La nueva base te la paso hoy abrazo

**Comment by mkreyness** [comment]
ahi salio la prueba.
