### ISSUE TITLE
Mailing para Comunidad VIE TUR. 04/11

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#60]
Buen día @FAAREIA ! Te paso un pedido de maquetación similar a los que venimos haciendo (aunque en este caso tenés tiempo para maquetar el mailing con la menor cantidad de imagenes posibles).

https://mega.nz/#!etNhjazT!p-Q9kl2APiAsExjlkG1qleC6GzqdpMFX6pqH2vrz4Mg

En este caso hay un video linkeado también, que es este:

https://vimeo.com/151764090

En el PSD hay un GIF, pero dado que la lista a la que le vamos a enviar en general no va a poder ver el GIF, reemplacemoslo por una falsa captura de video, que sería esta:

![preview-video-comunidad-vie_tur](https://cloud.githubusercontent.com/assets/6719872/19964895/0d5f80e0-a1a3-11e6-9feb-b289d90f3b75.jpg)

Con que esté para mañana estamos OK. Avisame nomás.

abrazo

**Comment by FAAREIA** [comment]
Necesito el archivo photoshop original, necesito separar fondos, ver tamaños, colores, etc

**Comment by LeandroBraier** [comment]
Perfecto. En el psd que te pase lo tenes. El que pesa 130 mb. Fijate

**Comment by FAAREIA** [comment]
No tiene las capas del archivo, solo tiene 21 capas (que sería los frames) repetidas
Necesito el editable

**Comment by LeandroBraier** [comment]
Uuuhhh ok. Ya lo pido. Perdon!

**Comment by LeandroBraier** [comment]
Acá está @FAAREIA !!

https://www.wetransfer.com/downloads/4f87c836c81ff3c1430c143ffcad5b5120161103180055/490b02376f6de5307a4821b4e42e852a20161103180055/96858a

Tranqui que es para mañana.

abrazo

**Comment by FAAREIA** [comment]
Fijate ahi Lea:
http://comunidad.vietur.com.ar/_mailing/16-11-comunidad/comunidad.html

**Comment by LeandroBraier** [comment]
Está perfecto Fede. Ya puedo copiar el Codigo fuente para armarle un
template en el mailchimp del cliente?

Lo hago yo, solo quiero saber si ya está todo final.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Si esta final lea, igual probalo como siempre

**Comment by LeandroBraier** [comment]
Genial. Gracias!

**Comment by LeandroBraier** [comment]
@FAAREIA si bien en Mailchimp se ve bien, mirá como lo ve el cliente:

![image 1](https://cloud.githubusercontent.com/assets/6719872/20023017/0e91b9f0-a2bc-11e6-9293-ecb97209234a.png)

Le harías los ajustes al html así lo reemplaza en su mailchimp?

**Comment by FAAREIA** [comment]
No encontré el template que habías creado pero cree uno nuevo con el ajuste necesario, debería ir bien ahi. Pruebenlo igualmente.

Abrazo

**Comment by FAAREIA** [comment]
También actualicé el archivo online

**Comment by LeandroBraier** [comment]
Muchas gracias Fede!!! Porfa dale prioridad al newsletter de Klaukol hoy.
Son unos ajustecitos nomas.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
jaja es que lo creaste en el mailchimp nuestro, no en el del cliente. Por eso no lo ibas a encontrar.

Ahi se lo pasé al cliente, te aviso cuando me confirme.

abrazo
