### ISSUE TITLE
Sumar Puntos por Ventas en Noviembre

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#61]
@mkreyness van los puntos de Comunidad VIE TUR de noviembre.

[Puntos a Sumar en Noviembre en Comunidad VIE TUR.xlsx](https://github.com/LeandroBraier/Vietur/files/613946/Puntos.a.Sumar.en.Noviembre.en.Comunidad.VIE.TUR.xlsx)

Avisame cuando estén subidos. Puede ser el martes, todo bien.

abrazo

**Comment by mkreyness** [comment]
Listo, ya estan subidos.

**Comment by LeandroBraier** [comment]
Muchas gracias MK!
