### ISSUE TITLE
Nuevo Juego VIE TUR- Candy de Fin de Año

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#62]
Buen día @valentinsabbath !

Te paso el nuevo juego que tenemos que armar para VIE TUR.

https://wetransfer.com/downloads/9a28b5d6def3dd2791f63d428ab87f2120161214013208/59be9c5ebbe3f9ea7a89868bf689717320161214013208/ec985b

El juego es este:

https://codecanyon.net/item/christmas-match3-html5-game-construct2-capx-leaderboard-api/18924240?s_rank=1 

Necesito que me pases todas las imágenes que se puedan customizar así las diseñamos. abrazo

**Comment by ghost** [comment]
Te paso el zip @LeandroBraier 
[images.zip](https://github.com/LeandroBraier/Vietur/files/652765/images.zip)

**Comment by LeandroBraier** [comment]
Muchas gracias Valen!

**Comment by LeandroBraier** [comment]
@mkreyness hoy voy a estar pasándole las imágenes a @valentinsabbath Vos coordinás con él para activar el tema de los puntos? Serían 300 puntos a partir de pasar el nivel 3.

**Comment by mkreyness** [comment]
Ok. Esta creado el tema/juego en el CMS ?

**Comment by LeandroBraier** [comment]
Aun no! Pensé que lo creaban uds, yo no lo puedo crear no? Decime sino y te
lo creo.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora <http://benteveo.tv>
Móvil 1158717399

**Comment by mkreyness** [comment]
Claro que podes crearlo, esta en el CMS, como todos los otros temas/juegos que siempre creaste vos hasta ahora. Lo que yo necesito es precisamente que este creado para poder a eso agregarle el URL de lo que suba Valentin.

**Comment by LeandroBraier** [comment]
Dale. En un ratito te lo paso.

**Comment by LeandroBraier** [comment]
Listo! Avisenme cualquier cosa.

**Comment by LeandroBraier** [comment]
Se llama Juego Candy VIE TUR y es el ID= 72

**Comment by ghost** [comment]
En qué directorio debería subir el juego?

**Comment by mkreyness** [comment]
siempre dentro de /vendedores/juegos ponele a tu directorio el nombre que quieras (decimelo) y eso lo pongo como URL del juego.

**Comment by ghost** [comment]
@LeandroBraier avisame cuando tengas las imagens

**Comment by LeandroBraier** [comment]
sip, se está demorando un poco, hasta qué hora estás?

**Comment by ghost** [comment]
Estoy hasta las siete

**Comment by ghost** [comment]
Si es urgente me llevo la notebook

**Comment by LeandroBraier** [comment]
Valen, despreocupate. Todavía no me llegan los diseños. Lo hacemos el lunes.

abrazo

**Comment by LeandroBraier** [comment]
Buenas @valentinsabbath ! Cómo va?

Acá te paso las imágenes: 

[images tuneadas Candy Tours.zip](https://github.com/LeandroBraier/Vietur/files/672508/images.tuneadas.Candy.Tours.zip)

Confirmame cuando podamos probarlo al jueguito subido.

@mkreyness el instructivo lo voy a tener más tarde: vos lo subís al server y me pasás la ruta o hay forma de que lo pueda subir yo directamente?

abrazo

**Comment by LeandroBraier** [comment]
@mkreyness acordate de limitarlo a 3000 puntos en total.

abrazo

**Comment by ghost** [comment]
@LeandroBraier no  me dijiste cuántos puntos había que sumar en el juego para que sume puntos a los vendedores. Por otro lado, las imágenes están mal. Fijate que si seleccionas una imagen, la misma se convierte en un boleto. Además debe estar mal el tamaño porque el juego no funciona fluido.
Te paso el link del juego subido para que pruebes.
http://comunidad.vietur.com.ar/vendedores/juegos/navidad/?usuario=LBraya02&clave=vietur

**Comment by LeandroBraier** [comment]
Hola @valentinsabbath ! Si te había dicho. Te había puesto esto: `Serían 300 puntos a partir de pasar el nivel 3.`

2. Decime qué es lo que está mal de las imágenes y pido el ajuste. Yo las revisé y estaban todas OK. No sé qué es lo que puede estar mal.

3. El link que me pasás no me funciona. @mkreyness nos das una mano con esto porfa?

**Comment by ghost** [comment]
No desesperes, todavía no llames a mk.
Proba este link para que veas cómo se comportan las imágenes, es mas fácil que lo veas

http://comunidad.vietur.com.ar/vendedores/juegos/navidad2/?usuario=LBraya02&clave=vietur

**Comment by LeandroBraier** [comment]
Ok. Yo las veo bien a las imágenes. Solo algunas cosas:

1) En la imagen de Loading estamos mal, porque te mandé una imagen que reemplaza esa campana. Lo mismo que en el Favicon. 
2) Hay un instructivo con un texto interno que no me pasaste como imagen. ¿Te puedo pasar un texto en español y reemplazarlo?
3) La tabla de posiciones no me deja ingresar un nickname. Se puede sacar la tabla de posiciones directamente para simplificar?

Lo demás lo veo ok.

**Comment by ghost** [comment]
Con lo de Loading no me doy cuenta cuál imagen reemplaza esa campana. Me la pasás por aca porfa?
El favicon es el que me pasaste. Yo sacaría los dos, el de Facebook  y el de Twitter porque te hacen compartir esto: " My score in CHRISTMAS MATCH3 - 120"
Las imágenes de los íconos están desordenadas, por eso adoptan un comportamiento erróneo para el juego. Ahora te muestro.
El Tutorial, no se por qué no se pasó como imagen pero acá te la paso.

**Comment by ghost** [comment]
Para el **tutorial**, me retracto, pasame el **TEXTO**

**Comment by ghost** [comment]
Aca te paso dos archivos con cuatro imágenes.
Las "ordenadas" son las originales-
Si comparas con las "desordenadas" Fijate que el PLANETA aparece desordenado si lo comparás con el SOL de las imágenes ordenadas. Lo mismo pasa con el TICKET si lo comparás con la bota navideña de las imágenes ordenadas

[imgOrdenadas.zip](https://github.com/LeandroBraier/Vietur/files/673152/imgOrdenadas.zip)

[imgDesordenadas.zip](https://github.com/LeandroBraier/Vietur/files/673154/imgDesordenadas.zip)

**Comment by LeandroBraier** [comment]
Tenés razón. Ahora reviso y pido todos los cambios necesarios.

1. Estoy viendo y tenés razón. Ese no está. Pasame porfa la imagen de la campana así te la paso con el mismo nombre. Por favicon me refiero al iconito que aparece arriba en la pestaña.

2. Te paso el texto del tutorial: 
JUEGO CANDY TOURS
Instrucciones

Demostró tu agilidad en este juego clásico y adictivo con todo el estilo de VIE TUR. Las reglas son muy simples: poner en fila 3 o más elementos idénticos en forma vertical u horizontal en el menor tiempo posible. Son 9 niveles cada uno con mayor complejidad. Si te gusta el estilo Candy Crash, no vas a poder dejar de jugar! Mové los elementos, hace las mejores combinaciones y llegá al final! Ganá 300 puntos pasando el nivel 3. 

Recordá: solo superando el nivel 3 podes sumar los 300 puntos. Jugalo todas las veces que quieras: acumules hasta 3000 puntos

3. Si, sacá todo eso que sobra.

abrazo

**Comment by ghost** [comment]
Te paso las imágenes de las campanas
[Campanas.zip](https://github.com/LeandroBraier/Vietur/files/673166/Campanas.zip)

**Comment by ghost** [comment]
@LeandroBraier la tipografía que se usa en el juego es en mayúscula unicamente y no usa tildes. Asi que:
habría que pasarme el instructivo en modo imágen png y lo agrego ahí

**Comment by LeandroBraier** [comment]
Entendido! Cuando tenga el instructivo entonces te lo paso ya diseñado.

A qué hora viajás?

abrazo

**Comment by ghost** [comment]
Viajo a la madrugada así que no tengo problemas con el horario

**Comment by LeandroBraier** [comment]
@valentinsabbath te paso las imágenes corregidas, el instructivo y los cinco íconos. Decime si ahora queda todo bien:
IMAGENES ORDENADAS FINALES
[Imagenes Ordenadas finales.zip](https://github.com/LeandroBraier/Vietur/files/673373/Imagenes.Ordenadas.finales.zip)

INSTRUCTIVO

![2 instructivo candy tour- juego](https://cloud.githubusercontent.com/assets/6719872/21500504/3f42831e-cc1e-11e6-90af-2ce898776704.png)


ÍCONOS
[ICONOS FINALES.zip](https://github.com/LeandroBraier/Vietur/files/674167/ICONOS.FINALES.zip)



abrazo

**Comment by ghost** [comment]
Proba Lean, abri en modo incógnito asi no te abre imagenes viejas cacheadas
http://comunidad.vietur.com.ar/vendedores/juegos/navidad/?usuario=LBraya02&clave=vietur&juego=54

**Comment by LeandroBraier** [comment]
@valentinsabbath te paso el feedback que hablamos recién por teléfono:

1. En el nombre de la página html dice “Christmas match3” debería decir “Candy Tours”

2. Que pasando el nivel 3 sume los 300 puntos en la comunidad

3. Quitar el botón de “i” que lleva al instructivo en inglés

4. Terminar de quitar la tabla de posiciones en todos los niveles, no solo nivel 1.

5. La imagen "menutext-sheet0" qie dice Fin de Juego no se está mostrando bien en estas pantallas:

<img width="1680" alt="captura de pantalla 2016-12-27 a las 12 49 41 p m" src="https://cloud.githubusercontent.com/assets/6719872/21503770/7d6fcb6e-cc38-11e6-8837-b967b94c71fe.png">
<img width="1491" alt="captura de pantalla 2016-12-27 a las 12 46 46 p m" src="https://cloud.githubusercontent.com/assets/6719872/21503773/803a58b4-cc38-11e6-8248-0fcfae5c4854.png">

Te la paso modificada a ver si funciona.

![menutext-sheet0](https://cloud.githubusercontent.com/assets/6719872/21503763/752044f2-cc38-11e6-8307-cd43bcad4907.png)

abrazo

**Comment by ghost** [comment]
Proba de nuevo como incognito.
http://comunidad.vietur.com.ar/vendedores/juegos/navidad/?usuario=LBraya02&clave=vietur&juego=54

Para mi no es tema de "fin de juego" sino en las estrellas blancas

**Comment by LeandroBraier** [comment]
Te paso feedback completo:

1. OK

2. OK

3. OK

4. Sigo viendo la tabla de posiciones en niveles 2 y 3.

5. Las estrellas están iguales, no cambiamos nada en esas imágenes. Tiene que haber algo más. Fijate porfa si encontrás alguna otra diferencia que pueda ocasionar eso. De diseño no es porque el resto de las imágenes son las originales, no las cambiamos.

**Comment by ghost** [comment]
Ya me di cuenta qué pasa con la imagen.
Esta imagen es un sprite que sirve para dos cosas.
O sea que el "Fin de juego" solo tiene que ocupar el area de "Complete" y no mas que eso.
y "Juego terminado" tiene que ocupar el area de "Game over"
![menutext-sheet0](https://cloud.githubusercontent.com/assets/16599421/21507046/d9d4a09e-cc53-11e6-8b39-c50131cf08fb.png)


en cambio en la rediseñada una sola cosa ocupa las dos areas
![menutext-sheet0](https://cloud.githubusercontent.com/assets/16599421/21507076/291d3abc-cc54-11e6-954b-2a3972e5d7b9.png)

**Comment by LeandroBraier** [comment]
Perfecto! Ya entendí! Excelente Valen.

Acá te paso la imagen definitiva entonces para reemplazar:

![menutext-sheet0](https://cloud.githubusercontent.com/assets/6719872/21507172/d7e58c16-cc54-11e6-9e48-4fea682bd3bb.png)

abrazo

**Comment by ghost** [comment]
Proba el juego otra vez Lean,
lo que no se es dónde va el instructivo

**Comment by ghost** [comment]
Cuando invoco a "/cgi-bin/sumapuntos.pl?juego=" & Browser.QueryParam("juego") & "&usuario="  & Browser.QueryParam("usuario") & "&clave="  & Browser.QueryParam("clave")

me lleva a "Advina Banderas" @mkreyness

**Comment by LeandroBraier** [comment]
El instructivo lo sube @mkreyness siempre. A mi me dan una ruta nomás.

**Comment by LeandroBraier** [comment]
Yo lo sigo viendo igual al juego che Vos lo probaste?

**Comment by LeandroBraier** [comment]
Estoy viendo y no me suma los puntos tampoco @valentinsabbath 
@mkreyness porfa nos das una mano con esto?

**Comment by ghost** [comment]
Yo lo veo diferente
Cerra el browser y volvelo a abrir como incognito
http://comunidad.vietur.com.ar/vendedores/juegos/navidad/?usuario=LBraya02&clave=vietur&juego=54

**Comment by LeandroBraier** [comment]
Ahora si! Quedó perfecto Valen!! Se ve que estaba cacheado en el incógnito también, perdón.

Lo que no veo es que me sume los puntos puede ser?

**Comment by ghost** [comment]
Lo que hago es invocar a un programa de @mkreyness .
Falta que lo adapte para sumar puntos

**Comment by LeandroBraier** [comment]
claro, ahí está la clave. Le voy a escribir por Whastapp.

**Comment by LeandroBraier** [comment]
Está llegando a su sitio vacacional, apenas se instala bien nos avisa. abrazo y gracias @valentinsabbath !

**Comment by ghost** [comment]
Nos vemos @LeandroBraier abrzo!!

**Comment by LeandroBraier** [comment]
abrazo!!
