### ISSUE TITLE
Puntos a sumar en Diciembre VIE TUR

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#63]
Buen día @mkreyness ! Feliz navidad!!

Acá van los puntos de Comunidad VIE TUR de diciembre.

[Puntos a Sumar en Diciembre en Comunidad VIE TUR.xlsx](https://github.com/LeandroBraier/Vietur/files/673020/Puntos.a.Sumar.en.Diciembre.en.Comunidad.VIE.TUR.xlsx)

Me avisás cuando estén subidos porfa?

abrazo

**Comment by mkreyness** [comment]
listo, esta todo subido

**Comment by LeandroBraier** [comment]
Gracias @mkreyness !
