### ISSUE TITLE
Tema Ranking Anual

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#64]
Buenas @mkreyness ! Bienvenido de vuelta!!

Apenas puedas confirmame esto: el ranking anual se actualizó y está vacío porque es 2017. Habrá posibilidad de en ese espacio poner artificialmente al ganador del mes anterior hasta que el ranking se regenere con puntos de este año?

**Comment by mkreyness** [comment]
No se cuando llego, sali hace 2:30hs de Miramar y estamos clavados en la salida de MdQ con algo del micro roto (ni informan).
Si, supongo que se puede forzar artificialmente que muestre de 2016 hasta que haya datos de 2018

**Comment by mkreyness** [comment]
Digo 2017

**Comment by LeandroBraier** [comment]
Dale, perfecto. Le digo al cliente y vamos ganando tiempo.

Que te sea leve MK!! Relazate y goza si puedes... abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora <http://benteveo.tv>
Móvil 1158717399

**Comment by mkreyness** [comment]
listo ya sale asi. Cuando sea febrero si ya va a tomar 2017.

**Comment by LeandroBraier** [comment]
Perfecto MK! Bienvenido!

Consulta: tenemos posibilidad de sumar el año 2016 al lado del texto
Ranking Anual para que se entienda mejor?

**Comment by mkreyness** [comment]
Si, ahi se lo puse fijo en el template, pero hay que acordar de sacarselo el 1-feb.

**Comment by LeandroBraier** [comment]
Excelente MK! Gracias!

Ya le aviso al cliente y te lo recuerdo en febrero.

Abrazo
