### ISSUE TITLE
Video chat tipo webinar para una web 

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#66]
También para la Comunidad VIE TUR, necesitamos implementarle un video chat, como se hace en los webinars. No hace falta que el asistente de VIE TUR vea al usuario, nos alcanza con que el usuario lo vea a él y tengan sonido de ida y vuelta.

Me dice @valentinsabbath que se puede lograr con un protocolo de comunicación muy extendido que se llama "webRTC" pero vos lo tenés que meter en la página. Me calcularías las horas también porfa?

abrazo

**Comment by mkreyness** [comment]
Sorry no lo habia visto. No tengo idea del tema pero meter el frame en la pagina es, como siempre te digo, mas un tema de maquetacion que de programacion.
El asunto es que alguien tiene que HOSTEAR eso, porque lo unico que hace la pagina es conectarse a un canal, pero el canal FISICAMENTE tiene que existir y estar en un servidor. Dudo que Duplika soporte eso.

**Comment by LeandroBraier** [comment]
Pero habria que consultarle y a lo sumo pagar mas no?

2017-01-05 21:26 GMT-03:00 mkreyness <notifications@github.com>:

**Comment by mkreyness** [comment]
no creo que sepan de que estamos hablando. El tema es que por lo que estuve leyendo, no es que realmente haya un server por el que pase el trafico del video, es solo la coordinacion de los usuarios.
Encontre unos que lo dan gratis, pero sabes como son estas cosas, hoy anda, mañana quien sabe.
Lo mejor seria hostear eso nosotros mismos en el servidor, lo cual implica instalar cosas.
Lo que habria que preguntarles es si podemos instalar una aplicacion que corre bajo node.js (y ahi si aclarales para que no se asusten, que es para hacer WebRTC de un video chat en la pagina). El trafico real va de browser a browser.

Ahora: NO SE si puede funcionar sin camara (solo audio). Hay que estudiarlo, y estudiarlo tambien lleva tiempo. Todas las demos que encuentro de WebRTC para iniciar la sesion en Chrome me dicen que "permita" el acceso a la camara, y como no tengo ninguna camara, no me aparece si quiera el popup para permitirlo. 
Y cuando lo pruebo en mi notebook, que SI tiene camara, me pasa exactamente lo mismo, asi que me parece que es algo del Chrome.
No se, me parece que si no tiene otra cosa grosa podria Valentin ponerse a investigarlo para ver si sirve o descartarlo.
SI SIRVE, hay que hacer un par de cosas:
- instalar el programa server en Duplika u otro lado o usar un server externo (dudo que ellos tengan, ya me fije en la pagina)
- integrarlo en la pagina (maquetacion + automatizar un poco el tema del nombre de la sesion basado en el usuario loggeado o algo asi)
Ponele que con un poco de dolores de cabeza, si Valentin se ocupa de investigar todo (seguramente interactuando conmigo, pero eso es esporadico), de instalar el server y dejarlo andando, con 5 horas mias + lo de maquetacion estaria todo integrado.

**Comment by ghost** [comment]
A mi el Chrome para las pruebas de WebRTC me pide que use la cámara y el mic y me funciona perfectamente.
Por lo que estuve viendo, como decís vos, y por lo que explican en el video de Google, la conexión sería P2P entre usuarios (no sirve para conferencias de mas de dos usuarios sin un server).
Hablando rápido, todo aparece en JS, no vi nada de backend al respecto. Estás seguro de que se necesita un server?

**Comment by mkreyness** [comment]
los que yo vi usan algo para coordinar la sesion entre ambos. Pero puede ser que no en todos los casos haga falta, a mi estos encima no me anduvieron.
Por eso digo, requiere un poco de investigacion.

**Comment by LeandroBraier** [comment]
Claro, entiendo. Muchas gracias!

Lo de que no se vea la cámara del usuario no es obligación, si se ven las dos mejor. 

Le aviso a Eze entonces. @valentinsabbath porfa arrancá a investigar esto así ganamos tiempo.

abrazo

**Comment by mkreyness** [comment]
el problema no es "no ver al usuario", el problema es que el software NO FUNCIONE si no hay camara conectada, porque no hay forma, desde el browser, de autorizar la camara, y hasta que no se autorice, el software no arranca.

**Comment by LeandroBraier** [comment]
Entiendo. Pero si hay 1 cámara conectada de 1 de los dos lados anda? O tiene que tener en los dos?

**Comment by ghost** [comment]
eso es lo que tengo que resolver

**Comment by mkreyness** [comment]
Pensalo asi: hay 2 personas, cada una en su maquina, con su browser. El software corre en CADA browser.
Al que tiene camara, le anda.
Al que no tiene camara, EN PRINCIPIO, no le anda, no se puede ni empezar a correr. 
Por lo tanto no hay conversacion entre esas dos personas.

**Comment by ghost** [comment]
Creo que está bien que eso ocurra.  Qué dispositivo que tiene micrófono no
tiene cámara? Hoy en día todos tienen las dos ya sea una Notebook o un
celular.
Y las webcam de PC vienen con mic incorporado.
Me parece raro que alguien tenga solo un micrófono en la pc.


El 6 ene. 2017 11:08 a. m., "mkreyness" <notifications@github.com> escribió:

Pensalo asi: hay 2 personas, cada una en su maquina, con su browser. El
software corre en CADA browser.
Al que tiene camara, le anda.
Al que no tiene camara, EN PRINCIPIO, no le anda, no se puede ni empezar a
correr.
Por lo tanto no hay conversacion entre esas dos personas.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/LeandroBraier/Vietur/issues/66#issuecomment-270909692>,
or mute the thread

**Comment by LeandroBraier** [comment]
Chicos, hablé con Eze y me dijo que estamos ok hasta acá. No sigamos avanzando hasta que el cliente nos de OK. Me quedo con el ticket.

Muchas gracias!

abrazo

**Comment by ghost** [comment]
@mkreyness , leyendo en la web de EasyRTC, para que ande se necesita SSL: "WebRTC clients running on Chrome, can't access cameras or microphones unless they are hosted from SSL servers or on the same machine (it's a browser security constraint)".
