### ISSUE TITLE
Maquetación Nuevo Sistema VT

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#68]
Buen día @FAAREIA ! 

Te cuento que estamos armando todo un nuevo sistema para VIE TUR que requeriría que hagamos un skype con Fede y MK para explicarte y que empieces a maquearlo, ya que es nuestra prioridad hoy en IT.

¿A qué hora pueden hacer los 3 un skype con @mkreyness y @valentinsabbath ?

Mientras tanto te estoy pasando en breve un desglose de maquetaciones necesarias para que te vayas organizando.

**Comment by mkreyness** [comment]
yo hoy tengo una reunion de 2 a 4, fuera de ese horario cuando quieran.

**Comment by LeandroBraier** [comment]
Tendría que ser entre las 11 y las 14 hs entonces.

**Comment by LeandroBraier** [comment]
@FAAREIA va el detalle de lo que hay que realizar. En la call con los chicos vamos a priorizar cual debe estar primero para que ellos puedan comenzar a trabajar lo antes posible.

PRIORIDADES

**5.1: Maquetar el esqueleto de formulario + respuestas

2 y 3: Splash Screen + Inicio con Menú

4: Restyling de la sección de Juegos**

MAQUETACIONES A REALIZAR

1- LOGO de la Comunidad que dragea al Escritorio con la URL logeada pero encriptada

2- SPLASH SCREEN : COMUNIDAD + PUNTOS + INCENTIVO
Texto:  Hola XXXXXNOMBREUSUARIOXXXXXX! Este mes acumulaste ya XXXXX puntos. Segui participando este por mes por el XXXXXPREMIOXXXXX!

Debe incluir un espacio de noticias donde se desplegarán en texto linkeable las novedades de ese día en VIE TUR (que se cargarán via CMS). Debe incluir un link abajo a INFO IMPORTANTE

3- INICIO con Menú: Tiene un header con Nombre de la agencia, Nombre del vendedor, Sus ventas, su cantidad de puntos, puntos a sumar para llegar a un objetivo X.

Hay 6 tipos de usuarios. Los otros 5 tipos de usuarios solo deben decir: Nombre y Tipo de Usuario debajo.

El Menú de Inicio tiene los siguientes botones:

. Productos (lleva a un _blank via link a productos-destacados) 

. Comunidad (lleva a un _blank via link a la comunidad de siempre, pero ya logeada)

. Chat con representante (levanto un pop up de un chat que están preparando MK y Valen)

. Mi Gestión (lleva a una serie de maquetaciones, que es el grueso de este nuevo sistema y te lo desgloso aparte)

. Promociones (por ahora lleva a un _blank via link a productos-destacados) 


. Tipos de cambio: Simplemente despliega un recuadro con diferentes tipos de cambio que maneja el cliente. Eso se carga via CMS al sistema.


4- RESTYLING PÁGINA DE JUEGOS en la Comunidad (pensando que después podamos hacer lo mismo en Comunidad de Vendedores Klaukol y Club de Colocadores)

Seria conveniente separar todas las opciones de dinámicas por categorias tales como
1.	Juegos
2.	Lineas de producto
3.	Videos de destinos
4.	Tutoriales


Pasanos una propuesta de como te parece mejor hacerlo. Se me ocurre una botonera rectangular con estas 4 categorías como botones con imagen y texto y en cada una un mensaje en rojo aclara un número con la cantidad de dinámicas nuevas que hay dentro.

5- PÁGINAS de Formularios e Intercambios de mensajes en Mi Gestión ESTO LO NECESITA MK COMO PRIORIDAD

Esto es lo principal que te tenemos que explicar por Skype. Te desgloso acá solo las páginas a maquetar. El detalle lo vas a encontrar en el documento que te adjunto abajo.

**5.1 Solicitar cotización FORM COTI** 

5.2 Solicitar reserva FORM RESE

5.3 Cuánto debo FORM LIQI

5.4 Emitir mis vouchers FORM VOUC

5.5 Informar pagos FORM PAGO

5.6 Documentacion de viaje de mis pax

5.7 Comentarios FORM CALI

5.8 Buscador 
 
5.9 Mi base de datos


Acá va el documento completo y consolidado para todos:

[Definiciones CONSOLIDADO 23-01.docx](https://github.com/LeandroBraier/Vietur/files/743167/Definiciones.CONSOLIDADO.23-01.docx)

Leelo porfa antes de la call asi te sacamos todas las dudas.

6- PANEL DE CONTROL SUPERVISOR

7- SISTEMA DE NOTIFICACIONES VIA MAIL

8- LOGIN PROPIO PARA EL SISTEMA

abrazo

**Comment by mkreyness** [comment]
Fede aca esta el link con la "zona draggeable" pero invisible funcionando:

/vendedores/test.html

si seguis las instrucciones, vas a ver que te genera en el escritorio un acceso directo que se lama "login.html", obviamente va a haber que buscar la forma de que salga un nombre mejor, ya que el verdedero URL va a ser un chorizo largo y feo, y con algun favicon o algo forzarle a que tenga aspecto de VT, porque asi como lo pone el browser no es lo mejorcito.

**Comment by LeandroBraier** [comment]
Buen día @FAAREIA ! Cómo estás?

Cuando calculás tener el diseño de lo que son los primeros formularios y respuestas?

No te olvides que antes de maquetar el cliente nos tiene que aprobar los diseños.

abrazo

**Comment by FAAREIA** [comment]
A ver si voy entendiendo todo, el diseño podría ser algo asi tipo panel de control.

![vietur---panel-de-control](https://cloud.githubusercontent.com/assets/6184969/22292623/eb64b378-e2ea-11e6-971f-7339c64ee11d.png)

**Comment by LeandroBraier** [comment]
Va por ese lado la diagramación. Qué decís MK?

Para mi mientras más parecido a esto de ML mejor:

<img width="1282" alt="captura de pantalla 2017-01-25 a las 11 21 42 a m" src="https://cloud.githubusercontent.com/assets/6719872/22292847/076bf300-e2ec-11e6-8bc5-105f2293538e.png">

**Comment by FAAREIA** [comment]
Repaso lo que voy entendiendo:

## Pantallas

- Login
- Registro (uno aparte del de la comunidad?)
- Inicio (no se especifica como van a ser los formularios para reportar cosas)
- Splash screen
- ~~Informaciones importantes (no se especifica categorías de información ni nada)~~
- Mi gestion - Solicitar cotización
- Mi gestion - Solicito reserva
- Mi gestion - Cuanto debo
- Mi gestion - Emito mis vaucher
- Mi gestion - Informe de pago
- Mi gestion - Documentacion de viaje de mis **pax**
- Mi gestion - Comentarios de calidad y atención
- Mi gestion - Buscador de cotizaciones, reservas, etc
- Mi gestion - BASE DE DATOS Y FORMULARIO DE VISUALIZACION (no es lo mismo que la anterior?)
- Panel de control supervisor

## Comunidad
- Restyling sección juegos

**Comment by LeandroBraier** [comment]
Todo lo que es mi Gestión está desglosado bien. 

Sumaste un registro aparte de la Comunidad que me parece OK, faltaba eso, pero es ultima prioridad.

Informaciones importantes va junto con la pantallas de Inicio. Son frases de actualidad. Tipo videograph de abajo de un noticiero ponele. Solo texto.

Supervisor Tipos de Cambio no hace falta. Eso va por CMS. 

Te faltan 2 cosas:

RESTYLING PÁGINA DE JUEGOS 

SPLASH SCREEN

El punto 1, que es el Logo, lo hacés vos o lo pido a Diseño mejor?

No te olvides de las prioridades:

**5.1: Maquetar el esqueleto de formulario + respuestas

2 y 3: Splash Screen + Inicio con Menú

4: Restyling de la sección de Juegos**

**Comment by FAAREIA** [comment]
El logo mejor si lo hace Diseño, es algo que me frenaría mucho todo y más si el cliente empieza a dar vueltas.

- Con respecto a los formularios van a salir rápido ni bien tenga ya definido el diseño general.
- ¿A que llamas respuestas? Sería la pantalla en que podes ver el formulario enviado y las respuestas del mismo?
- ¿El splash screen no sería un bloqué emergente sobre la pantalla de inicio?

**Comment by mkreyness** [comment]
El formulario es parte de un flujo de mensajes. No necesariamente el INICIO del mensaje.
Lo que hay que manejar conceptualmente son conversaciones, pueden o no empezar con un formulario, se pueden ir incorporando formularios durante su curso. Como te dije el otro dia, para mi los formularios son mas como "attaches inteligentes" a una ida y vuelta de mensajes.
Tiene que haber una interface que permita ver las conversaciones, entrar a una de ellas, que te lleve al ultimo mensaje recibido o emitido y te permita contestarlo. Algunos tipos de usuarios van a poder attachar nuevos formularios, otros podran solo mirar los que la conversacion ya trae attachados. 
Cuando digo "inteligentes" es porque tienen campos editables con algo de validacion, y otros campos libres, pero no es una "hoja en blanco" para poner cualquier cosa. Tienen formato.
Diferentes usuarios van a ir interviniendo a lo largo de la conversacion, va a haber criterios por los cuales gente que no habia participado de repente le llega una notificacion para "meterse" en la conversacion. Eso tiene que ver justamente con que se haga referencia a ellos en algun formulario, o a su sector.

La logica del sistema hara que cuando se agregue cualquier mensaje a una conversacion, el usuario "originante" (el vendedor), esto sea notificado por mail.
No tengo todavia claro si a los otros usuarios (los internos de VIE TUR) vamos a notificarlos por mail o mas bien tendrian que aparecerle en pantalla algun tipo de alertas de que tiene conversaciones en las que participar.

Lo que yo necesito que maquetes primero es esta pantalla de "conversacion", que permita ver una lista cronologica de mensajes de una conversacion dada, con sus formularios attached. En el renglon del mensaje los attaches iran con iconitos, supongo. Al tocarlos se abriria el formulario. Tendria que haber alguna forma simple de "agregar" un formulario en un mensaje.
Los puntos del menu esos que dicen "Nuevo COTI", en principio yo entiendo que serian para iniciar conversaciones NUEVAS, en el caso del vendedor, pero no me convencen mucho para que los usuarios internos 'respondan', porque ahi primero hay que seleccionar sobre que conversacion responder.

**Comment by FAAREIA** [comment]
Ok, me queda más claro. Lo que se podría hacer entonces es que en vez de crear "Formularios" uno cree una conversación y ahi decide si adjuntar o no un formulario, habiendo varios tipos para elegir. ¿Qué dicen?


![vietur---panel-de-control](https://cloud.githubusercontent.com/assets/6184969/22334735/967599b0-e3ba-11e6-91ce-e88a6cbdc058.png)

**Comment by LeandroBraier** [comment]
Yo lo veo OK. Solo que no pongamos Dashboard sino Inicio. Nada de palabras
en inglés.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora <http://benteveo.tv>
Móvil 1158717399

**Comment by mkreyness** [comment]
Para mi hay 3 niveles: lista de conversaciones, una vez que elegiste una, el contenido (lista de mensajes) pero tenes que poder tambien elegir un mensaje y ver su contenido, o agregar uno nuevo.
Ahi es donde entran a jugar los formularios. Cuando estas escribiendo un nuevo mensaje dentro de una conversacion (y un caso particular es el PRIMER mensaje, que crea la conversacion) te tiene que permitir adjuntar formularios, que tambien completarian en ese momento. 
El que lee el mensaje (sin pasar por la lista de conversaciones/lista de mensajes, tiene que aparecerle directo en el referenciado por el link que recibio por mail o la notificacion que le aparecio en pantalla) tiene que ver el contenido del mensaje con los formularios (tiene que clickear en el icono de cada formulario para que se abra con todo su contenido). Como si fueran attaches.

**Comment by FAAREIA** [comment]
Ahi va el diseño de la pantalla básica de una conversación

![vietur---panel-de-control](https://cloud.githubusercontent.com/assets/6184969/22384143/cbd28fae-e4ab-11e6-9c0c-bb902f267a58.png)

**Comment by mkreyness** [comment]
O sea estilo whatsapp web, esta bueno, todos ya conocen como funciona eso.
Y en algun lado tendria que haber un clip para agregar attaches al renglon siendo editado. Eso es importante tambien: los attaches REALES, no se si lo mencionamos. Tarde o temprano se van a adjuntar scans o pdfs de objetos "externos" al sistema digamos, no solo los "formularios inteligentes'.
No se en tal caso si mas bien esos attaches serian PARTE del cuerpo de un formulario, pero igual me parece piola que se puedan agregar sueltos aca. 
Tipo "vino un cliente y me trajo esta cotizacion que le hicieron en otra agencia, mira" y le attacha un scan.

**Comment by mkreyness** [comment]
Lean, que habria en "Mi Gestion" ? Una cosa mas ordenada por numero de cotizacion/reserva, no ?

**Comment by LeandroBraier** [comment]
No, en Mi Gestión está todo el sistema. Nunca hablamos de una sección de "conversaciones". Los objetos que tiene conversaciones dentro son cotizaciones. Eso está en el DOC. 

Me encanta la diagramación que ofrecés Fede, pero necesito que el contenido de la misma sea el que está en el doc. No hagamos nada por fuera de ese Doc porfa porque nos vamos de presupuesto. Las secciones están claras ahi.

**Comment by mkreyness** [comment]
Estamos medio empantanados acá, porque lo que dice en el menu de "Mi Gestion" pareceria que fueran todas formas diferentes de INICIAR una conversacion, aunque no la quieras llamar asi.
Cotizacion es solo UNA de las cosas que dice "Mi Gestion". Yo entiendo que se podria arrancar directamente desde una reserva, por ejemplo, pero si el tipo ya venia conversando, y recibió la respuesta a la cotización, la reserva deberia en tal caso poder arrancar desde la MISMA conversacion que se inicio en "Solicitar Cotización".  O sea, continuar el hilo una conversacion previa. Si solo le ofrecemos formas de ARRANCAR una conversacion, no tiene como continuarlas.
Por eso Fede puso el item "Conversaciones", porque es donde lo vamos a llevar al tipo cuando entre por la notificacion.
Aunque sea dentro de "Mi Gestion", pero tiene que haber una forma de ver lo hablado ANTES, no solo empezar cosas nuevas.

**Comment by LeandroBraier** [comment]
Si. Para eso está el Buscador dentro de mi gestión.  Se busca por id de
cotización o file si la reserva ya está ingresada al sistema de vie tur.
Esto está contemplado en el doc. Leanlo bien que está.  Cumplamoslo lo mas
posible salvo que haya un impedimento o un cambio real que hacer.  El
término conversación no significa nada dentro del sistema de vie tur.

**Comment by mkreyness** [comment]
Que te parece esta idea revolucionaria: todo lugar donde Fede o yo hayamos dicho "conversacion" reemplazalo por la palabra "gestion". 
Porque tampoco hay algo muy claro en el sistema de VIE TUR que se llame "gestion".
La gestion no es el formulario en si. Una gestion atraviesa diferentes formularios, hay como un hilo conductor, que no tiene nombre.  Pensa que lo que estan reemplazando son (uff no se que palabra usar) "intercambios de ideas" entre el vendedor y el representante, que actualmente son telefonicas o por mail. Si restringimos a que sea solo un ir y venir de formularios sin un minimo texto humano, se va a volver algo extremadamente desagradable de usar.
Por ejemplo, alguien podria escribir "aca te mando casi todo lo que me pediste, hay un par de cosas que todavia estoy averiguando, pero anda mirando esto", y adjuntar el formulario. El otro podria contestarle "Gracias, pero lo necesito todo junto".  Tiene que haber ese tipo de "comunicacion ?" alrededor de los formularios.

**Comment by LeandroBraier** [comment]
Buen día Revolucionarios! Cómo andan?

Insisto una vez más: están repensando cosas que ya están resueltas en el Doc. Me parece que siguen sin leerlo en detalle o sin entenderlo bien. Si tienen dudas consultenme.

En la numeración del doc está claro como es el menú. Se los resumo acá basado en la diagramación de Fede para más claridad. Sería así:

**Primer menú desde la izquierda:**

1. Inicio
2. Productos 
3. Comunidad 
4. Chat con un representante
5. Mi gestión
6. Ver Tipos de Cambio 

ACLARACION DE CADA UNO
1. Inicio lleva a Splash Screen
2. Productos lleva a link de productos en la web del cliente
3. Comunidad lleva a la Comunidad de siempre pero ya logeada
4. Chat: Abre un pop up para video chat
5. Mi gestión: abre toda la lista de formularios posibles, buscador y dentro de esto todo lo que estamos llamando informalmente conversaciones
6. Ver Tipos de Cambio: muestra una página de texto con info que el cliente sube por CMS.

**Segundo menú desde la izquierda, es decir, lo que aparece al clickear en "Mi gestión"**

1. Solicitar cotización (dentro va el formulario y todas las conversaciones que se dan, que son formularios subsiguientes pero de solo un campo)
2. Solicitar reserva (dentro va el formulario y todas las conversaciones que se dan, que son formularios subsiguientes pero de solo un campo)
3. Cuanto Debo (idem anterior)
4. Emitir mis vouchers (idem anterior)
5. Informo el pago (idem ant)
6. Documentación de viaje de mis pasajeros (aparece un buscador que trae los attachs que el cliente subió para cada reserva)
7. Comentarios (formulario de 1 campo con comentarios)
8. Buscador 
9. Base de datos y formulario

Confirmenme si ahora queda más claro porfa.

En cuanto a diseño Fede todavia no lo adaptaste a la estética del cliente no?

abrazo

**Comment by mkreyness** [comment]
No difiere de lo que ya hablamos. Lo unico que para mi conceptualmente una conversacion "pasa" por los distintos puntos, viene de una cotizacion, se incorpora la reserva, luego pide los vouchers, y no se pierde el hilo.
Asi como esta planteado pareceria que el tipo tiene que empezar con un formulario nuevo cada paso, perdiendo todo el rastro anterior. Todo suelto, desconectado. Si no como haces para decir que la reserva es sobre una cotizacion previa ?

Creo que lo que mas nos aclararia es saber que va en "Buscador", tal vez se parezca bastante a lo que Fede planteo como "Conversaciones", con un par de filtros.

**Comment by LeandroBraier** [comment]
Exacto MK! Eso ya está pensado en el buscador. Lo que dice el doc es:

> Permite buscar cualquier información a través de número de ID, ID/File ,  nombre de pasajero, vendedor/agencia , agencia, etc etc. Deberia ser posible parametrizar los conceptos de búsqueda conforme el tipo de usuario de que se trate ( niveles )

Yo me imagino un buscador lo más parecido a Google posible pero que en lugar de decir "Search Google or type URL" diga "Buscar ingresando ID o File, Nombre de Pasajero o Agencia." Los resultados se mostrarían por ID y dentro de cada ID podrían desplegarse en un subnivel las conversaciones tal y como las diseñó Fede dentro de su sección "Conversaciones"

En cuanto al resto, lo que les pasé "no difiere tanto" pero "difiere" de lo que está en la diagramación de Fede. Le tengo que pasar al cliente la diagramación con el diseño cuanto antes para que lo apruebe y podamos avanzar, por lo cual lo fundamental es que no difiera de lo convenido con él.

abrazo

**Comment by mkreyness** [comment]
Y se tiene que poder buscar texto libre que se haya escrito dentro de los comentarios.
Lo que Fede planteo fue que de cada conversacion que cumpla el criterio, se muestra "como en Whatsapp" fecha hora y lo ultimo que se dijo (a eso habria que agregarle los datos identificatorios que quepan), si lo seleccionas te muestra al lado la conversacion completa, con los formularios que venga arrastrando.
Vos decis que en realidad la conversacion no existe sino que son textos libres que van en cada formulario, pero yo eso lo veo muy incomodo de leer. Tener que abrir el formulario para ver el texto ?
Para mi ese texto de comentario tendria que estar "afuera" del formulario, el formulario ademas va a tener campos de texto libre para escribir lo que quieran, pero el "dialogo humano" tiene que estar a nivel de la conversacion. Asi como por ejemplo la fecha, esta bien que dentro del formulario habrá seguramente una fecha, pero tambien es importante verla afuera, para ordenar y ubicarse temporalmente,

**Comment by mkreyness** [comment]
Las "Agencias", vamos a tener una tabla o algo ? Porque hoy en dia en la comunidad hay un dato de numero de agencia o algo por el estilo que no se valida contra nada, y que c/u la puede cambiar a gusto.

**Comment by LeandroBraier** [comment]
Lo de AGENCIA dejemoslo en un segundo plano por ahora. En principio tomemos
ese dato del formulario ingresado por el usuario, no de nuestra base.

CONVERSACIONES En cuanto a conversaciones me expresé o me entendiste mal.
Lo que yo digo es lo mismo que vos. Toda conversación comienza con el
Formulario correspondiente que pasó el cliente y después se convierte en
whatsapp encadenado como vos dijiste. ACLARACIÓN: A lo que me refería es a
que, para poder escribir un nuevo comentario dentro de una conversación, lo
que usamos es en definitiva un formulario que solo tiene un campo de texto.
Solo a eso me refería.

BUSCADOR En cuanto a buscar texto libre, yo no lo haría. Te explico por
qué: sé por una cierta experiencia (que vos también seguro tenés mucho más
y me podrás desburrar) que un buen buscador es difícil de hacer y requiere
conocer mucho al usuario y seguir su comportamiento. Para hacer más fácil
yo solo permitiría buscar solo por esos datos que les pedí.

Si uds quieren que se pueda buscar por Texto Libre y les parece que no va a
llevar más tiempo de desarrollo y ajustes, tratemos de incorporar el
buscador de Google o algún buscador ya previamente seteado para eso. Si va
a llevar más tiempo dejemoslo para versión 2.0 No quiero que nuestro
buscador dé demasiados resultados que compliquen tanto la experiencia de
usuario como el tráfico en el sitio.

abrazo

2017-01-30 9:31 GMT-03:00 mkreyness <notifications@github.com>:

**Comment by mkreyness** [comment]
y despues esta el punto ese de "Base de Datos", que en realidad es todo lo contrario a una base de datos, es un repositorio de documentos. Eso esta accesible solo para los usuarios internos de VIE TUR, no ?

**Comment by mkreyness** [comment]
En general cuando hablamos de formularios siempre tienen como una cierta "formalidad", un numero, una fecha, un tipo, etc. Para mi esta bien que pueda haber un tipo de formulario que sea "Texto Libre", por si alguien quiere presentar (o tienen que mandarle al vendedor) un texto pero, "protocolizado", digamos.
Pero para decir "Y cuanto seria si en vez de en tren van en avion?" yo no lo protocolizaria.
Me explico ? Son como dos niveles, uno mas formal, que puede existir, pero uno mucho mas informal que es el que le da fluidez.
Si no, van a hacerlo por mail, whatsapp o telefono. Si le haces al vendedor INCOMODO hacer una pregunta, no la va a hacer por ahi y listo.

**Comment by mkreyness** [comment]
En realidad lo que tenemos en el usuario de comunidad se llama "Legajo", eso es lo mismo que agencia, no ?

**Comment by LeandroBraier** [comment]
Marce, me seguís entendiendo mal. Obvio que va a haber texto libre. Los mensajes de ida y vuelta son texto libre como vos decís. Punto.

Yo estaba hablando del Buscador. Específicamente en el campo de búsqueda del buscador, prefiero que el usuario no pueda buscar dentro de la info ingresada en ese texto libre.

BASE DE DATOS

Es para todos los usuarios. Es como el buscador pero automáticamente te muestra un listado de datos organizados en Tabla. Como era la tabla de ventas del famoso Torneo de Potenciados que hicimos en 2015 te acordás?

**Comment by mkreyness** [comment]
Si, no lo decia por la parte del buscador sino que "hacer un comentario" era ingresar a un formulario con un campo de texto libre.
Creo que el problema es que estamos usando la palabra "formulario" para dos cosas.
Una cosa es un formulario de HTML, eso no me preocupa y siempre esta implicito en cualquier lugar donde se ingrese algo.
Cuando yo hablo de formularios en esto me refiero a los "COTI", "RESE", etc. esas cosas tipificadas y con un formato definido. Formularios "preimpresos" digamos.

Base de datos:
pero la tabla de ventas era una estadistica, fijate  lo que dice la definicion de "Base de datos", dice que es un conjunto de mails, documentos de pasajeros, en definitiva una bolsa de gatos, no una base de datos.

**Comment by LeandroBraier** [comment]
Pero "esa bolsa de gatos" es la que ellos usan para ver todas las compras que le están haciendo a VIE TUR. La necesitan. No va a ser un listado tan largo, no te preocupes. Si te parece que va a ser mucho podríamos poner Filtros, pero lo que ellos quieren es eso.

**Comment by mkreyness** [comment]
Es que no entiendo el formato. Te podrian dar una muestra de como lo quieren ver ? Yo entiendo que es una carpeta de archivos sueltos.

**Comment by LeandroBraier** [comment]
Yo me lo imagino como un excel que alista los ID. En cada columna suma una
cosa y, si hay archivos,en dicha columna hay un link para los archivos que
sean (voucher, factura, etc)

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora <http://benteveo.tv>
Móvil 1158717399

**Comment by mkreyness** [comment]
que podrian ser muchas columnas en el mismo ID

**Comment by mkreyness** [comment]
O sea, es como el buscador pero a razon de 1 renglon por formulario ? Es un listado de formularios ?

**Comment by LeandroBraier** [comment]
Exacto. Pero recordá que si hay más de un formulario ingresado para un mismo ID van en la misma fila. 

Una vez que presentemos la diagramación general y la aprueben mandamos esto en diseño para que lo aprueben también. @FAAREIA a qué hora vamos a tener un diseño para mandar?

abrazo

**Comment by LeandroBraier** [comment]
@FAAREIA es importante hoy mandar avances porque venimos muy atrasados, se nos fue una semana y no entregamos nada de diseño.

**Comment by FAAREIA** [comment]
Ok, ahora en un rato subo imágenes.
El logo ya lo tiene?

**Comment by LeandroBraier** [comment]
Gracias @FAAREIA !

Por ahora usemos el mismo que veníamos usando de Comunidad VIE TUR. La idea es que todo se perciba como parte de lo mismo.

DISEÑO: Estamos trabajando en agregarle a ese logo de Comunidad VIE TUR un grosor que hable de algo más software, no solo logo web, y además sumarle un tag abajo que diga algo de "de escritorio" o algo así. Como lo ves?

**Comment by FAAREIA** [comment]
Lo que me parece es que es tosco iniciar una conversación desde diferentes links, para mi habría que crear una conversación y ahi definir si queres adjuntar un formlario o un archivo o simplemente escribir. Más simple.

![01](https://cloud.githubusercontent.com/assets/6184969/22430590/7d3e05b4-e6ed-11e6-95df-5ac45e068ee0.png)
![02](https://cloud.githubusercontent.com/assets/6184969/22430829/39490588-e6ee-11e6-9f2c-bd1ffef3ed34.png)
![03](https://cloud.githubusercontent.com/assets/6184969/22430591/7d462c4e-e6ed-11e6-91e2-ad4801f73246.png)

**Comment by LeandroBraier** [comment]
@FAAREIA está bueno el diseño pero seguís sin leer el documento con atención. Te llamo y te aclaro así ya lo modificás y podemos mandarlo.

**Comment by LeandroBraier** [comment]
Fede como va? Cuando tenemos los diseños?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora <http://benteveo.tv>
Móvil 1158717399

**Comment by FAAREIA** [comment]
Ahi sumé la pantalla inicial y la segunda inicial de mi gestión que ya tiene el entorno del panel de control asi el usuario ya se va acostumbrando a que para usar todo lo de mi gestión, tiene que usar esa interface.
También le agregué el buscador, que no esta 100% claro en el doc, a la pantalla ex-conversaciones.

![0](https://cloud.githubusercontent.com/assets/6184969/22479104/50c65426-e7cb-11e6-8b6c-813cb4498b66.png)
![1](https://cloud.githubusercontent.com/assets/6184969/22479105/50f5a8a2-e7cb-11e6-80ef-a6d41dcb4e15.png)
![2](https://cloud.githubusercontent.com/assets/6184969/22479107/50fb6ec2-e7cb-11e6-9c8b-e07577c17ae5.png)
![3](https://cloud.githubusercontent.com/assets/6184969/22479106/50fb59aa-e7cb-11e6-9fac-eae8b3e9b1a8.png)
![4](https://cloud.githubusercontent.com/assets/6184969/22479108/50fcb5ac-e7cb-11e6-8a81-687096150120.png)

**Comment by LeandroBraier** [comment]
@FAAREIA muchas gracias!!

Voy a pasar los 4 menos el de adjunto porque confunde. El formulario nunca es un adjunto. Cuando elijo la opción "Solicitar cotización", por ejemplo, el formulario es lo primero que me tiene que aparecer. Después puede quedar como adjunto en el sistema pero para el usuario es el punto de partida de la conversación, no un adjunto.

@FAAREIA @valentinsabbath Y @mkreyness EL CLIENTE (de ahora en más) me confirmó que tiene Google Alerts para el nombre de su marca, así que no volvamos a usar el nombre del cliente en estos ISSUES ni en los otros en los que trabajemos porfa. abrazo

**Comment by LeandroBraier** [comment]
@FAAREIA estaba repasando y me parece que no va a funcionar así. Te paso feedback así lo corregís para mañana y lo pasamos bien.

SPLASH SCREEN: La veo muy apagada, hay que llamarles más la atención a los usuarios. Tenemos que convercerlos de que usen el sistema. Hacelo un poco más colorido y con más destaque de los botones (son grises son fondo gris) con fuentes más grandes. Los íconos de chat, mi gestión y tipo de cambio no dicen nada. Buscá algunos más directos que ayuden a entender la función. Por ejemplo, en chat un globo de diálogo, en Mi gestión dos personas intercambiando hojas, no las hojas solas amontonadas.

MI GESTIÓN: Se ven como 9 botones dispersos en una mesa, cuando deberían verse más como una secuencia. Me parece que son 3 filas de botones que tienen cada línea algo en común. La primera fila responde a pedidos hacia el representante VT. La segunda fila responde a búsqueda de información ya almacenada. La tercera fila es una mezcla de las dos: comentarios es pedido a representante y las otras son búsqueda de información. FIjate si podés ordenar por colores algo que ayude más a la lectura en ese sentido.
En cuanto a los íconos, fijate si podés mejorar el de Reserva, Cuanto Debo, Emitir mis Vouchers, Informo el Pago, Comentarios y Base de datos. Me parece que los íconos que elegiste o bien no ayudan a entender o son símbolos que estamos acostumbrados a ver para otra cosa (la ruedita de la base de datos remite a Configuración.

Las demás están bien. Corregí estas dos para mañana porfa y las mandamos. abrazo

**Comment by FAAREIA** [comment]
Ahi van los cambios lea.

- El único ícono que no cambié fue el del voucher ya que me parece correcto, si queres decime otro concepto que tengas en mente y busco otro ícono.
- El ícono de comentario lo simplifiqué pero sigue siendo un globo de diálogo.
- La pantalla con el título adjunto si queres le cambio el título o le saco la opción de adjuntar un formulario de cotización. Tengo entendido que se podría hacer eso y en este caso no iniciaria una nueva "conversación"

![0](https://cloud.githubusercontent.com/assets/6184969/22510778/f8f467cc-e871-11e6-913d-501d616408af.png)
![1](https://cloud.githubusercontent.com/assets/6184969/22510779/f8f6acf8-e871-11e6-82ef-d14a0d41a8fc.png)
![3](https://cloud.githubusercontent.com/assets/6184969/22510780/f8ff527c-e871-11e6-92f0-e00f38d55f53.png)

**Comment by LeandroBraier** [comment]
Excelente @FAAREIA ! Ahora si perfecto. muchisimas gracias!
