### ISSUE TITLE
Cargar Puntos Enero Comunidad

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#69]
@mkreyness te paso los puntos de siempre para subir.

Avisame porfa cuando estén arriba.

[Puntos a Sumar en Enero en Comunidad VIE TUR.xlsx](https://github.com/LeandroBraier/Vietur/files/732407/Puntos.a.Sumar.en.Enero.en.Comunidad.VIE.TUR.xlsx)

abrazo

**Comment by mkreyness** [comment]
pero esta diferente a otras veces, no figuran los dolares, solo los puntos, no importa ?

**Comment by LeandroBraier** [comment]
No importa. Total vos no ingresabaa los dolares no?

**Comment by mkreyness** [comment]
Si, yo siempre los ingrese, pero no los use para nada. Bueno paso esto asi con $0 dolares, ok ?
Lo que digo es que si el dia de mañana quieren ver la suma de dolares o calcular algo nuevo en base a eso, estos no van a sumar.

**Comment by LeandroBraier** [comment]
Si, no hay problema. Gracias!

**Comment by mkreyness** [comment]
Listo todo entonces.

**Comment by LeandroBraier** [comment]
Gracias!
