### ISSUE TITLE
Actualización Bases y condiciones VIE TUR

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#7]
@FAAREIA cuando puedas tranqui necesito que ajustes las bases y condiciones de VIE TUR.

[Bases y condiciones Comunidad VIE TUR .docx](https://github.com/LeandroBraier/Vietur/files/157728/Bases.y.condiciones.Comunidad.VIE.TUR.docx)

abrazo

**Comment by LeandroBraier** [comment]
Pequeño agregado de texto para el final de todo de la bases, la parte en cursiva:

_El personal de VIE TUR, sus representados, proveedores, representantes y demás personas vinculadas a VIE TUR podrán capacitarse y competir pero no podrán acceder a la premiación en ninguna de sus formas la que solo queda reservada para el personal de las agencias de viajes_

Confirmame porfa cuando esté todo actualizado. abrazo

**Comment by braulio-evangelisti** [comment]
Hecho. Chequear por favor que no tengo acceso al sitio registrado, solo a la maqueta en el directorio raiz

**Comment by LeandroBraier** [comment]
Perfecto Brau! Gracias!

Te paso acceso para la próxima:

LBraya02

password: vietur

**Comment by braulio-evangelisti** [comment]
Que lindo saliste en la foto de perfil jajajaja

Gracias por el user.

**Comment by LeandroBraier** [comment]
jajaja Gracias gracias. Mucho gym

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Una vez más @braulio-evangelisti Aparentemente esta vez es versión final:

[BASES Y CONDICIONES 7 mar 16.docx](https://github.com/LeandroBraier/Vietur/files/161747/BASES.Y.CONDICIONES.7.mar.16.docx)

abrazo

**Comment by braulio-evangelisti** [comment]
Hecho.

**Comment by LeandroBraier** [comment]
Gracias @braulio-evangelisti !

Un detalle más en la Comunidad VIE TUR ya que estamos.

En la home, donde dice JUGA SUMA Y GANA

Dice: _Todos los puntos que puedas subiendo tu foto, conectando tu facebook, disfrutando y compartiendo nuestros contenidos o jugando a los diferentes desafíos._

Cambialo por:
_Todos los puntos que puedas subiendo tu foto, conectando tu facebook, compartiendo nuestros contenidos, jugando a los diferentes desafíos y, sobre todo, vendiendo productos VIE TUR._

Confirmame cuando esté

abrazo

**Comment by braulio-evangelisti** [comment]
Listo ;)

**Comment by LeandroBraier** [comment]
Gracias Brau!

**Comment by LeandroBraier** [comment]
@braulio-evangelisti necesito actualizar una vez más las bases. Lo que está en rojo es solo para señalar la parte nueva, pero que quede estéticamente igual que ahora. Solo cambia el contenido.

[Bases y condiciones Comunidad VIE TUR  10-03.docx](https://github.com/LeandroBraier/Vietur/files/167429/Bases.y.condiciones.Comunidad.VIE.TUR.10-03.docx)

**Comment by braulio-evangelisti** [comment]
Hecho.

**Comment by LeandroBraier** [comment]
Mil gracias!!
