### ISSUE TITLE
Mailing de Bienvenida VIE TUR No llega el reenvio

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#8]
@mkreyness me dice Gabriela de VIE TUR que no recibe la copia de todos los mailings de bienvenida como ella había pedido. Puede ser que le caigan al spam?

**Comment by mkreyness** [comment]
El programa funciona igual para todos los mails. 
Ojo que todavia no terminaron de mandarse, ni siquiera se si todos los que en teoria ya mande se despacharon realmente, puede que Duplika lo tenga encolado.
Tambien puede pasar que si  a alguien NO le llega el mail (porque su server se lo rebota a Duplika) tampoco le llegue la copia, pero seguro cualquier mail recibido por el cliente ella TIENE que estar recibiendo la copia. Tal vez con cierto delay si al servidor de vietur.com.ar le parece que estamos abusando.
Otra cosa que veo es que hay muchos mails repetidos (distintas personas con el mismo mail) y eso puede que tampoco le guste al servidor receptor.

**Comment by LeandroBraier** [comment]
MM, entiendo, pero ella me mandó un mail que le mandó a ella un cliente
pero ella no recibió la copia. Te reenvio su mail asi lo ves.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-03-03 18:57 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
cuantos SI le llegaron ?
Este fue el mail numero 24 que se mando, de un total de 309, todos con copia a ella.

**Comment by LeandroBraier** [comment]
@mkreyness adonde estarían llegando ahora los mailings de bienvenida? Seguimos sin recibirlo. 

Si los estás mandando a un mail de @vietur.com.ar mejor empezá a reenviarlos a esta cuenta:

comunidadvietur@gmail.com

abrazo

**Comment by mkreyness** [comment]
A newsletters@vietur.com.ar
Ahi lo cambie a GMail, crucemos los dedos...
Yo creo que el problema es que Duplika cree que vietur.com.ar es este mismo servidor, entonces los esta guardando en algun lugar que nadie en realidad accede.
Probablemente por la misma razon nunca deben haber llegado mails a Alberto o sus empleados.

**Comment by LeandroBraier** [comment]
Esa teoria me gusta. Me queda con esa. Gracias!! Crucemos los dedos.
