### ISSUE TITLE
Usuarios deben sumar 100 puntos por haber asistido al lanzamiento de Comunida VIE TUR

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Vie#9]
@mkreyness te paso una lista de usuarios que deben sumar 100 puntos. Me confirmás cuando estén sumados porfa?

[Usuarios deben sumar 100 puntos solo por haber asistido al lanzamiento de Comunidad VIE TUR.xlsx](https://github.com/LeandroBraier/Vietur/files/159327/Usuarios.deben.sumar.100.puntos.solo.por.haber.asistido.al.lanzamiento.de.Comunidad.VIE.TUR.xlsx)

abrazo

**Comment by mkreyness** [comment]
100 puntos + 1 ficha seria ?
cargale algun tema + juego que sea esto, y yo le vuelco.

**Comment by LeandroBraier** [comment]
Sip.

Hecho. El tema es "Asistencia a Evento VIE TUR" ID=12

**Comment by mkreyness** [comment]
Ojo que hay codigos de usuario que me pasaste que NO SON esos, por ejemplo BenjaminRozemberg tiene codigo BRozemberg0, se debe haber dado de alta por su cuenta.

**Comment by LeandroBraier** [comment]
Ah, ok. De ultima pasame los que no están registrados y te busco los
usuarios reales.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-03-04 17:59 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Ese era facil porque lo encontre, pero por ejemplo hay una tal ValeriaRodriguez que no me figura de ninguna manera.

**Comment by LeandroBraier** [comment]
Por eso, sumale a todos los que puedas y pasame los pendientes que yo te
los macheo.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
JazminBrizzi  
OsvaldoSaporiti 
ValeriaRodriguez

**Comment by LeandroBraier** [comment]
Jazmin y Valeria no están anotadas.

Osvalo Saporiti es:

OSaporiti1

**Comment by mkreyness** [comment]
listo ya le di sus puntos y su ficha a Saporiti. Esta todo cargado entonces.
Si en algun momento das de alta a estas Jazmin y Valeria se le pueden cargar los puntos/fichas en ese momento.

**Comment by LeandroBraier** [comment]
Gracias MK!
